### ISSUE TITLE
Empty TreeTable body when virtualScroll used with flex scroll

### ISSUE THREAD

**Issue by mfig** [primefaces/primeng#9545]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Issues is visible in documentation, only table header is visible, 
https://www.primefaces.org/primeng/v10.0.3/#/treetable/flexscroll

**Current behavior**
There are no rows visible. The only thing that is displayed are caption & table header

![image](https://user-images.githubusercontent.com/8777355/99676405-be2d1600-2a78-11eb-98f5-6563aec964b0.png)

Isues does NOT occur when use fixed height, for example `scrollHeight="300px" [virtualScroll]="true"`
Permanent issue when `scrollHeight="flex" [virtualScroll]="true"`

**Expected behavior**
Whole treetable should be displayed with rows.

* **Angular version:** 10.1.2

* **PrimeNG version:** 10.0.3

* **Browser:** [all | Chrome XX | Firefox XX  ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by yigitfindikli** [comment]
You can find FlexScroll demo at [Flexible Viewport](https://www.primefaces.org/primeng/showcase/#/treetable/scroll)

**Comment by mfig** [comment]
Flex itself is ok.
Flex with virtual scroll is not ok.
You still can see issue at [Virtual Scrolling with Full Page Viewport](https://www.primefaces.org/primeng/showcase/#/treetable/flexscroll).

**Comment by mfig** [comment]
May I follow up on this issue.
Since the [demo](https://www.primefaces.org/primeng/showcase/#/treetable/flexscroll) is still not working I believe it should not be closed yet.

**Comment by danbord** [comment]
I have the same issue with the PTreetable component.  Whenever I set scrollHeight="flex" and [virtualScroll]="true" the data is not shown.  It works fine when either change one of the following : scrollHeight="400px" or [virtualScroll]="false"

**Comment by afkos** [comment]
I have the same problem with PrimeNG 11.3.2
Could you reopen the issue?

**Comment by QuietDevLife** [comment]
Same Problem with PrimeNG 11.0.0.
@yigitfindikli just try primeNG demo and change scrollHeight to flex in the stackblitz...
![image](https://user-images.githubusercontent.com/83551363/121839778-18bee580-ccdb-11eb-9c08-f6861c40612a.png)

**Comment by pete4dev** [comment]
The same problem in 11.4.2

**Comment by intoxopox** [comment]
Same here. Still broke. Please reopen.

**Comment by satoshisound** [comment]
Also seeing this issue. Please help.

**Comment by giesmininkas** [comment]
Still seeing this issue in PrimeNG 12.2.2. Please reopen.

**Comment by Christopherjl** [comment]
Hi Same Issue here

**Comment by Kszemi** [comment]
Hi, same issue still here

**Comment by Philippvs** [comment]
Hi, same issue still here

**Comment by eukuz** [comment]
Hello, same issue still here
