### ISSUE TITLE
Let the user choose where to place a DynamicDialog rather than in body

### ISSUE THREAD

**Issue by john8329** [primefaces/primeng#9546]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When creating a DynamicDialog, PrimeNG creates an element as a direct child of the <body>  element. This is non-configurable.

**Expected behavior**
It'd be nice to have a parameter like `appendTo` to specify which element to attach the dialog to. I need to wrap every element created in a <div> but right now it's not possible.

**What is the motivation / use case for changing the behavior?**
The aim is to block the entire UI with a graphic filter when the app is in the "reconnecting" state. The filter can be applied to a divider that contains the entire UI.

* **Angular version:** 9

* **PrimeNG version:** 9.1.3

**Comment by ferikeem** [comment]
I would also like this feature. I implemented a global context-menu (for translating labels and stuff), and it doesn't work on dynamicdialog. Now there are possible solutions to this, but it would be much cleaner to append the dynamicdialog to a top-level div (or something). The contextmenu does work in the (plain) dialog component.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by john8329** [comment]
The issue is still relevant, although as a workaround I'm closing all dialogs when the app displays the "reconnecting" overlay.

**Comment by shayl29** [comment]
@mertsincan I have created a PR for this request
https://github.com/primefaces/primeng/pull/12283
