### ISSUE TITLE
Remove FilterUtils

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#9548]
In favor of the new FilterService, FilterUtils is obsolete now and we had to remove it.

https://github.com/primefaces/primeng/issues/9547

**Comment by lf-novelt** [comment]
Could you elaborate on how `FilterService` replaces `FilterUtils`?

Do you just need to replace the import by 
`import { FilterService } from 'primeng/api/filterservice';`

and then inject `private filterService : FilterService` ?
