### ISSUE TITLE
p-fileUpload  invalidFileSizeMessageSummary

### ISSUE THREAD

**Issue by haidaRJW** [primefaces/primeng#9549]
I am using the p-fileUpload component of PrimeNG.

Code Snippet:

<p-fileUpload #uploadFiles name="myfile[]" mode="advanced" (onSelect)="handleCustomUpload($event,accordionIndex,item)" multiple="multiple" (onRemove)="handleRemove($event)" invalidFileSizeMessageSummary="{0} has wrong size, " invalidFileSizeMessageDetail="it exceeds {0}." maxFileSize="1000000">

However, When I am selecting a file which exceeds the maxFileSize, that file is not selected but I am not able to see the invalidFileSizeMessageDetail or invalidFileSizeMessageSummary

In few places, it is mentioned that the mode should be advanced but after changing that also it is not working.

Can anyone please help me with this problem.

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.
