### ISSUE TITLE
AppendTo body closes MultiSelect in Table

### ISSUE THREAD

**Issue by DustinPham** [primefaces/primeng#9551]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Stackblitz (Bug Reports)**

https://stackblitz.com/edit/primeng-tableedit-demo-appendto

**Current behavior**

Selecting a multiSelect option will close when appendTo is set. Same as old ticket here: [https://github.com/primefaces/primeng/issues/2345](https://github.com/primefaces/primeng/issues/2345)

**Expected behavior**

Selecting a multiSelect option will keep the multiSelect open and able to click other options.

**Minimal reproduction of the problem with instructions**

Using the primeng documentation [https://www.primefaces.org/primeng/showcase/#/table/edit](https://www.primefaces.org/primeng/showcase/#/table/edit) you can take their example via Edit in Stackblitz and change the p-dropdown to p-multiSelect. 

Done here: https://stackblitz.com/edit/primeng-tableedit-demo-appendto

**What is the motivation / use case for changing the behavior?**

Ability to use multiSelect within tables.

* **Angular version:** 11.X

* **PrimeNG version:** 11.X

My environment uses v9, but 11 also has the issue as shown in stackblitz

* **Browser:** Chrome 86.0.4240.198

 
* **Language:** TypeScript 4.X

**Comment by Naveed1842** [comment]
Hi is there any update on this issue @yigitfindikli

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
