### ISSUE TITLE
regression(confirm-dialog): Labels are not working on v11.0.0.rc.1 via template variable 

### ISSUE THREAD

**Issue by KapilSachdev** [primefaces/primeng#9552]
**I'm submitting a ...** 
- [x] bug report => Search github for a similar issue or PR before submitting

This seems like a regression as there seems to be no `changelog` entry describing any behavioural changes.
When confirm dialog labels are accessed via template variables, labels such as accept, reject etc are no more added to the DOM. The methods `accept()` and `reject()` seems to be to working as expected.
_However adding them as text works as expected._

The use case works fine in ~10.0 but is failing in ~11.0.0.rc.1,  

**Plunkr Case (Bug Reports)**
Changing the primeng version in the `stackblitz` from 11(rc) to 10 works as expected
https://stackblitz.com/edit/github-x8vfrl

**Current behavior**
Labels via template variable are not accessible.

**Expected behavior**
Labels should be accessible via template variable.

View:
```html
<button pTooltip="Delete" (click)="confirm()">
  Delete
</button>
<p-confirmDialog [closable]="false" width="425" #inputSwitch>
  <p-footer>
    <button type="button" class="btn btn-default btn-sm" (click)="inputSwitch.reject()">
      {{inputSwitch.rejectLabel}}
    </button>
    <button type="button" class="btn btn-danger btn-sm" (click)="inputSwitch.accept()">
      {{inputSwitch.acceptLabel}}
    </button>
  </p-footer>
</p-confirmDialog>
```
Component:
```ts
  public confirm() {
    this.confirmationService.confirm({
      header: "Delete ",
      message: "Are you sure you want to delete?",
      acceptLabel: "Delete",
      rejectLabel: "Cancel",
      accept: () => {},
      reject: () => {}
    });
  }
```

**Please tell us about your environment:**
Linux, VS Code

* **Angular version:** 11.0

* **PrimeNG version:** 11.0.0.rc.1 

* **Browser:** all
 
* **Language:** TypeScript 4.0

* **Node (for AoT issues):**  14.15

**Comment by yigitfindikli** [comment]
Hi,

You can use rejectButtonLabel and acceptButtonLabel instead of acceptLabel and rejectLabel.

Regards.

**Comment by KapilSachdev** [comment]
Thanks for the reply @yigitfindikli .
I should have gone through the commits in the changelog as well.
I see that 5073c16 introduced this.
