### ISSUE TITLE
PrimeNG 9.1.3 - Table virtual scrolling and filtering do not function together correctly

### ISSUE THREAD

**Issue by parky128** [primefaces/primeng#9553]
### PrimeNG 9.1.3 - Table virtual scrolling and filtering do not function together correctly

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Stackblitz Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewed in detail and assisted.

https://stackblitz.com/edit/primeng9-table-virtualscroll-with-filtering?file=src/app/app.component.html

**Current behaviour**
As per the demo URL above, just filter by any of the columns of data that are returned, e.g. a brand name and observe how the original data in the table remains unfiltered.

I have added additional console output to the table's `onFilter` event to confirm the underlying is being filter out correctly.

**Expected behaviour**
I would expect the table to filter the table rows correctly!

My suspicion here is that this is down to an internal problem with how the CDK virtual scroller has been implemented with the p-table component.

Removing the `[virtualScroll]="true" [virtualRowHeight]="34"` in the stackblitz demo returns the filtering functionality back to normal BUT that loses the benefit of having the virtual scroll being enabled. I would like to have both features working together here.

**Minimal reproduction of the problem with instructions**

See stackblitz case details above

**What is the motivation / use case for changing the behaviour?**

Note I am working on a v9 app thats not yet in a state to be migrated to primeng v10+ yet where i know this issue of combining virtual scrolling and filtering on primeng tables doesn't exist, so I'm trying to find a workaround for the latest public non-pro version of v9.

Any help here will be greatly appreciated 👍 

**Please tell us about your environment:** Mac OS X (VS Code IDE)

* **Angular version:** 9.1.12

* **PrimeNG version:** 9.1.3

* **Browser:** Chrome
 
* **Language:** all

**Comment by yigitfindikli** [comment]
Thanks for reporting, Fixed in v9-lts v10-lts v10 and v11.

**Comment by parky128** [comment]
@yigitfindikli - ok, sure I understand it has been fixed since but what was the actual fix, I need to be able to replicate this solution.

**Comment by Ankit-Taneja** [comment]
@parky128 - Were you able to replicate the solution? 
https://github.com/primefaces/primeng/commit/84a1275ea09499a1bbf26223f47682bdf07493d9
If yes, Could you please let me know
