### ISSUE TITLE
Tree folder node indent in RTL Mode is not correct

### ISSUE THREAD

**Issue by webnegar** [primefaces/primeng#9554]
[* ] bug report => 

For tree component in RTL mode, folder indent doesn't work correctly.

 
![bug](https://user-images.githubusercontent.com/7112978/99874303-ff99fe80-2bfb-11eb-8009-c47819a34bec.jpg)

**Comment by orshtar** [comment]
Hello,
I'm having the same issue,
Have you managed to solve it somehow?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by msdastlan** [comment]
hi your problem will be solved by using this styles

    enter code here
    .p-tree .p-tree-container .p-treenode {
      padding: 0.143rem;
      padding-right: 1rem;
    }
    .p-treenode-label{
      padding-right: 0.5rem;
    }
    enter code here
