### ISSUE TITLE
p-splitbutton has html entity "&nbsp;" rendered as a text

### ISSUE THREAD

**Issue by pkunitsky** [primefaces/primeng#9557]
I'm submitting a bug report

* **Angular version: ~11.0.2
* **PrimeNG version: ^11.0.0-rc.1

TLDR: The component p-splitbutton has incorrect rendering showing `&nbsp;` as text.
LOCALIZATION: p-splitbutton -> p-button-label outputs &nbsp; as text, but should be HTML

**Comment by salvadormarcos** [comment]
I have the same problem with p-button

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
