### ISSUE TITLE
MultiSelect not working when Objects contain property "value"

### ISSUE THREAD

**Issue by Timmeeeey** [primefaces/primeng#9561]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-multiselect-demo-xda4gx

**Current behavior**
If you select options which have a property "value" they are not marked as checked.
```
this.cities = [
      { name: "New York", value: "NY" },
      { name: "Rome", value: "RM" },
      { name: "London", value: "LDN" },
      { name: "Istanbul", value: "IST" },
      { name: "Paris", value: "PRS" }
    ];
```
![image](https://user-images.githubusercontent.com/46870283/99969587-fd21db00-2d9a-11eb-9ae5-8af5cb7f3363.png)

* **Angular version:** 11.X

* **PrimeNG version:** 11.X

**Comment by meistaiwan** [comment]
Seconded, I have to change my SelectItems to a custom {mylabel:string;myvalue:string} with multi-select option optionLabel="mylabel". The filter function returns the value in a format option1,option2 when using selectitem in multiselect

**Comment by ODB-Gideon** [comment]
Hi, same issue for me. I am using multiselect with table for filtering a single column. The filtering works but the checkboxes are not shown as selected.

I am using `optionalLabel = "name"` and `optionValue="myVal"`

The object interface looks like:
`
{ name: string; myVal: el.string}
`

I have tried combinations of adding label and value keys to the object and removing optionalLabel and optionValue from the html and no combination works entirely.

I have however noticed:
1. Setting optionValue or placing a value key in the object results in the filter working but the checkboxes not showing
2. Removing optionValue and removing a value key in the object results in the checkboxes showing but the filter not working.

Thank you for your time!

**Comment by incode4it** [comment]
HI. I'm having the same issue
