### ISSUE TITLE
Custom toasts not stacked

### ISSUE THREAD

**Issue by Michael881188** [primefaces/primeng#9562]
```
[ x] bug report => Search github for a similar issue or PR before submitting

```

**Plunkr Case (Bug Reports)**
https://primeng-toast-demo-dz93fy.stackblitz.io

**Current behavior**
I implemented two custom p-toast templates with different keys, when i call both of them there are not stacked.
Custom toasts do not stack

**Expected behavior**
Stacked toasts.

**Minimal reproduction of the problem with instructions**
Just click :'Click me' you will see two toasts on each other

* **Angular version:** 11.0

* **PrimeNG version:**11.0.0-rc.1

* **Browser:** Chrome/Firefox

**Comment by KYRY001** [comment]
is it alive?

**Comment by cetincakiroglu** [comment]
Hi,

We couldn't replicate the issue with the latest PrimeNG (v13).
If the issue still exists with the latest PrimeNG version, please provide a StackBlitz example by using [PrimeNG Issue Template ](https://stackblitz.com/github/primefaces/primeng-issue-template) and re-open the issue.

Regards

**Comment by KYRY001** [comment]
Hi @cetincakiroglu , sure, i can reproduce it :-) 
Here is example: https://stackblitz.com/edit/github-1metrx
Steps to reproduce:
Click on 1 button, then click on 2nd one.
Toasts are overlapping

<img width="705" alt="image" src="https://user-images.githubusercontent.com/60639223/160436682-0fdeeced-f026-4a98-a898-476331c9855d.png">

**Comment by Michael881188** [comment]
I'm not able to reopen it as well. @cetincakiroglu closed it, not me.

**Comment by KYRY001** [comment]
@Michael881188 i created new one https://github.com/primefaces/primeng/issues/11366
