### ISSUE TITLE
Table Column Filtering By Date Should have Custom Date Format Option

### ISSUE THREAD

**Issue by souravsaraf** [primefaces/primeng#9563]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

Go to the the PrimeNg New Filter Table feature website (v11.0rc1) https://primefaces.org/primeng/showcase/#/table/filter
Filter by Date : 

![Primeng Table Column Filter Date Type Bug](https://user-images.githubusercontent.com/3005625/100003544-3f273d00-2dec-11eb-9eda-d0a642bf64fa.png)

**Expected behavior**

One should have a custom date format option , otherwise the filter options wont work.

Or, I should have an option to call a custom filter function when I click on **"Apply"** where I can do the required calculations to perform the filter. ( Same for **"Clear"** button )

**What is the motivation / use case for changing the behavior?**

Currently every date is displayed in USA format.

**Comment by yigitfindikli** [comment]
You can achieve with our new (i18n API)[https://primefaces.org/primeng/showcase/#/i18n]

**Comment by souravs-2pirad** [comment]
Hi, you have closed the issue without providing a way to achieve the **dateFormat** change.

I have searched the codebase.

1. `<p-columnfilter>` itself does not pass anything to the dateFormat , aka it uses the default. Pertinent Code : 
https://github.com/primefaces/primeng/blob/a7b03ae24f375b2f13d578e2ba0a577f7767bf28/src/app/components/table/table.ts#L3843

2. By default, `p-calendar` uses the default dateFormat = 'mm/dd/yy' unless an **@input** is passed. Pertinent Code : 
https://github.com/primefaces/primeng/blob/a7b03ae24f375b2f13d578e2ba0a577f7767bf28/src/app/components/calendar/calendar.ts#L217

3. The i18n translation api [file](https://github.com/primefaces/primeng/blob/master/src/app/components/api/translation.ts) does not have anything related to **dateFormat** .

Am I missing something? Can you please show how to achieve the dateFormat change.

Thanks

**Comment by lolstatsguy** [comment]
I agree, the behavior as displayed in the picture cannot yet be achieved with i18n.

**Comment by FA007** [comment]
I found a solution in the custom filter section ... all you have to do is to convert the filtered value in your expect date format.

Her is how i done this for me in my special format YYYY-MM-DD for my result set.

As base i took the examples on primeng filter description (https://primefaces.org/primeng/showcase/#/filterservice)

1. declare your filter normal as date as shown in the example
![image](https://user-images.githubusercontent.com/4435657/104092383-e6204500-5283-11eb-9470-fc060ff266dd.png)
(Copyright by PrimeNG)
this is my version of it 
![image](https://user-images.githubusercontent.com/4435657/104092478-80808880-5284-11eb-8c29-6259a783ab16.png)
i disabled the showOperator, cause at my develop state it is not necessary - Match All - Match Any, but you can choose for your own
2. prepare your custom filter and matchmodes - at this step you have to figure out what filter would you choose for your process!
![image](https://user-images.githubusercontent.com/4435657/104092431-35ff0c00-5284-11eb-84c2-8c42ae367fb4.png)
Describe the visible values of the drop-down
![image](https://user-images.githubusercontent.com/4435657/104092456-66df4100-5284-11eb-92d1-9756eddc95ed.png)
3. implement register the filters
As change/difference to previous versions, i recognized, that the format to register a new filter has changed. So be carful, if you use  
![image](https://user-images.githubusercontent.com/4435657/104092601-48c61080-5285-11eb-816f-ecc620a1dad9.png)
As you can imagine, the filter only allows const values, so I decide to took an array with fixed values. In my opinion it is more flexible ...
I wrote my own convert method for my special format to use it in all of my custom filters
![image](https://user-images.githubusercontent.com/4435657/104092584-29c77e80-5285-11eb-8f0f-810db95d3a10.png)
For all comparisons i took the library **moment** 
![image](https://user-images.githubusercontent.com/4435657/104092627-6abf9300-5285-11eb-8ba5-60384ada21bf.png)
4. After all have been done, no lets see how it works
DropDown with my chosen values
![image](https://user-images.githubusercontent.com/4435657/104092668-b5d9a600-5285-11eb-9f53-ce81b6e087cf.png)
For example -> Same as
![image](https://user-images.githubusercontent.com/4435657/104092675-d1dd4780-5285-11eb-9f04-0f75741a603a.png) 
5. One disadvantage couldn't be erased, and this would be the input format of the datepicker ...

I hope this first steps could help someone ...

Kind regards

**Comment by tomstolarczuk** [comment]
If you would like to set certain format for every p-calendar, in your main.ts add this:

`Calendar.prototype.getDateFormat = () => 'dd/mm/yy';`

It's just an ugly hack, because things like this should be configurable somewhere.

**Comment by ssshammi** [comment]
Hello, I still get the  error  when i use dd/mm/yyyy format. 
Uncaught TypeError: value.getTime is not a function
    at dateBefore (api.esm.js:632:1)
I use code like this 
` const [filters1, setFilters] = useState({
      /*  global: { value: null, matchMode: FilterMatchMode.CONTAINS },*/
      "attributes.CourseID.data.attributes.Name": { value: null, matchMode: FilterMatchMode.CONTAINS },
      "attributes.StudentID.data.attributes.username": { value: null, matchMode: FilterMatchMode.CONTAINS },
        'type': { value: null, matchMode: FilterMatchMode.CONTAINS },
        'attributes.createdAt': { value: null, matchMode: FilterMatchMode.DATE_AFTER },
        "attributes.TimeTaken":  { operator: FilterOperator.AND, constraints:[{ value: null, matchMode: FilterMatchMode.GREATER_THAN}] },
        "attributes.Score": { value: null, matchMode: FilterMatchMode.EQUALS }
    });

 const dateFilterTemplate = (options) => {
        return <Calendar id="calendar-24h"  value={options.value } onChange={(e) => options.filterCallback(e.value, options.index)}  dateFormat="dd/mm/yyyy" placeholder="dd/mm/yyyy" mask="99/99/9999" />;
    };
`

Is there a way to filter the dates. I am using version 

   "primeflex": "3.1.0",
        "primeicons": "^5.0.0",
        "primereact": "7.1.0",
        "prismjs": "1.9.0",
