### ISSUE TITLE
HTML attribute events are case-sensitive

### ISSUE THREAD

**Issue by metaloha** [primefaces/primeng#9564]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://github-stuwnd.stackblitz.io

**Current behavior**
The HTML attribute is case-sensitive.

**Expected behavior**
The HTML attribute should not be case-sensitive.

**Minimal reproduction of the problem with instructions**
Create a tooltip-enabled element using `ptooltip` instead of `pTooltip`. The tooltip will not appear.

**What is the motivation / use case for changing the behavior?**
Unfortunately, some libraries (like Highcharts-Angular) convert HTML attributes to lowercase to display in the `canvas` they use.

**Please tell us about your environment:**
Chrome browser on MacOS 10.15

* **Angular version:** 5.X
10.2.3

* **PrimeNG version:** 5.X
10.0.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Chrome 87
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS 4.05

* **Node (for AoT issues):** `node --version` =   
12.18.3

**Comment by cetincakiroglu** [comment]
Hi,

We couldn't replicate the issue with the latest PrimeNG (v13).
If the issue still exists with the latest PrimeNG version, please provide a StackBlitz example by using [PrimeNG Issue Template ](https://stackblitz.com/github/primefaces/primeng-issue-template) and re-open the issue.

Regards
