### ISSUE TITLE
ver. 11.0.0-rc.1 error with table when building in prod.

### ISSUE THREAD

**Issue by gate42srl** [primefaces/primeng#9567]
Hi,
I'm using Mirage Template and I've updated primeNG to ver. 11.0.0-rc.1 to solve a problem with dropdown and model driven form in ver. 10.0.3. Unfortunately now when I try to build my project I got this error :
ERROR in node_modules/primeng/table/primeng-table.d.ts.ColumnFilter.html(16,90): Expected 2 arguments, but got 1.
I've tried to delete node_modules folder and type npm install with no results. 

How can I solve this issue ?
Thanks

**Comment by huseyinkaynar** [comment]
I am in the same situation. 
    "name": "verona",
    "version": "10.0.0",
    "license": "PrimeNG Commercial",
