### ISSUE TITLE
prime-ng 11.0.0-rc1 breaking change accordion custom header 

### ISSUE THREAD

**Issue by pmo1948** [primefaces/primeng#9568]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-xyyi2e?file=src%2Fapp%2Fapp.component.html

**Current behavior**
PAccordionTab is disabled, so it disables all elements in header

**Expected behavior**
In the previous version (10.0.3), I could toggle the accordion tab's disabled from an input switch in the header. Due to changes in 11.0.0-rc1, this no longer works, since the input switch within the header becomes inaccessible

**Minimal reproduction of the problem with instructions**
The logic of the code works in 10.0.3 (see attached stackblitz). However, once the version is updated, toggle can no longer be toggled

**What is the motivation / use case for changing the behavior?**
I do not want my app logic to break bc of a change in primeNg version

* **Angular version:** 
10.1.6 before, 11.0.2 after

* **PrimeNG version:** 
works in 10.0.3, does not work in 11.0.0-rc1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
did it in chrome

**Comment by pmo1948** [comment]
a workaround I have found for now is to add `accordion-inputswitch` as a `styleClass` on the input within the header, and then add the following to the  scss `:host ::ng-deep{ .p-disabled .accordion-inputswitch { cursor: pointer !important; pointer-events: autp; }}

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.3.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again
