### ISSUE TITLE
Table - context menu selection is incorrect when dataKey is specified

### ISSUE THREAD

**Issue by saramcicchi** [primefaces/primeng#9569]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When the following attributes are specified on a table, the selected item does not get updated appropriately.

```
selectionMode="single" [(selection)]="selectedItem" [contextMenu]="cm" contextMenuSelectionMode="joint" dataKey="<something>"
```

After right clicking on more than one row, if you try to right click on any of the rows that have already been clicked on, the selected item will be the last newly clicked row, instead of the last clicked row.

This only happens if the dataKey attribute is specified. If it is not specified, the expected row is selected.

**Expected behavior**
The row that is right-clicked on should be the selected row.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/primeng-tablecontextmenu-demo-v11

**What is the motivation / use case for changing the behavior?**
Right clicking on a row should select that row.

**Please tell us about your environment:**

* **Angular version:** 11.0.0

* **PrimeNG version:** 11.0.0-rc.1

* **Browser:** Chrome and Firefox (and probably others)

 
* **Language:** all

* **Node (for AoT issues):** `node --version` = 12.16.3

**Comment by saramcicchi** [comment]
Note that this is reopening #9035

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
