### ISSUE TITLE
p-menu no longer fades out when you scroll the page in v11.0.0-rc.1

### ISSUE THREAD

**Issue by jonnomk** [primefaces/primeng#9571]
The fix that was applied to address an issue where menu's that use appendTo="body" would not anchor to the button that triggers them on scroll seems to have reverted.

Now, if I use a menu within a scrollable container that has a position set, I have to use appendTo"body" to address one bug where the menu is misaligned, but then when I scroll, the menu 'travels' with the page and not with the triggering button.

Can you not add a mask in scenarios where appendTo="body" is used effectively blocking the scroll until the menu is dismissed in the same way that Angular Material does it?

**Comment by jonnomk** [comment]
This is still not resolved in v11.0.0.  I'm now in a position where I cannot upgrade to the latest version (currently using v10.0.3) because of this regression.  You're previous solution worked quite well when the menu faded out on scroll.  I think it's fair enough to have breaking changes for improvements, but you seem to have removed a solution to a problem in previous versions.

I can't comprehend why there are still issues with the most basic of UI components, the Menu...

Can you not make the default behaviour for the menu to open in the body and as previously suggested add a mask that blocks scroll and serves to dismiss the menu on click?

**Comment by jonnomk** [comment]
Is there a way to add the earlier fix back in so that the menu fades on scroll?  I've updated PrimeNG to latest to take advantage of latest features, but now the menu's travel with the page on scroll.  A lot of progress seems to be being made in other areas except this and the underlying issue of having to use appendTo="body" to work-around an issue with placement of menu's in positioned elements.  Is this not considered a major UX problem @cagataycivici?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
