### ISSUE TITLE
.p-multiselect-label-empty class added to p-multiselect

### ISSUE THREAD

**Issue by Mahfoud047** [primefaces/primeng#9573]
Hello, 
I recently migrated to primeng10.0.3, and I have a strange issue with multi-select component, I have a classe .p-multiselect-label-empty even if I set the filterPlaceHolder property. 
![image](https://user-images.githubusercontent.com/29728197/100216393-83146200-2f12-11eb-9aa8-a7a1674f108e.png)

And when I delete the class from the browser inspector, I find the placeholder:
![image](https://user-images.githubusercontent.com/29728197/100216551-b35c0080-2f12-11eb-9295-36279b9f7d80.png)

Here is my component:
```
<p-multiSelect [options]="options"
               [filter]="true"
               [filterPlaceHolder]="'multiSelect.selectOption' | translate"
               (onChange)="onSelectChanges($event)"
               (onPanelHide)="onHidePanel()"
               [(ngModel)]="fieldModel"
               [panelStyle]="{
                     minWidth:'12em'
                 }">
  <ng-template let-selectedOptions pTemplate="selectedItems">
    <span *ngIf="!fieldModel || fieldModel.length === 0">{{placeholder}}</span>
    <span *ngIf="checkAllSelected(fieldModel) else babbles"> {{ placeholder }} </span>
    <ng-template #babbles>
        <span class="select-line" *ngFor="let val of fieldModel" (click)="onRemoveItem(val, $event)">
      {{getLabel(val)}}<i class="pi pi-times"></i>
      </span>
    </ng-template>

  </ng-template>
  <ng-template let-opt pTemplate="item">
    <div class="select-bubble">{{opt.key}}</div>
  </ng-template>
</p-multiSelect>
```

Can you check this please,
Thanks.

**Comment by Mahfoud047** [comment]
I think that the problem is related to the size of options list, because it workes well with input that have so many options

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a stackblitz example.

**Comment by nithinar** [comment]
Hi,

I am facing the same issue. Please find the below mentioned stackblitz link. When loading default values with custom template, the selected values will not be displayed. And as mentioned in the issue title, **.p-multiselect-label-empty** class is not getting removed when we pre-load values. 

Note: I have added timeout in sample because, we need to get values from API. Without timeout, the selected values will be shown in multiselect.
[https://stackblitz.com/edit/angular-ivy-dj44mj?file=src/app/app.component.ts](url)

**Comment by crazyjavatricks** [comment]
Same issue exists in primeNg version11.4 as well.

**Comment by pratham321** [comment]
add defaultLabel="Choose" and my issue is resolved.
     <p-multiSelect [options]="subGroup.Filters.Filter[filterIdx].FilterValues.FilterValue"
                            [(ngModel)]="subGroup.Filters.Filter[filterIdx].model" optionLabel="FilterValueName" defaultLabel="Choose"

                            (onChange)="sharedData.multiselectDrpChange($event, subGroup, filterIdx)" [filter]="false">
                          </p-multiSelect>
