### ISSUE TITLE
PrimeNG 11, new TabView style does not work with multi-line tabs

### ISSUE THREAD

**Issue by draco2007** [primefaces/primeng#9574]
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Same issue as https://github.com/primefaces/primeng/issues/9426 because it IS replicateable. Again clone tab-header nodes (those are "li"-tags in the DOM) with the debug tool with any browser and make the browser window smaller. See the screenshot below. This is taken from YOUR demo website.
The description below is the same as the old ticket...

If too many tabs in TabView it breaks the line and the selector-line becomes invisible, because of negative margin.

**Expected behavior**
I would expect to see the selector-line below the tab or I would expect a "..." button left of the tabs, where all the tabs are, which do not have space. Like the tabs here at GitHub. (Code, Issues, etc)

**Minimal reproduction of the problem with instructions**
Just add enough tabs so it breaks.
This is how it looks on your own demo page, I just cloned the last tab multiple times:
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
If too many tabs in TabView it breaks the line and the selector-line becomes invisible, because of negative margin.

**Expected behavior**
I would expect to see the selector-line below the tab or I would expect a "..." button left of the tabs, where all the tabs are, which do not have space. Like the tabs here at GitHub. (Code, Issues, etc)

**Minimal reproduction of the problem with instructions**
Just add enough tabs so it breaks.
This is how it looks on your own demo page, I just cloned the last tab multiple times:
![grafik](https://user-images.githubusercontent.com/13048681/100244773-9c7bd500-2f37-11eb-9935-af28a89bf9df.png)

* **Angular version:** "whatever you use on your demo page

* **PrimeNG version:** 11.0.0-rc.1

* **Browser:** [all]
 
* **Language:** [all]

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
