### ISSUE TITLE
Resizable columns with virtual scroll doesn't work with p-treeTable

### ISSUE THREAD

**Issue by AlexStefan** [primefaces/primeng#9575]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

[Stackblitz](https://stackblitz.com/edit/primeng-treetablescroll-demo-8ht22i?file=src/app/app.component.ts) with primeng 10.0.3
[Stackblitz](https://stackblitz.com/edit/primeng-treetablescroll-demo-5ywqjm?file=src/app/app.component.ts) with primeng 11.0.0 rc

**Current behavior**
If you have a treetable with both the resizable columns and virtual scroll when trying to resize a column, app crashes.

**Expected behavior**
The resize should not crash.

**Minimal reproduction of the problem with instructions**
Try to resize a column.

**What is the motivation / use case for changing the behavior?**
n/a

**Please tell us about your environment:**
Stackblitz provided above

* **Angular version:** 5.X
11.0

* **PrimeNG version:** 5.X
10.0.3 and 11.0.0 rc1

**Comment by AlexStefan** [comment]
Also this seems connected with this: https://github.com/primefaces/primeng/issues/8885, which was just close :(

**Comment by yigitfindikli** [comment]
Fixed in https://github.com/primefaces/primeng/commit/3d9cacf56851e3618f7c6b9e1385ecd524b5eaa0 . Thanks for detailed report @AlexStefan.

**Comment by AlexStefan** [comment]
Awesome! Thank you for fixing it!

**Comment by yigitfindikli** [comment]
@AlexStefan You're welcome :) Always happy to help!

**Comment by AlexStefan** [comment]
offtopic a bit: @yigitfindikli can you please also check https://github.com/primefaces/primeng/pull/9358 would be really helpful.
