### ISSUE TITLE
Multiselect on chips display does not update the model when deleting them from the chip icon

### ISSUE THREAD

**Issue by gxenakis** [primefaces/primeng#9579]
I'm submitting a 
[X] bug report

**Current behavior**
On chips display when you delete a chip by clicking the X button the model doesn't refresh

**Expected behavior**
Model should be refreshed like when you unclick from the dropdown list.

**Minimal reproduction of the problem with instructions**
https://primeng-multiselect-demo.stackblitz.io/

**Comment by yaoxiantong** [comment]
![image](https://user-images.githubusercontent.com/22648810/100695997-72aa2e80-33cd-11eb-86ef-53b1be6afd4b.png)
@gxenakis

**Comment by tvbowersz** [comment]
Also discovered this when I was implementing it. Tried both using the formControlName inside of a reactive form as well as just binding with NgModel.  Neither updated the model when removing items using the x inside of the chip

**Comment by andriy101** [comment]
Here is a [question](https://stackoverflow.com/questions/65162913/is-there-any-way-to-know-when-chip-is-removed-in-primeng-multiselect/65163465#65163465) at StackOverflow and here is my [workaround](https://stackblitz.com/edit/primeng-multiselect-demo-ag9pfc)

**Comment by Timmeeeey** [comment]
Besides from that the `onChange` event is not called/emitted when removing a chip.
I don't know if I should open another issue for this or if it fits in here.

**Comment by andriy101** [comment]
No need to open a new issue, my pull request fixes this current issue for both template druiven and reactive forms

**Comment by Timmeeeey** [comment]
@andriy101 
`this.onModelChange(this.value);` is not emitting `onChange`. It is only emitted by `onOptionClick(event)` and `toggleAll(event)`.

**Comment by andriy101** [comment]
> @andriy101
> `this.onModelChange(this.value);` is not emitting `onChange`. It is only emitted by `onOptionClick(event)` and `toggleAll(event)`.

I added onChange emit with new value and the mouse event passed from the template via `(click)` function.
