### ISSUE TITLE
ConfirmDialog displays stale data -> dialog is not reusable

### ISSUE THREAD

**Issue by linkvt** [primefaces/primeng#958]
Hi,

I have a view where there is a list on the left side and the view of the selected item on the right side. The view on the right side has a delete button that uses the bound data of the list.
There is a `<p-confirmDialog></p-confirmDialog>` element in this view to confirm the deletion.

When calling `confirm` of the `ConfirmationService` several times, the dialog still shows the data (header, icon, message) of the first `confirm` call.

The problem lies here: [confirmdialog.ts#L100](https://github.com/primefaces/primeng/blob/master/components/confirmdialog/confirmdialog.ts#L100)
After the first `confirm` call (or already when defining the `p-confirmDialog` element with attributes) the fields `message`, `icon` and `header` are filled.
This means that ALL subsequent calls will have no effect on these fields, since they are already set.

IMO it should look somehow like this. The dialog fields are only set if the confirmation fields are set - defaults are not overwritten:
```TypeScript
    constructor(protected el: ElementRef, protected domHandler: DomHandler, 
            protected renderer: Renderer, private confirmationService: ConfirmationService) {
        this.subscription = confirmationService.requireConfirmation$.subscribe(confirmation => {
            this.confirmation = confirmation;
            this.message = this.confirmation.message == null ? this.confirmation.message : this.message;
            this.message = this.confirmation.icon == null ? this.confirmation.icon : this.icon;
            this.message = this.confirmation.header == null ? this.confirmation.header : this.header;
```
Another solution would be to store the values from the HTML attributes in separate variables to not reuse values of old confirm calls.

~~Would this kinda be the intended behaviour or is it intended, that the dialog element gets created for each confirmation?~~

**Edit:** The current behavior is not intended according a recent PrimeNg blog post:
> Great thing is the ability to use the same dialog over and over by other actions on the same component.
http://blog.primefaces.org/?p=4113

**Comment by carcigenicate** [comment]
This is still a problem 10 years later. This line causes a continual merging of settings on `this` (the component): https://github.com/primefaces/primeng/blob/22d9ca15d7b5d1e5df32f59e6ca8df301afffa25/packages/primeng/src/confirmdialog/confirmdialog.ts#L465

It's inconsistent too; although that's for the better I guess. Settings like `header` and `message` will bleed into latter uses of the dialog, but the `accept` and `reject` callbacks won't since the associated subscriptions are unsubscribed from when the dialog is closed.
