### ISSUE TITLE
rtl support for float label

### ISSUE THREAD

**Issue by pmo1948** [primefaces/primeng#9580]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
[stackblitz link](https://stackblitz.com/edit/primeng-inputtext-demo-ydvgnw?file=src%2Fapp%2Fapp.component.html)

**Current behavior**
when code is set for rtl ( see [styles set](https://stackblitz.com/edit/primeng-inputtext-demo-ydvgnw?file=src%2Fstyles.css)), float label is on the left, outside of the inputText, both before and after it "floats"

**Expected behavior**
placeholder should stay inside text, regardless of alignment, and function properly

**Minimal reproduction of the problem with instructions**
take the existing stackblitz demo for float label of inputtext and set global direction to rtl and global alignment to right

**What is the motivation / use case for changing the behavior?**
rtl support

* **Angular version:** 11

* **PrimeNG version:** 11 rc1

**Comment by mohammadAlsafadiMetyaf** [comment]
please we need that, there any solution?

**Comment by avnerma** [comment]
for now i did some workaround add some styles to `app.component.scss`

```css
label {
    right:  10px;
    left: unset;
}
```
see fix - [StackBlitz](https://stackblitz.com/edit/primeng-inputtext-demo-78aqqn?file=src/app/app.component.scss)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by PersianKingMajid** [comment]
man i love u so much
