### ISSUE TITLE
P-table p-columnFilter with MultiSelect does not display Selected Checkboxes

### ISSUE THREAD

**Issue by souravs-2pirad** [primefaces/primeng#9584]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

### Test Case : MultiSelect Filter on a String Column

https://stackblitz.com/edit/primeng-tablefilter-demo-mjsylc/

**Current behavior**

Steps to reproduce bug : 

1. Open the stackblitz link
2. In the Agent dropdown, (remove any selected options) select the options "Amy Elsner" and "Asiya Javayant"
3. The Filtering works on the table **but** the Selected items are **NOT** marked with Blue checkboxes. Output would be something similar to the below image : 

![image](https://user-images.githubusercontent.com/40688353/100393659-6be38a80-3060-11eb-8395-98e28779a328.png)

**Expected behavior**

Selected items in a multiselect **SHOULD** be marked with blue checkboxes

Any help would be appreciated.

P.S On the New Table [Filters Demo Page](https://primefaces.org/primeng/showcase/#/table/filter), can you please add an example where a MultiSelect filter is applied on a **string** column like "Name" or "Status" using the "in" matchmode.

Thanks 😀

**Comment by souravs-2pirad** [comment]
Ok, finally I solved it. 👍 

I needed only an array of strings in the multi-select as [options]. optionsLabel and optionsValue should not be passed.

https://stackblitz.com/edit/primeng-tablefilter-demo-umkfkp

**Comment by dsharkou** [comment]
You can pass `[(item: any) => item]` into `filterBy`
