### ISSUE TITLE
Toast styling inconsistent.

### ISSUE THREAD

**Issue by negberts** [primefaces/primeng#9585]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

The styling of the toast is inconsistent. When you use the regular toast the close button is up right:
![image](https://user-images.githubusercontent.com/20299260/100429097-22f9f900-3095-11eb-84a4-9bf9426096a1.png)

When you use the template for the toast the close button is on the left:
![image](https://user-images.githubusercontent.com/20299260/100429137-34430580-3095-11eb-8f5f-be30ecdeae6a.png)

It's confusing for users. Please move the close button on the template also to the right.

See https://primefaces.org/primeng/showcase/#/toast

**Comment by cetincakiroglu** [comment]
Hi,

We couldn't replicate the issue with the latest PrimeNG (v13).
If the issue still exists with the latest PrimeNG version, please provide a StackBlitz example by using [PrimeNG Issue Template ](https://stackblitz.com/github/primefaces/primeng-issue-template) and re-open the issue.

Regards
