### ISSUE TITLE
PanelMenu no longer highlights expanded menu items

### ISSUE THREAD

**Issue by KeithGillette** [primefaces/primeng#9586]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
PanelMenu expanded menu items are not highlighted.

**Expected behavior**
PanelMenu expanded menu items are highlighted.

**Minimal reproduction of the problem with instructions**
Compare the behavior of the [v9-LTS PanelMenu Showcase Demo](https://www.primefaces.org/primeng/v9.2.0-lts/#/panelmenu) with the [v11.0.0-rc.1 PanelMenu Showcase Demo](https://www.primefaces.org/primeng/showcase/#/panelmenu): In versions before PrimeNG 10, the expanded parent menu gets highlighted with a change in background color via the application of the `.ui-state-active` class, but this behavior was removed when menus were migrated to PrimeOne, per [the change on line 41 of this commit](https://github.com/primefaces/primeng/commit/c5f3d87e39b6d5f01ca3ffc0ab9af5062bc4e402#diff-a87ef8e07858b812d2f58a0deb22658db3c77c0d7d1b09a0e7b5667a88bac9d7L41).

**What is the motivation / use case for changing the behavior?**
This change seems like a regression, as previously supported behavior has been removed.

**Please tell us about your environment:**

* **Angular version:** 10.1.5
* **PrimeNG version:** 11.0.0-rc.1
* **Browser:** all
 * **Language:** TypeScript 4.0.3
* **Node (for AoT issues):** 12.18.4

**Comment by Wandmalfarbe** [comment]
@yigitfindikli This is kind of an essential thing for a menu to have. Is there an estimation when this bug will be fixed?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
