### ISSUE TITLE
Problem P-Dropdown with version 9

### ISSUE THREAD

**Issue by laperez** [primefaces/primeng#9588]
Hi,

I am using the p-dropdown component to load a list of options that come from the rest api.

Initially when I load p-dropdown options I set them to [{label: "", value: ""}] and perfect.

When subtract api returns the result to load the options, a problem occurs when selecting the default item.

The optionLabel assigns it a default label, causing a change in the options. The change is the following:
{label: "3", value: "3"} - {label: "3", value: {label: 3, value: "3"}}

Translated with www.DeepL.com/Translator (free version)

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a stackblitz example.
