### ISSUE TITLE
Carousel page property don't work

### ISSUE THREAD

**Issue by Ramboqui** [primefaces/primeng#9589]
Hi

I'm using p-carousel on V9.2.0-LTS and I'm using property page to set first page, but even if it is on the second page, it displays the data for the first item in the array. There seems to be some problem with the let-item.
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

https://stackblitz.com/edit/github-e6zaqd?file=src/app/app.component.html

**Current behavior**
Carousel open page 2 but display page 1 data

**Expected behavior**
Carousel open page 2 and display page 2 data

* **Angular version:** 9.1.12

* **PrimeNG version:** 9.2.0-LTS

**Comment by yigitfindikli** [comment]
Fixed at https://github.com/primefaces/primeng/issues/8739 . Will be added to LTS versions too.
