### ISSUE TITLE
DataTable filtering keyboard entry being cleared

### ISSUE THREAD

**Issue by gatapia** [primefaces/primeng#959]
This is a hard one to explain but quite easy to reproduce.

Go to: http://www.primefaces.org/primeng/#/datatablefilter in Chrome (have not tested in others).

On any column (Vin for instance) type a letter, wait a second, backspace, wait a second, **enter a letter**.

This second letter sometimes gets cleared, I assume this is to do with data binding.

**note:**  Timing is critical for this, so just keep trying with faster and slower key presses.

**Comment by gatapia** [comment]
I have created a gif showing this issue:
![rimeng20161010090543](https://cloud.githubusercontent.com/assets/135965/19224060/211e009e-8ec9-11e6-94c6-a0ba70b2459c.gif)

In the gif, the last clearing of the 'a' is not done manually, i.e. the bug eats this 'a'.

**Comment by shahmirn** [comment]
@gatapia I've created a PR to fix this issue as my team ran into it also.

**Comment by cagataycivici** [comment]
Please provide a plunkr as we couldn't replicate yet.
