### ISSUE TITLE
p-table flexscroll missing documentation

### ISSUE THREAD

**Issue by ProfEibe** [primefaces/primeng#9592]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Documentation-site of table-flexscroll does not include any source-code or additional information how to use this feature.
https://primefaces.org/primeng/showcase/#/table/flexscroll

**Comment by yigitfindikli** [comment]
You can check at https://primefaces.org/primeng/showcase/#/table under theFull Page Scroll.
