### ISSUE TITLE
Fractions for p-rating

### ISSUE THREAD

**Issue by ProfEibe** [primefaces/primeng#9594]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
p-rating currently only supports integer numbers.
it would be great if it could support fractional numbers too, at least for displaying values.

For example full stars and half stars are displayed and if it is something in between the neares value is shown.
3.1 value => 3 stars
3.4 value => 3.5 stars
3.73 => 3.5 stars
...

this would be great. And an icon with an half filled star would be necessary for this.

I believe amazon is doing it like this.

**Comment by l-Legacy-l** [comment]
Any news ?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
