### ISSUE TITLE
Version used in Showcase is not released?

### ISSUE THREAD

**Issue by wederer** [primefaces/primeng#9595]
The primeNG showcase uses version 10.0.5, but this version is not even released via npm?

https://www.primefaces.org/primeng/v10.0.5-lts/#/tristatecheckbox
![image](https://user-images.githubusercontent.com/2777122/100720456-4f2bb780-33be-11eb-8d4e-021dce4b004b.png)

When will 10.0.5 or 10.1.0 be released? We found some bugs in the current version (10.0.3).

**Comment by yigitfindikli** [comment]
LTS and public releases are different. You can read about lts license at https://primefaces.org/primeng/showcase/#/lts .
