### ISSUE TITLE
Language Support Column Filter Menu

### ISSUE THREAD

**Issue by Tr1monster** [primefaces/primeng#9596]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation / use case for changing the behavior?**

As an company in germany we want to display the filter options in the column filter menu in german language. I could not see a solution for this purpose. In the current documentation is nothing mentioned. I think this is not an uncommon use case. So maybe there is an solution. Then please tell me. By now i have to disable this feature.

**Please tell us about your environment:**

* **Angular version:** 11

* **PrimeNG version:** v11.0.0-rc2

**Comment by yigitfindikli** [comment]
Language support already exist in v11. You can check our new [I18n API](https://primefaces.org/primeng/showcase/#/i18n).

**Comment by Tr1monster** [comment]
This is exactly what I need. Thank you!
