### ISSUE TITLE
Dropdown with 'null' in option values throws errors

### ISSUE THREAD

**Issue by crumhorn** [primefaces/primeng#9599]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report 
```
**Current behavior**
In PrimeNG prior to v11. You could have dropdowns with null values in the bound objects. Example:

`let myObjects = [null, "a", "b", "c"]`
and bound as:
`[options]="myObjects"`

As of v11, this now throws multiple errors, as all option checking code in the dropdown don't expect that there can be a null in there. For example the code that fetches the option value...

```
getOptionValue(option) {
      return this.optionValue ? ObjectUtils.resolveFieldData(option, this.optionValue) : (option.value !== undefined ? option.value : option);
    }
```    

...does not take into account that "option" could be null, so it'll throw an error

This is pretty standard dropdown behavior as users are used to selecting the first "blank" value to clear the combo without having to resort to a clear button and the like.

Not sure if MultiSelect has same issue, but it may have.

**Expected behavior**
That there is no breaking change from pre-11 to 11 in regards to having nulls in the options. As working around this seems nearly impossible.

* **Angular version:** 5.X
11.0.2

* **PrimeNG version:** 5.X
11.0.0-rc.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Latest Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS 4.0.2

**Comment by yigitfindikli** [comment]
Fixed in https://github.com/primefaces/primeng/commit/46cb5069a3f42a2ff5918d7cdfcef3713c088a72
