### ISSUE TITLE
"expression changed after it was checked" in Dialog::ngAfterViewChecked

### ISSUE THREAD

**Issue by ErikWallin** [primefaces/primeng#960]
**I'm submitting a ...**

```
[X] bug report
```

**Current behavior** 
Angular sometimes throws exception "expression changed after it was checked" when reopen Dialog component. This only happens in development mode, not when calling enableProdMode from @angular/core

This is the code, which causes the problem (components/dialog/dialog.ts line 191):
ngAfterViewChecked() {
  if(this.shown) {
    this.onAfterShow.emit({});
    this.shown = false; // <-- Modifies view
  }
}

From Angular's documentation:
https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html#!#afterview
"""Because we must adhere to Angular's unidirectional data flow rule which says that we may not update the view after it has been composed. Both hooks fire after the component's view has been composed.

Angular throws an error if we update component's data-bound comment property immediately (try it!).
"""

The following code works
ngAfterViewChecked() {
  if (this.shown) {
    this.onAfterShow.emit({});
    window.setTimeout(() => {
      this.shown = false;
    });
  }
}

Is this a good idea?

**Expected behavior**
The Dialog component should not throw exception on normal usage in development mode

**Reproduction of the problem**
Do not have a plunker yet.

**What is the motivation / use case for changing the behavior?**
Bug
- **Angular version:** 2.0.0-final

**Comment by garethlewis** [comment]
You shouldn't try and limit this to only the dialog component.  Any component that Prime has that needs to dynamically change content based on a trigger should handle this situation.

I just looked at the logger component on the page you linked and basically the prime guys could easily take that idea of a service that is injected into every component and just use it to update the display.  The two methods tick and tick_then just initiate a setTimeout for 0 ms and then run the code you passed in the lambda.

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
