### ISSUE TITLE
Overlays are closed when scrolling components without appendTo set

### ISSUE THREAD

**Issue by tmc101** [primefaces/primeng#9604]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
For components with overlays and without  an appendTo value, when the page is scrolled:

PrimeNg 9 leaves the overlay visible.
PrimeNg 10 closes the overlay.
PrimeNg 11 leaves the overlay visible.

**Expected behavior**
I would expect v10 to work the same as versions 9 and 11 i.e. leave the overlay visible when appendTo is not set. 

**Minimal reproduction of the problem with instructions**

It is possible to see the different behaviours here:

https://www.primefaces.org/primeng/v9.2.0-lts/#/dropdown
https://www.primefaces.org/primeng/v10.0.5-lts/#/dropdown
https://www.primefaces.org/primeng/showcase/#/dropdown

Select the 'Single' dropdown to show the overlay, then scroll the page slightly.

**What is the motivation / use case for changing the behavior?**
Consistent behaviour.

On dialogs with an overlay component near the end, it is impossible to scroll the overlay into view in v10.

Scrolling the dialog closes the overlay.

PrimeNg 11 is still RC at time of posting.

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
