### ISSUE TITLE
Paginator / Table: Configurable Dropdown Icon

### ISSUE THREAD

**Issue by jBuchholz590** [primefaces/primeng#9605]
**I'm submitting a ...**
```
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
```

**Current behavior**
The paginator uses the dropdown to display a list of available `rowsPerPageOptions`.
The dropdown offers the customization of the dropdown icon via `dropdownIcon` property. This property cannot be set from the paginator resulting in the default value of `pi pi-chevron-down` being used.

In my example I am using FontAwesome Icons throughout my application but cannot exchange icons of the paginator.

**Expected behavior**
Paginator should also have a property `dropdownIcon` that is passed on to the dropdown.
subsequently the table should offer the same property that gets passed to the paginator.

* **Angular version:** 11

* **PrimeNG version:** 11.0.0-rc.2

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by sc-atompower** [comment]
This remains a current issue.
