### ISSUE TITLE
Allow combination of string value and object suggestions in autocomplete

### ISSUE THREAD

**Issue by anaq1** [primefaces/primeng#9606]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
At this moment autocomplete supports string or objects for both value and suggestions. But there are cases, when value is a string and suggestions are objects and these cases cannot be easily handled. Example: We have a form with Name, Price, Quantity. Name is an autocomplete field. Typing name loads suggestions - objects with Name and Price. Selecting a suggestion should fill the name with string (based on "field" property) and the price can be filled programmatically in onSelect. 

**Expected behavior**
A way to easily handle this case, maybe new property for this.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
