### ISSUE TITLE
There is no directive with "exportAs" set to "#dt"

### ISSUE THREAD

**Issue by erik-ropez** [primefaces/primeng#961]
I'm using data-table and it's working fine but when I try to add reference variable I receive: _There is no directive with "exportAs" set to "#dt"_ 
I'm using http://www.primefaces.org/primeng/#/datatableexport as example. Replacing #dt with ref-dt doesn't help.
What could be an issue?

**Comment by cagataycivici** [comment]
That is strange, what is your Angular 2 version?
