### ISSUE TITLE
pPassword - mediumRegex and strongRegex properties

### ISSUE THREAD

**Issue by thimma11** [primefaces/primeng#9610]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**pPassword directive**

It would be great, if you could provide mediumRegex and strongRegex properties to be able to define custom patterns like its already possible in primevue and primereact.

**Comment by yigitfindikli** [comment]
You can use new p-password component.
