### ISSUE TITLE
Horizontal scrolling + column grouping not working in treeTable (and table)

### ISSUE THREAD

**Issue by arnochauveau** [primefaces/primeng#9627]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-treetablecolgroup-demo-tjs6nc?file=src/app/app.component.html

**Current behavior**
When combining grouped columns and horizontal scrolling according to the samples in the documentation, the result is not as expected. (see StackBlitz sample) 

When setting the width of columns in the colgroup template, and a width  with `[style]="{width:'300px'}"` + `[scrollable]="true"` on the table. The result is that the columns are collapsed/smaller than defined in the colgroup, which results in columns that are printed over each other. Additionally, in the project I'm currently working on, some columns are even not shown while scrolling to the right (cut off).

**Expected behavior**
I expect every col to have the width I defined in the colgroup template. And scrolling to work properly

**Minimal reproduction of the problem with instructions**
See stackblitz, basically a combination of grouped columns + horizontal scrolling

**Please tell us about your environment:**
windows 10, NPM

* **Angular version:** 11.X

* **PrimeNG version:** 
11.0.0-rc.1 in stackblitz, 
^10.0.3 in my local project

* **Browser:**
 all 
 
* **Language:** 
all 

* **Node (for AoT issues):** `node --version` =   14.15.0

Let me know if I can be of assistance to fix this!

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
