### ISSUE TITLE
Can't vertical scroll page on mobile devices with full width PrimeNg carousel

### ISSUE THREAD

**Issue by MathanM** [primefaces/primeng#9629]
I have a full width carousel on a page, most of the area of the page is covered by the carousel. On mobile screen when I try to scroll vertically, it does not work.

You can check the behavior here, try to scroll on image. https://primefaces.org/primeng/showcase/#/carousel

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a stackblitz example.

**Comment by Nabeelhassan** [comment]
Try this @MathanM 

`Carousel.prototype.onTouchMove = noop;`
