### ISSUE TITLE
Sort event should not be triggered if target is clickable

### ISSUE THREAD

**Issue by tamatcho** [primefaces/primeng#963]
Hi,
I have a MultiSelect as template in a datable column header and the column is also sortable,but when clicking to drop down the menu it also sorts the table. Is there a way to separate both use cases?

**Comment by lbamburski** [comment]
adding (click)="onFilterInputClick($event)" on MultiSelect or regular select prevents sorting.

**Comment by tamatcho** [comment]
thanks for the advice but it still not working, I'm getting the exception 'self.context.onFilterInputClick' is undefined as shown in the attached screenshot.
![screen shot 2016-09-26 at 15 58 35](https://cloud.githubusercontent.com/assets/22147189/18836993/7a4cbf24-8402-11e6-8396-25351d19167b.png)

**Comment by lbamburski** [comment]
I was editing Datatable template and put that click event there. Outside of datatable that method doesn't exist.

**Comment by cagataycivici** [comment]
This should also happen when you add an input or button or anchor inside table header. We need to find a way to stop sorting in these cases.
