### ISSUE TITLE
Table AriaLabel For Page Numbers Are Not Clear

### ISSUE THREAD

**Issue by peaverok** [primefaces/primeng#9630]
**I'm submitting a bug report/feature request**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
I am not sure how you would categorize this. You say your table is accessible but this is not good design so I would say it was a bug. You can classify it however you want. You might call it a feature request.

**Current behavior**
The aria labels for page numbers on the table paging system are unclear. The aria labels (and content) for page number buttons are just 1, 2, 3, 4, etc. This is very unclear for blind users. It doesn't tell them anything about what the button does. Think if you are blind and you are hovering over a button that just says "4" on a page. Our accessibility reviewers are not passing us because of this. It is unclear to our end users what these buttons do. 

**Expected behavior**
The aria labels for page numbers should say something like "Go to Page 4" or something to make it clear what the button does. In addition, any similar situations throughout primeng should be reviewed and fixed. If you generate something and we as developers can't alter the aria labels you need to make sure they are extremely clear to end users.

**Minimal reproduction of the problem with instructions**
Setup a primeng table with pagination using page numbers.

**What is the motivation / use case for changing the behavior?**
I am a government developer. We need to have our applications accessible by law. Just because you have an aria label doesn't mean it is accessible. The aria label must be clear to a blind user.

* **PrimeNG version:** all

* **Browser:** all

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
