### ISSUE TITLE
Paginator + scroll don't work properly for p-table element

### ISSUE THREAD

**Issue by Pryanishnik** [primefaces/primeng#9633]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
p-table doesn't work properly using paginator and scroll
![image](https://user-images.githubusercontent.com/43049295/101653875-821e1d00-3a48-11eb-8809-6cdad1376213.png)

![image](https://user-images.githubusercontent.com/43049295/101653780-61ee5e00-3a48-11eb-823f-8d44d817bf1f.png)

**Expected behavior**
If you change number of rows in paginator to make it overflows the page height, scroll should appear.

**Minimal reproduction of the problem with instructions**

  ```
<p-table  [value]="fakeData"  [scrollable]="true" scrollHeight="90%" autoLayout="false" [paginator]="true" [rows]="10" [showCurrentPageReport]="true"
             currentPageReportTemplate="Showing {first} to {last} of {totalRecords} entries" [rowsPerPageOptions]="[10,25,50]">
    <ng-template pTemplate="header">
      <tr >
        <th style="border-top-left-radius: 10px">ID</th>
        <th>REPORT NAME</th>
        <th>PERSON NAME</th>
        <th>GROUP</th>
        <th>DATE</th>
        <th style="border-top-right-radius: 10px"></th>
      </tr>
    </ng-template>
    <ng-template pTemplate="body" let-entity>
      <tr>
        <td>{{entity.id}}</td>
        <td>{{entity.reportName}}</td>
        <td>{{entity.personName}}</td>
        <td><div class="group-element"><label class="group-label">{{entity.group}}</label></div></td>
        <td>{{entity.date}}</td>
        <td>
          <i class="pi pi-share-alt"></i>
          <i class="pi pi-print"></i>
          <i class="pi pi-trash"></i>
        </td>
      </tr>
    </ng-template>
  </p-table>
```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 11

* **PrimeNG version:** 11

**Comment by RaviGuggilam** [comment]
is any update on this ?

**Comment by cetincakiroglu** [comment]
Hi,

Could not replicate the issue, could you please provide a reproducer by using https://stackblitz.com/github/primefaces/primeng-issue-template

**Comment by Pryanishnik** [comment]
I created this issue abiut 2 years ago, or something. So, might be it is not relevant anymore

**Comment by cetincakiroglu** [comment]
> I created this issue about 2 years ago, or something. So, might be it is not relevant anymore

Then closing the issue, hope it is solved, or found a workaround
