### ISSUE TITLE
p-dialog event onMaximize does not get invoked

### ISSUE THREAD

**Issue by mmlitvin** [primefaces/primeng#9634]
*  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-dialog-demo-azjihr?file=src%2Fapp%2Fapp.component.html

**Current behavior**
onMaximize event in p-dialog does not get triggered when dialog is maximized or minimized

**Comment by yigitfindikli** [comment]
Fixed in v11-final.
