### ISSUE TITLE
Globally configure p-calendar firstDayOfWeek 

### ISSUE THREAD

**Issue by chrizy** [primefaces/primeng#9635]
[ ] bug report => Search github for a similar issue or PR before submitting
[X ] feature request => Please check if request is not on the roadmap already 

Currently I have to set the firstDayOfWeek in every instance of p-calendar (>100 instances), ideally, I’d like to be able to set it once either in PrimeNGConfig or the new Translation setting in PrimeNGConfig.

I'm Currently using PrimeNG version: 11.0.0

**Comment by miiihi** [comment]
Right, and this is a **breaking change** from v10 not mentioned in the upgrade!

Previously the firstDayOfWeek was part of locale, now it's separate. Why? What was the reasoning to separate it?

**Comment by Seraphe1** [comment]
Was happy to set calendars' config once for our whole app with i18n API, but as we're reaching France here, had to add firstDayOfWeek on our >100 instances too - which I could set once before PrimeNg V10.
I definitely think firstDayOfWeek has its place in PrimeNGConfig

**Comment by vardaru** [comment]
There is no way to set firstDayOfWeek for a p-columnFilter if its type is date. So its is cruicial to have it in PrimeNGConfig

**Comment by WillBoig** [comment]
I have to agree with you, not having first day of week in locale is a big deal for us and requires a lot of boilerplate code to achieve what was previously a one time effort

**Comment by stedel** [comment]
Any updates on integrating this in `PrimeNGConfig` or another "configure once" approach?

**Comment by jakob-bebop** [comment]
We need this. We bought a licence. Please fix it :-)
