### ISSUE TITLE
update angular11 reactive from error  Type 'AbstractControl' is not assignable to type 'FormControl'

### ISSUE THREAD

**Issue by luoxiao-xy** [primefaces/primeng#9636]
After angular11, stricttemplates will be added to tsconfig by default
`"angularCompilerOptions": {
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }`
The checkbox component of primeng uses reactive forms
`<p-checkbox
      name="group1"
      value="San Francisco"
      [formControl]="myFormGroup.controls['cities']"
      inputId="sf"
    ></p-checkbox>`
An error will be reported when starting:
`Type 'AbstractControl' is not assignable to type 'FormControl'.`
But primeng recommends it.
https://primefaces.org/primeng/showcase/#/checkbox

I made a demo project:
https://github.com/luoxiao-xy/primeng-checkbox-demo-error
Welcome clone to come down and have a look. What's the problem!

**Comment by MyKindfu** [comment]
bad bug

**Comment by kakarias** [comment]
same for Angular v10 version and PrimeNg v10 with 

`"angularCompilerOptions": {
        "fullTemplateTypeCheck": true,
        "strictTemplates": true
    }`

**Comment by FabienDehopre** [comment]
This also impacts all the input properties of (almost) all the components. If an input property is bound to a an object property that can be `null` or `undefined`, the compiler complains about the type not being assignable.
```
error TS2322: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.

24         [styleClass]="styleClass"
           ~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by SpiralUp** [comment]
I managed to have a working checkbox when I replace **[formControl]** with **formControlName + value**. For example:

`          <p-checkbox label="Remember me" name="rememberMe" id="rememberMe"
                      class="form-control"
                      formControlName="rememberMe"
                      value="rememberMe"
                      [binary]="true"
          ></p-checkbox>
`

It is not according to primeng recommendations, but it works for me (in Angular 11).

**Comment by rsjunior** [comment]
Same here.

**Comment by lauratondi** [comment]
I managed to fix the error by adding: 

`"compilerOptions":` {
    "strictPropertyInitialization": false,
}

"angularCompilerOptions": {
   "enableIvy": false
  }

**Comment by mafina** [comment]
can you guys try this ?
termsAgreed: [false, Validators.requiredTrue] <---- requiredTrue / False
also my strictPropertyInitialization is set to false.

**Comment by houcemlaw** [comment]
Hi,
just disable strictTemplates in your tsconfig (works with ivy on as well).

"strictTemplates": false

**Comment by khalid7487** [comment]
just disable strictTemplates in your tsconfig 

"strictTemplates": false

**Comment by luoxiao-xy** [comment]
@khalid7487 @houcemlaw I know how to configure it！It is proposed to solve this problem, not to avoid it. After all, the default configuration of angular is now. It has to be solved in the end

**Comment by sengmann** [comment]
You could use the pseudo cast function [https://angular.io/guide/template-typecheck#disabling-type-checking-using-any](https://angular.io/guide/template-typecheck#disabling-type-checking-using-any)

```html
<p-checkbox name="group1" value="San Francisco" [formControl]="$any(myFormGroup).controls['cities']" inputId="sf" ></p-checkbox>```

**Comment by lightbulb110** [comment]
> You could use the pseudo cast function https://angular.io/guide/template-typecheck#disabling-type-checking-using-any
> 
> ```
> <p-checkbox name="group1" value="San Francisco" [formControl]="$any(myFormGroup).controls['cities']" inputId="sf" ></p-checkbox>```
> ```

Looks like this fixes the compiler error. However ".setValue(true)"  still does not work

**Comment by developernader** [comment]
I use vs code, 
I create this formControl

  myForm = new FormGroup({
    name: new FormControl(''),
    age: new FormControl(''),
    address: new FormControl(''),
    Job: new FormControl('')
  });
  
shows an error in age, address, job
I just remove these three controls and write it again working well.

**Comment by steven-rothwell** [comment]
I was able to get around this issue by giving the template direct access to the FormControl as well as adding it to the form in initForm().

.ts

```
form: FormGroup = new FormGroup({});
quantity: FormControl = new FormControl(Quantity.MIN, [
  Validators.min(Quantity.MIN),
  Validators.max(Quantity.MAX),
]);

ngOnInit(): void {
  this.initForm();
}

initForm(): void {
  this.form.addControl('quantity', this.quantity);
}
```

.html (In my case I am passing the FormControl quantity to a custom component that takes a FormControl Input() named "control".)

```
<form [formGroup]="form" (ngSubmit)="submit()">
  <app-select-quantity [control]="quantity"></app-select-quantity>
  <div>
    <button
      mat-flat-button
      type="submit"
      color="primary"
      [disabled]="!form.valid"
    >
      Submit
    </button>
  </div>
</form>
```

**Comment by sengmann** [comment]
I use [this pattern](https://www.thecodecampus.de/blog/refactorable-reactive-forms-in-angular/) for reactive forms. With the formModel property you can access all of your form controls in your template.

```typescript
formModel: {[key in keyof Todo]?: FormControl} = {
    name: new FormControl(null, Validators.required),
    assignedTo: new FormControl(null),
    description: new FormControl(null, Validators.minLength(10)),
    due: new FormControl(null),
  };
  form: FormGroup = new FormGroup(this.formModel);

  constructor() { }

  ngOnInit() {
    this.form.patchValue(this.todoItem);
  }
```

```html
<input type="text" placeholder="Name" [formControl]="formModel.name">
<textarea placeholder="description" [formControl]="formModel.description"></textarea>
<input type="date" placeholder="due date" [formControl]="formModel.due">
<input type="email" placeholder="Email" [formControl]="formModel.assignedTo">
```

**Comment by amirhosein5858** [comment]
also you can define ypur form like this :-)
`form: any;`

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
