### ISSUE TITLE
Datatable: selctionMode="multiple" in a column drops disable usual row selection

### ISSUE THREAD

**Issue by tamatcho** [primefaces/primeng#964]
Hi,
after setting "<p-column selectionMode="multiple"></p-column>" I'm not longer able to select a row without clicking on the checkbox. Is it a design or bug? Because one could want to implement onRowSelect events or selecting multiple rows for delation.

**Comment by cagataycivici** [comment]
Please provide your sample html code.

**Comment by tamatcho** [comment]
It is now working, I guess you fixed it in the last update, thanks:
<p-dataTable [value]="processes" selectionMode="multiple" [(selection)]="selectedProcesses" [paginator]="true" [rows]="10" [responsive]="true" [pageLinks]="3" [rowsPerPageOptions]="[5,10,20]">
        <header>
        	<label>List of Processes</label>
	        <div style="text-align:left">
	            <p-multiSelect [options]="columnOptions" [(ngModel)]="cols"></p-multiSelect>
	        </div>
	    </header>
	    <p-column [style]="{'width':'38px'}" selectionMode="multiple"></p-column>
