### ISSUE TITLE
p-dropdownItem Selector Not Receiving itemSize Value From p-dropdown

### ISSUE THREAD

**Issue by Marshal27** [primefaces/primeng#9645]
I can see the implementation of the `@Input() itemSize: number;` on the `selector: 'p-dropdown'`, and that input value is being passed into to the `cdk-virtual-scroll-viewport`.

I can also see the implementation of the `@Input() itemSize: number;` on the `selector: 'p-dropdownItem`... what I do not see, is the implementation that passes the value from `p-dropdown` into the `p-dropdownItem` ... the `p-dropdownItem` input for `itemSize` doesn't appear to be used.

- Am I confused about how this should work with relation to the `cdk-virtual-scroll-viewport` and the `p-dropdownItem`? 

- Or should `p-dropdown` pass it's `itemSize` input value into the `p-dropdownItem` at the same time it is passing it into the `cdk-virtual-scroll-viewport`?

https://github.com/primefaces/primeng/blob/260114b4cafd5a32ce9b3e0675ed6cfbc3713cf9/src/app/components/dropdown/dropdown.ts#L113

**Comment by Omzig** [comment]
I cannot get itemSize to work on any version of PrimeNg: 
```<p-dropdown [options]="cities" [virtualScroll]="true" itemSize="30"></p-dropdown>```
The default is always 6 items.

**Comment by Omzig** [comment]
Here is the reproduction of the issue:
https://stackblitz.com/edit/angular-ivy-prime-dropdown-demo?file=src%2Fapp%2Fapp.component.html

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
