### ISSUE TITLE
when using row editing in table edit ,cell editing must not work

### ISSUE THREAD

**Issue by rahmatimahdi** [primefaces/primeng#9647]
when using row editing in table edit , I want to cell editing not work

https://primefaces.org/primeng/showcase/#/table/edit

**Comment by amitskale** [comment]
If you set the editMode="row" for the p-table then cell editing does not work. You have to click on row edit button to make the row editable. Does it help you or I understood your question incorrectly?

**Comment by jalilzade** [comment]
Hi, can you please update related [stackbilitz ](https://stackblitz.com/edit/primeng-tableedit-demo) example also.
