### ISSUE TITLE
Table export - Get the entire record in Export function

### ISSUE THREAD

**Issue by TKul6** [primefaces/primeng#9648]
**I'm submitting a ...** 
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Today, when using the `exportFunction` feature  the method accept only 2 args:
- The cellData.
- The field (colmn) that is bound to this field.

Sometimes we need the entire record in order to provide the data to export. It will be really helpful to ship it as well when invoking the `exportFunction`.

**Expected behavior**
When invoking the `exportFunction` the function will also provide the entire record (or at least the record's id if available).

**What is the motivation / use case for changing the behavior?**
A good example can be a products table  where each product has a price and a currency.
When exporting the table i'd like to export the price and the currency.
In order to do so, I need the currency code which exists on another field in the record.

Thank you

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
