### ISSUE TITLE
this.calendarElement.datepicker is not a function

### ISSUE THREAD

**Issue by rogueRabbit** [primefaces/primeng#965]
![image](https://cloud.githubusercontent.com/assets/14859823/18862532/53340f38-84bf-11e6-9bb8-d816fb34365c.png)
I use calendar plug-ins, such problems encountered, Would like to ask how to introduce the UI datepicker jQuery plug-in, Please help me

**Comment by cagataycivici** [comment]
You need to include jquery, jquery ui until we reimplement it as a native component. Easiest way is;

```
<script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
        <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ui-timepicker-addon/1.6.1/jquery-ui-timepicker-addon.min.js"></script>
```

**Comment by supermafete** [comment]
Hi there,

Using Angular 2.0.1 with jquery and jquery-ui modules and typings loaded from angular-cli.json and tsconfig.json. Still saying:

> Error in ./UsersComponent class UsersComponent - inline template:82:16 caused by: this.calendarElement.datepicker is not a function

If I remove jQuery modules then the error is:

> Error in ./UsersComponent class UsersComponent - inline template:82:16 caused by: jQuery is not defined ;

So I assume jQuery is loaded correctly. Any preview on when the native component will be ready? Any workaround in the meantime?

Thanks.

**Comment by supermafete** [comment]
Oh dear, it was released today and worked perfectly. Thanks! ;)

**Comment by arat3091** [comment]
I am facing same for schedule component . How to fix this error ?

**Comment by heidermatos** [comment]
@supermafete what version are you using? Angular and primeng?

**Comment by supermafete** [comment]
@heidermatos at the moment I experienced the issue were using angular beta 28 and primeng 1.0.0-beta.17, but it was six months ago.
