### ISSUE TITLE
Wrong display scrollbar space in header of p-table, when scrollable is used.

### ISSUE THREAD

**Issue by thornidlo** [primefaces/primeng#9653]
[x] bug report

https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-p41jus?file=src%2Fapp%2Fapp.component.ts

Angular version: 11.0.0
PrimeNG version: 11.0.0

When property scrollable=true is set to p-table and we have only few rows, there is "scrollbar space" in header, but for data scrollbar is not shown. I need that for filter data with virtualscroll enabled - it can return 3 or 3000 rows.

![image](https://user-images.githubusercontent.com/9034700/102187735-ad739280-3eb4-11eb-8afb-fee4943cc945.png)

**Comment by adama357** [comment]
This bug also manifests _without_ virtual scroll: If scrollable is set but scrollHeight isn't, e.g., you want the table to have horizontal scroll but not vertical.

**Comment by CD-UNCC** [comment]
We are on 11.2.1 and `p-datatable-scrollable-body` has `overflow-y: scroll`  as an inline style so the scroll bar is always there. We would like to override to `auto` so the scrollbar only appears when the table is scrollable but if we try to we encounter this issue. I dont see how you have the scrollbar missing though.

**Comment by adama357** [comment]
Fyi this bug also affects TreeTable

**Comment by MrCosmo** [comment]
Any update on this issue? I'm currently having problems with this one. 
As a temp workaround i'm forcing a scrollbar on y-axis. This is rather ugly but only solution for now I guess.

**Comment by briancodes** [comment]
Using `11.3.1`, with virtual scroll enabled. I'm currently using the following workaround: 

```
cdk-virtual-scroll-viewport {
  overflow-y: scroll !important;
}
```

**Comment by briancodes** [comment]
> Any update on this issue? I'm currently having problems with this one.
> As a temp workaround i'm forcing a scrollbar on y-axis. This is rather ugly but only solution for now I guess.

This workaround unfortunately doesn't really work on a `Mac` when the user has scrollbar preferences set to the default `General > Show scroll bars: > Automatic/When Scrolling`

**Comment by mertsincan** [comment]
It has already been fixed with table implementation. Please use the latest PrimeNg version.

Best Regards,

**Comment by wondie** [comment]
This issue is still there in primeNg 14.
