### ISSUE TITLE
PColumnFilter's apply and clear button arent hiding if [showApplyButton] or [showClearButton] are set to false

### ISSUE THREAD

**Issue by dennis-mysign** [primefaces/primeng#9654]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-tablefilter-demo-fupw4q?file=src%2Fapp%2Fapp.component.html

**Current behavior**
Setting ShowApplyButton or ShowClearButton to false, doesn't hide the apply- or the clear-button on the pColumnFilter

**Expected behavior**
Setting ShowApplyButton or ShowClearButton to false, should hide the apply- or the clear-button on the pColumnFilter

**What is the motivation / use case for changing the behavior?**
To be able to create custom buttons, which are using the filterCallback, for applying or clearing filters on the pColumnFilter.

* **Angular version:** 11.X

* **PrimeNG version:** 11.X

**Comment by chapoub** [comment]
I had the same issue today with
angular v11.1.1
primeng v11.2.0

Do you plan to solve this issue anytime soon?

Thanks,

**Comment by jroovers** [comment]
I also have this problem

**Comment by balagex** [comment]
I also have this problem. (angular 11.1.1 ; primeng 11.2.0)

**Comment by Sayali77** [comment]
I also have this problem angular v11.1.0 primeng v11.2.0

**Comment by AyhamJaradat** [comment]
I also have this problem

**Comment by jesuspa17** [comment]
I also have this problem

**Comment by agarofalotecnetsys** [comment]
I have same problem
