### ISSUE TITLE
[Feature request] FilterService: need to look at entire row at once in custom filter callback

### ISSUE THREAD

**Issue by blunket** [primefaces/primeng#9656]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request 
[ ] support request

This feature request would either add a new filtering function that loops over each **row** (instead of each cell), or perhaps simply passes another [optional] parameter to the callback function on a custom filter with the entire current row's data rather than just the current cell.

**What is the motivation / use case for changing the behavior?**
My app has a search field. I am trying to register a new filter method with the new FilterService that functions in a way _similar to_ the default `contains` filter, but it should run on _each individual word typed_ (split on whitespace). Due to the current implementation I am not currently able to do this correctly, as it needs to run across all columns as well.

For an example, if I have a table with this data:
```
*-----------------------------------*
| # | title  | status   | assignee  |
*------------+----------+-----------*
| 1 | Foo    | active   | Andrew    |
| 2 | Bar    | active   | Andrew    |
| 3 | Baz    | active   | John      |
| 4 | Baz 2  | canceled | John      |
*-----------------------------------*
```

Then typing `"andrew foo"` would return the row 1 **only**. Typing `"Baz John"` would return the 3rd and 4th row. Typing `"Andrew active"` would return rows 1 and 2, etc.

Currently, the callback for a custom filter has no way of looking at the other columns in the current row (it is only passed the filter value and the current's cell value), so I am unable to do this.

**Please tell us about your environment:**

* **Angular version:** 10.0.4

* **PrimeNG version:** 11.0.0

* **Language:** TypeScript 3.9.7

* **Node (for AoT issues):** `node --version` = 15.0.1

**Comment by blunket** [comment]
I'd love to offer my help and contribute this feature after some discussion here if an implementation is agreed upon! (I've been able to implement it within my app by referencing PrimeNG's source code)

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
