### ISSUE TITLE
[Feature Request] Add current page in LazyLoadEvent

### ISSUE THREAD

**Issue by tiagotrigger** [primefaces/primeng#9657]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Hello,

It would be nice to have more fields in the interface LazyLoadEvent for the lazy pagination of the tables.

For instance, one of the fields that would help is the current page number.

Today there is the "first" field, but for my environment (Java Spring Page class in the backend server) it uses the current page number. So I have to make extra calculations and add extra bindings between .html and .ts files.

Thanks.

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
