### ISSUE TITLE
Unable to filter input method characters using the keyFilter directive.

### ISSUE THREAD

**Issue by SuperRichZhao** [primefaces/primeng#9658]
Currently using system input method, press Shift or Enter when entering non-English text, the selected text can still be entered into the input box.
#### Expected results:
When typing another language, it should not be added to the input box.
#### Actual results:
Keyfilter does not appear to be in effect and can still be entered normally.

Unable to provide online instance due to input problem. Sorry.
If possible, I can provide a recording link.

**Comment by SuperRichZhao** [comment]
[review links]: http://hepl-file.aiyuninfo.com/group1/M00/01/0B/fwAAAV_f-GWASV06AAZx7R1WaaM516.mov

**Comment by SuperRichZhao** [comment]
review link: http://hepl-file.aiyuninfo.com/group1/M00/01/0B/fwAAAV_f-GWASV06AAZx7R1WaaM516.mov

**Comment by SuperRichZhao** [comment]
@yigitfindikli

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
