### ISSUE TITLE
optionValue backward compatibility issue

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#9660]
<img width="1946" alt="Screen Shot 2020-12-16 at 11 54 09" src="https://user-images.githubusercontent.com/686247/102326548-9658a180-3f95-11eb-96ff-135da6faa78e.png">

**Comment by cagataycivici** [comment]
Reopen for review

**Comment by Spaction** [comment]
Not fixed as commented on code review.
This prevent any type of binding data with ngModel with the most basic set-up of dropdown. This can be determined through setting NGModel to the non-default input. Additionally, if you change the dropdown value, the ngModel is always set to undefined
https://stackblitz.com/edit/primeng-dropdown-demo-pte6kg?file=src%2Fapp%2Fapp.component.html
