### ISSUE TITLE
How to Set max-height and scroll for tieredmenu submenu items

### ISSUE THREAD

**Issue by shankar5147** [primefaces/primeng#9661]
![tired-menu1](https://user-images.githubusercontent.com/43570538/102336034-a6cd4400-3fb6-11eb-9e69-38ce01f7000f.png)
![tired-menu2](https://user-images.githubusercontent.com/43570538/102336040-a7fe7100-3fb6-11eb-839c-660f7c9eac7e.png)
I am trying to add scrollbar for subitems. I am adding styles are max-height and overflow: auto but inner sub items also hide inside of the scrollbar 
and how to automatically align subitems left to right

**Comment by cagataycivici** [comment]
Please use forum or discord for questions.
