### ISSUE TITLE
p-table stateStorage date filter showing 0 rows upon refresh

### ISSUE THREAD

**Issue by ODB-Gideon** [primefaces/primeng#9666]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
I am using data table with caching to localstorage enabled. When I apply a filter to a Date column, it works but when I refresh no data appears in the table. All other filters work on the table and I am passing in an array with valid dates to the table

**Expected behavior**
I expect that when I refresh the page, the table Date filter will be read from storage and applied correctly.

**Please tell us about your environment:**
WINDOWS, VSCode, NPM

* **Angular version:** ~11.0.1

* **PrimeNG version:** ^11.0.0

**Comment by MMarus** [comment]
I have the same issue. It seems that the date filter is not recreated properly after loading from the local storage.
I can see following message in the console:

ERROR TypeError: filter.toDateString is not a function
    dateIs primeng-api.js:345
    executeLocalFilter primeng-table.js:1617
    _filter primeng-table.js:1554
    ngOnChanges primeng-table.js:875
    Angular 28
    RxJS 5
    Angular 17
    RxJS 19
    Angular 24
    adopt index.es.js:44
    ZoneAwarePromise Angular
    adopt index.es.js:44
    step index.es.js:48
    fulfilled index.es.js:46
    Angular 11
core.js:5980

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
