### ISSUE TITLE
All menus should be UI blocking

### ISSUE THREAD

**Issue by jonnomk** [primefaces/primeng#9668]
All menus should be UI blocking when they're active, especially the context menu.

If you activate a context menu, you shouldn't have to try and find a part of the UI that hasn't got a clickable item in order to 'click off' of the menu to deactivate it.  It's the same for standard menus and anything that has an overlay.

Consider the default browser context menu - this blocks the UI until the menu is deactivated as do Material UI menus.

Please add UI blocking, transparent masks to all menu's and items that exist in overlays.

Secondary to this, the logic that determines the position of menus needs to be fixed.  Again, in using the context menu, I used the below:

`<p-contextMenu [target]="row" [model]="menuItems"></p-contextMenu>`

...where 'row' was a template reference variable.  I shouldn't have to use appendTo="body" to make the menu align where I right click in the vewport, it should just work.  The 'row' is located in a div that has a position set.

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
