### ISSUE TITLE
You shouldn't be able to open multiple context menus

### ISSUE THREAD

**Issue by jonnomk** [primefaces/primeng#9669]
I submitted a previous issue about [menu's not being UI blocking](https://github.com/primefaces/primeng/issues/9668#issue-769781352) - if they were, then you wouldn't get the below problem, but seeing as I don't know what the solution to the other issue will be, I thought I would raise this as a separate issue.

I have a UI with some rows that contain data using the treeview component.  Each row has it's own menu icon to the far right, but I thought I'd play around with a context menu.

The first problem I encountered was having to use appendTo="body" to get the menu to appear in the right place.  The second issue is that the menus don't block the UI, so I'm able to create this mess:

![image](https://user-images.githubusercontent.com/56191325/102473455-6077f380-404f-11eb-8ce3-2eeecd71c42f.png)

The third issue is that (because the menus are not UI blocking!) I am able to scroll, but the menus are not anchored where they originally opened, so I get an undesirable effect where the application scrolls underneath the menus which stay static on the screen.

Making the menus open in the body by default, correcting the position of the menu without having to use appendTo="body" and blocking the UI will solve a multitude of UI issues with your menu/overlay components.

**Comment by ThomasPrikrylBE** [comment]
What is the status of this issue?

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
