### ISSUE TITLE
Column filter Without cleaning filters

### ISSUE THREAD

**Issue by Th14go** [primefaces/primeng#9670]
**Current behavior**

When you click the clear filters button, you are clearing only the table

**Expected behavior**

When you click on the clear filters button, you must clear the search made in column filter and reset the table as well.

Example StackBlitz
https://stackblitz.com/edit/primeng-tablefilter-clearfilters?file=src/app/app.component.html

Angular 10.2.0
PrimeNG 11.0.0

**Comment by mmlitvin** [comment]
This is not enhancement. This is a defect. What would be circumvention until a fix is provided?

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
