### ISSUE TITLE
<p-dialog> regression bug: [focusOnShow]="true" no longer sets focus when dialog is opened

### ISSUE THREAD

**Issue by Da13Harris** [primefaces/primeng#9674]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**StackBlitz Case (Bug Reports)**
https://github-mxvzyf.stackblitz.io

**Current behavior**
When focusOnShow is set to true, keyboard focus does not get set to the first focusable element when the dialog is opened.

**Expected behavior**
If focusOnShow is set to true, keyboard focus should be set to the first focusable element when the dialog is opened.

This appears to be a regression bug. It used to work in PrimeNG version 9.1, but no longer works in version 11.

**Minimal reproduction of the problem with instructions**
1. Navigate to this StackBlitz: https://github-mxvzyf.stackblitz.io
2. Click the first button to open the dialog. (Focus is still on the button and shouldn't be)
3. Press tab on the keyboard. (Focus moves to the next button behind the dialog, but should stay trapped in the dialog.

**What is the motivation / use case for changing the behavior?**
Keyboard focus on the dialog ensures accessible dialogs for keyboard users.

**Please tell us about your environment:**
Development: Windows 10, VS Code; Server: IIS/Windows

* **Angular version:** 11.0.4

* **PrimeNG version:** 11.0.0

* **Browser:** Tested in Chrome 87.0.4280.88 & Firefox 82.0.3, likely an issue in all browsers

**Comment by cagataycivici** [comment]
You need to add an element with [autofocus] to set the onFocusTarget to use this. Idea is to provide flexibility to let you choose what to focus. Seems to be missing a doc which we will add.

**Comment by Da13Harris** [comment]
Awesome! I've used the `autofocus` attribute and everything is working perfectly. And it's a nice declarative and flexible solution. Thanks for following up with the documentation update.
