### ISSUE TITLE
Allow PanelMenu to be expanded without being activated

### ISSUE THREAD

**Issue by fucjoh** [primefaces/primeng#9676]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already 
[ ] support request => Please do not submit support request here
```

**Current behavior**
Clicking on an entry in then PanelMenu activates the corresponding MenuItem. There does not seem to be a way to just expand a parent MenuItem without activating (navigate/execute command) it.

**Expected behavior**
When clicking on the chevron/arrow the MenuItem should be expanded without activating it.

**What is the motivation / use case for changing the behavior?**
Currently it is not reasonably possible in the PanelMenu to have an action on a MenuItem, which has children.

**Please tell us about your environment:**

* **Angular version:** 11.X

* **PrimeNG version:** 11.X

* **Browser:** all

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
