### ISSUE TITLE
Menubar menuitems must have menu/menubar as parent 

### ISSUE THREAD

**Issue by mbquinonez** [primefaces/primeng#9680]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Menubar component introduces wcag violation: https://dequeuniversity.com/rules/axe/4.1/aria-required-parent

**Expected behavior**
Component should should pass wcag2 tests

**Minimal reproduction of the problem with instructions**
Use Menubar component and run accessibility tool such as axe

**What is the motivation / use case for changing the behavior?**
Pass WCAG tests

**Please tell us about your environment:**
Angular version: 11

PrimeNG version: 11

Browser: Chrome

* **Angular version:**
 *11

* **PrimeNG version:** 
 *11

* **Browser:** 
* all

**Comment by komby** [comment]
@yigitfindikli Since a fix and test are already available for this change is it possible we will see it in 11.3?  We need some of these a11y changes in our app.
