### ISSUE TITLE
[New Component Request]  A new concept component

### ISSUE THREAD

**Issue by RobersonLuo** [primefaces/primeng#9683]
Yestoday I found a concept "Fancy Form" from the FancyGrid:
https://fancygrid.com/docs/form-concepts/understanding-fancyform

It's really nice and achive editing using it!
PrimeNG  can implement it in the year 2021 or 2022?
Look forward to...thanks a lot!
 
![image](https://user-images.githubusercontent.com/7013492/102873145-b3044600-447b-11eb-8fec-94066fdeef5f.png)

**Comment by yigitfindikli** [comment]
I think you can implement by your self using our form components and card component.
