### ISSUE TITLE
[bug report] - Prime NG Table rowedit does not work when p-table is wrapped inside a form tag

### ISSUE THREAD

**Issue by amitskale** [primefaces/primeng#9687]
Hi,

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/primeng-tableedit-demo?file=src%2Fapp%2Fapp.component.html

**Current behavior:**

Row Edit functionality does not work properly for p-table when wrapped inside a form tag in Angular 10 and Prime NG table latest version 11.x. Rather than making entire row editable it makes one of the row cells editable and look and feel also becomes erratic. This makes it useless to use p-table with reactive forms in Angular

**Expected behavior:**

Row Edit functionality of p-table should work with form tag to make use of it with reactive forms in Angular 10

**Minimal reproduction of the problem with instructions:**

Just wrap up the app.component.html within a form tag in the below Stackblitz sample and you will be able to reproduce the issue

https://stackblitz.com/edit/primeng-tableedit-demo?file=src%2Fapp%2Fapp.component.html

**What is the motivation / use case for changing the behavior?**

To make p-table work with reactive forms in Angular 10+

**- Angular version: 10.X
- PrimeNG version: 11.x
- Browser: [all]**

**Detailed Description of the issue**

I was exploring the usage of Prime Ng table for implementing a grid in our application being developed in Angular 10. I am specifically trying row edit functionality because that's what we want it mainly for. The sample example provided on github/stackblitz works as is however when I wrap the p-table ode inside a form tag then the row edit does not work properly. Rather than making entire row editable it makes one of the row cells editable and look and feel also becomes erratic. This makes it useless to use p-table with reactive forms in Angular

Here's the stackblitz link of the sample app by Prime Ng. Just wrap up the app.component.html within a form tag and you will be able to reproduce the issue

https://stackblitz.com/edit/primeng-tableedit-demo?file=src%2Fapp%2Fapp.component.html

I checked other open issues here on Github and I see that a similar issue is there for cell editing as well however there is a workaround to it. Here for rowedit there does not seem to be any workaround and only way I could see it working while playing around on Stackblitz was not to use the form tag around the p-table

Any workaround that you can suggest or any plan to fix this behavior to make p-table work with form tag?

**Comment by vishwackh** [comment]
I simply removed the form-tag, instead I attached the formGroup to tr-tag will solve the problem

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by qwadrox** [comment]
I'm still experiencing this issue on Primeng: 15.2.0
