### ISSUE TITLE
enable tabView to be full screen

### ISSUE THREAD

**Issue by pmo1948** [primefaces/primeng#9690]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Tab View panel only takes up as much space as its content

**Desired behavior**
Enable tabView panel to take up full screen

**What is the motivation / use case for changing the behavior?**
The desire to use tabView for tabs on a page fullscreen, with a look and feel that does not keep shrinking and growing if content is slightly different in sizes

* **Angular version:** 11.0.2

* **PrimeNG version:** 11.0.0

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
