### ISSUE TITLE
Cannot find module 'primeng/skeleton'

### ISSUE THREAD

**Issue by nnasirzada** [primefaces/primeng#9691]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
When I import `SkeletonModule` as `import { SkeletonModule } from 'primeng/skeleton';`, I get the following error: `Cannot find module 'primeng/skeleton' or its corresponding type declarations.ts(2307)`

I checked `node_modules/primeng/skeleton` folder but the folder doesn't exist either. The other folders are available under `node_modules/primeng`. I tried to reinstall `primeng` by deleting npm cache, but still the same error pops.

**Expected behavior**
`import { SkeletonModule } from 'primeng/skeleton';` should work without an error. The folder `node_modules/primeng/skeleton` should be exist.

**Please tell us about your environment:**
Windows 10x64, Version	10.0.18363, Build 18363

* **Angular version:** 11.0.4

* **PrimeNG version:** 11.0.0

 
* **Language:** TypeScript 4.1.2

* **Node (for AoT issues):** `node --version` =  v12.14.0

**Comment by yigitfindikli** [comment]
You need to install PrimeNG v11.1.0-rc.1
