### ISSUE TITLE
circle shape not working in avatar component in release 11.rc1

### ISSUE THREAD

**Issue by quantica-life** [primefaces/primeng#9693]
I'm submitting a ... (check one with "x")

[ X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
Current behavior
avatar component show a square image when shape="circle" is provided

Desired behavior
show a circular shape image

What is the motivation / use case for changing the behavior?
this behavior is defined in documentation

Angular version: 11.0.5

PrimeNG version: 11.1.0.rc1

**Comment by yigitfindikli** [comment]
I couldn't replicate it. Check https://stackblitz.com/edit/primeng-avatar-demo

**Comment by quantica-life** [comment]
yes, it works great with icons and text, but i have this issue with image content, using the component this way
<p-avatar image="assets/layout/images/avatar.png" styleClass="p-mr-2" size="xlarge" shape="circle"></p-avatar>
i can't reproduce it in stackblitz because i can't add an image there, but this is the result
<img width="381" alt="Schermata 2020-12-28 alle 22 37 10" src="https://user-images.githubusercontent.com/69714887/103244493-8067bb00-495d-11eb-9433-454bf79ce5ad.png">
Thanks for your support and sorry for my unclear first message

**Comment by xubmuajkub** [comment]
Just simply add style overflow: hidden; and it should work

**Comment by quantica-life** [comment]
thanks @xubmuajkub, it works

**Comment by s4m0r4m4** [comment]
I ran into this as well. @yigitfindikli I think this should still be open - it does not work with images but the docs seem to indicate it should. I think the course of correction should be: 1) update the stackblitz example from the docs to include an image example and 2) fix it so p-overflow-hidden is automatically applied when shape="circle" (I'm open to other solutions if there is an "official" approach from the PrimeNG team).

**Comment by phutchins** [comment]
Agreed, this was aggravating and shouldn't' have to be overridden to make it behave like the docs specify.
