### ISSUE TITLE
[Feature request] Need support zoom in/out mode  in Galleria

### ISSUE THREAD

**Issue by RobersonLuo** [primefaces/primeng#9694]
**What is the motivation **
My app has uploaded some images(png) for each bill, but it's shown unfriendly to the user for some images that are too big or too small.

**Comment by bgl3317** [comment]
Would love to have this feature.

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
