### ISSUE TITLE
Tooltip on Dropdown made Conditional

### ISSUE THREAD

**Issue by pmo1948** [primefaces/primeng#9696]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Tooltip automatically shows on dropdown for any given value

**Expected behavior**
enable condition to set whether tooltip is visible or not

**What is the motivation / use case for changing the behavior?**
Sometimes we want to show the tooltip only if the selected value is really long, or if it has a special property

* **Angular version:** 5.X
11.0.2

* **PrimeNG version:** 5.X
11.0.0

**Comment by maralik** [comment]
You can implement it by yourself:
```
<p-dropdown
                ...
                [pTooltip]="showTooltip ? title : undefined"
                [tooltipPosition]="showTooltip ? 'bottom' : undefined"
            >
```

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
