### ISSUE TITLE
Table filter - Filter is not updated when changing the filters input

### ISSUE THREAD

**Issue by TKul6** [primefaces/primeng#9697]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
I'm using the table, and provide the filters myself (using the `filters` input property).
I found out the only way to make it work is if I call to the `_filter()` method myself. According to what I read in github, the column-filter also call the `_filter()` to apply the new filter.

**Expected behavior**
It would be very helpful if one of the following methods will be implemented:
- on `ngOnChanges` check if the `filters` input property is changed and if so call to the `_filter()`.
- Change the `filters` input property to have get / set, and in the setter call to the `_filter()` method.

I have no problem changing the code and create a pull request, But I'd like to get your opinion first.

**Minimal reproduction of the problem with instructions**
1. Create table.
2. Change the `filters` property
3. See that nothing is happens.

**What is the motivation / use case for changing the behavior?**
I want to avoid calling the `_filter()` myself, and I think the table control should do that.

**Please tell us about your environment:**
Win 10, NPM 

* **Angular version:** 5.X
Angular 11

* **PrimeNG version:** 5.X
PrimeNG 11

* **Browser:** [all]

 
* **Language:** [all ]

* **Node (for AoT issues):** `node --version` =

**Comment by TKul6** [comment]
Hi @yigitfindikli  is it possible to fix it and send a PR (not sure what your policy about contribution.

**Comment by emirselvi** [comment]
@TKul6 same issue occurs for <p-treeTable> component, as you said adding tt._filter() gives me what I wanted.

`<input type="text" pInputText size="50" placeholder="Global Filter" (input)="tt.filterGlobal($event.target.value, 'contains'); ` **tt._filter()** `"style="width:auto">`

Thanks for you response.
Happy coding. 😄

**Comment by TKul6** [comment]
HI @yigitfindikli , I fixed the issue in #9720 can you please approve it?

**Comment by Cito** [comment]
@yigitfindikli Please merge that pull requests #9720 from @TKul6. It comes with a test and helps a lot!

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
