### ISSUE TITLE
nodeDrop event firing with different properties in tree.ts

### ISSUE THREAD

**Issue by Tr3yb0** [primefaces/primeng#9699]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
onNodeDrop in tree.ts, there is an index parameter which is sometimes named dropIndex (lines 209 and 221) , and sometimes named index (lines 326 and 338). 
This results in varying behavior when a nodeDrop event is fired.

**Expected behavior**
Either event.index or event.dropIndex should always be emitted in the same event, but not have different fields for the same event.

**Minimal reproduction of the problem with instructions**
create a tree with draggable and droppable nodes. use the onNodeDrop attribute to validate the event that is fired. when inspecting the event, sometimes the properties will contain event.index, sometimes event.dropIndex, unclear what triggers which.

**What is the motivation / use case for changing the behavior?**
consistent behavior

**Please tell us about your environment:**

windows, vscode, npm, angular dev server

* **Angular version:** 5.X
angular 7.3

* **PrimeNG version:** 5.X
8.0

* **Browser:**
chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a stackblitz example.

**Comment by Tr3yb0** [comment]
i literally referenced the lines in the source code where the issue is originating. 
The index for the nodeDrop event is sometimes called index and sometimes called dropIndex. 
Cant be any more clear than that.
