### ISSUE TITLE
Row Expansion for DataTable

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#97]

**Comment by TekSiDoT** [comment]
Will this feature be comparable to [this table](http://www.primefaces.org/showcase-ext/sections/exporter/expandableTable.jsf)?

**Comment by cagataycivici** [comment]
It will be same as;

http://www.primefaces.org/primeui/#datatableExpansion

or

http://www.primefaces.org/showcase/ui/data/datatable/expansion.xhtml

Expanded area will be based on a user defined template that gets the rowdata as a variable.

**Comment by TekSiDoT** [comment]
Fantastic, looking forward to it.

**Comment by cagataycivici** [comment]
Ready for 1.0.0-beta.3

<img width="1082" alt="screen shot 2016-04-18 at 17 24 10" src="https://cloud.githubusercontent.com/assets/686247/14607623/f2fe24f4-058a-11e6-9b8c-1899121ff934.png">
