### ISSUE TITLE
Support paginate table pragmatically 

### ISSUE THREAD

**Issue by TKul6** [primefaces/primeng#9703]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
There is no way to change the current page from the component hosting the table control.
**Expected behavior**

Either to have a `@Input() currentPage` that will do the pagination upon change, or at least let the table have `setPage(page: number)` option.

**Minimal reproduction of the problem with instructions**
Just add a table.
**What is the motivation / use case for changing the behavior?**
When I add new row to the collection it is added to the last of the table. After adding the row I wish to disable the sort / filters if exists and navigate to the last page.

* **Angular version:** 11

* **PrimeNG version:** 11

* **Browser:** [all]

 
* **Language:** [all ]

* **Node (for AoT issues):** `node --version` =   14

**Comment by yigitfindikli** [comment]
We'll implement new drag-drop features in 11.2.0. Thanks for your report.

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
