### ISSUE TITLE
Custom template/style for reorderable column when dragging

### ISSUE THREAD

**Issue by Exlord** [primefaces/primeng#9704]
**I'm submitting a ...**  (check one with "x")
```
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
```

**Current behavior**
dragable column header is duplicated/copied

**Expected behavior**
dragable column header has a class to apply custom styling or has a custom template

**What is the motivation / use case for changing the behavior?**
To look prettier visually , and my UX/UI team wants it in our product

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
