### ISSUE TITLE
p-table: toggled columnes are not (/should be?) saved by state

### ISSUE THREAD

**Issue by ProfEibe** [primefaces/primeng#9705]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Toggled Columns are not saved by the state feature. So if you come back and a global-filter is set, which was used with the column, these rows are not found anymore.

**Current behavior**
Toggled Columns are reset when coming back to the side.

**Expected behavior**
Toggled Columns are saved by the state variables and visible on return

* **PrimeNG version:** 11.0.0

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
