### ISSUE TITLE
Error triggered browser default event after right-clicking on expand/collapse icon on p-tree

### ISSUE THREAD

**Issue by Austin-Ming** [primefaces/primeng#9706]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Current behavior
Tree right-click expand/collapse icon error triggers default event.

Expected behavior
Error triggered browser default event after right-clicking on expand/collapse icon on p-tree.

Normal right-click node:
![chrome_rGrwK4MGas](https://user-images.githubusercontent.com/49113564/103519122-edc0a200-4eaf-11eb-83b7-02aa80045c4f.png)

Right-click to expand/collapse icon:
![ApplicationFrameHost_uwokdE3E5Y](https://user-images.githubusercontent.com/49113564/103519119-ec8f7500-4eaf-11eb-8e29-3d161f7661e8.png)

PrimeNG version: 11.0.0

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
