### ISSUE TITLE
p-table pagination does not redirect to page 1 after changing contents of p table

### ISSUE THREAD

**Issue by bougpan88** [primefaces/primeng#9707]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-p-table-paginate-to-first-page-when-no-records-x2ydhh

**Current behavior**

When the p-table has pagination enabled results can be found in multiple pages. Suppose I click on 2nd page of results. Then the contents of p-table refresh and let's suppose that they are less than before. P table results remain on page 2 of pagination even if page 2 does not exist any more as there are not so many results. 

**Expected behavior**

It would be expected when the contents of p-table change that we are redirected in page 1 of pagination. This at least should happen when the page where the user currently is, does not exist after the updated results

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/primeng-p-table-paginate-to-first-page-when-no-records-x2ydhh
1) Go to page number 2 of results
2) Click update results button
3) Click previous page button on pagination

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.X

* **PrimeNG version:** 5.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by yigitfindikli** [comment]
Seems to be fixed. I tried your stackblitz example(Actually your stackblitz example not running you need to change omega to saga-blue or any existing theme).
