### ISSUE TITLE
Row click event should not be triggered if target is clickable

### ISSUE THREAD

**Issue by ribizli** [primefaces/primeng#971]

**Comment by cagataycivici** [comment]
I'm not sure, technically row is clicked due to propagation right? What if another user wants it to be fired?

**Comment by ribizli** [comment]
I have the following usecase: multi select with checkboxes and default action on row click, The action opens the record in a new route. So it is not possible to do selection on the table because we navigate away.

**Comment by cagataycivici** [comment]
I think we do not select row (onRowSelect) in such a case when selection mode is on, it makes sense to do it for onRowClick callback as well.

**Comment by ribizli** [comment]
Yes, as stated in the title... If selectionMode is defined on the table (not on row) my usecase makes no sense.

**Comment by cagataycivici** [comment]
I've applied the similar solution we had in PrimeFaces.
