### ISSUE TITLE
Feature Request: Dynamic Dialog add a custom transform option

### ISSUE THREAD

**Issue by pascalporedda** [primefaces/primeng#9712]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Hey guys,

I'm filing this issue as I'm currently trying to modify the transform of the DynamicDialog component, but with the current hardcoded implementation it is not possible to change the transform as it is currently hardcoded:

https://github.com/primefaces/primeng/blob/ad79c7c1ccd39117cbd8b42df47ed2a283e53d66/src/app/components/dynamicdialog/dynamicdialog.ts#L81

Adding another option to not only change the transition but the transform as well would be pretty beneficial.

Dunno what you guys think about that, but I guess that's not a big change at all.

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by NateRadebaugh** [comment]
Not completed, this code is still not customizable in the latest:
> https://raw.githubusercontent.com/primefaces/primeng/refs/heads/master/src/app/components/dialog/dialog.ts
