### ISSUE TITLE
Use `el.ownerDocument` where possible, instead of `document`

### ISSUE THREAD

**Issue by brian428** [primefaces/primeng#9714]
This issue extends #9181, for cases where PrimeNg currently uses the `document` object (e.g. `document.addEventListener()`). In cases where separate browser windows are used in conjunction with the Angular CDK `CdkPortal` and `DomPortalOutlet`, using the main window's `document` object results in broken PrimeNg behavior because the document object being used is actually incorrect.

I will open a PR with changes to attempt to use `this.el.nativeElement.ownerDocument` where possible.

Going forward, I would also ask that this approach be used in any new components that need to reference the `document` object, to avoid the "separate document" problem in the future. Thanks.

**Comment by Brian-V** [comment]
+1

**Comment by mccoy1** [comment]
+1

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
