### ISSUE TITLE
bug - p-calendar locale "es" not working

### ISSUE THREAD

**Issue by sourdoth** [primefaces/primeng#9728]
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Spanish section -> https://stackblitz.com/edit/primeng-calendar-demo

**Current behavior**
locale="es" or [locale]="es" not work in p-calendar

**Expected behavior**
set spanish label

**Minimal reproduction of the problem with instructions**
set variable "es" with primeNg structure

* **Angular version:** 11

* **PrimeNG version:** 11

**Comment by yigitfindikli** [comment]
You can use our new [I18N API](https://primefaces.org/primeng/showcase/#/i18n).

**Comment by Valera1980** [comment]
> You can use our new [I18N API](https://primefaces.org/primeng/showcase/#/i18n).

I have that bug as well.

**Comment by Valera1980** [comment]
I have that bug as well.
  "@angular/animations": "~11.0.5",
    "@angular/cdk": "^10.2.2",
    "@angular/common": "~11.0.5",
    "@angular/compiler": "~11.0.5",
    "@angular/core": "~11.0.5",
    "@angular/forms": "~11.0.5",
    "@angular/platform-browser": "~11.0.5",
    "@angular/platform-browser-dynamic": "~11.0.5",
    "@angular/platform-server": "~11.0.5",
    "@angular/router": "~11.0.5",
    "primeng": "^11.0.0",
    "@angular/service-worker": "11.0.5",

**Comment by FlorianLudwig** [comment]
@yigitfindikli I think this issue request is not about translating strings but setting `locale` on the datetime - to change `dateFormat` etc.

Maybe the issue is not the code but just missing documentation on the `locale` property.

**Comment by jeanRandria** [comment]
why closed?I have the same problem.I use i18n but it's no working also on locale fr

**Comment by Darkmagister** [comment]
Same here, i'm trying to use the locale option, but it doesn't work !!!!

**Comment by legendbr94** [comment]
The same here in ANGULAR V13

**Comment by CristinaVidal** [comment]
Same in angular 15 why??
