### ISSUE TITLE
Datatable w/ scrollable and scrollHeight=100% miscomputes scrollHeight

### ISSUE THREAD

**Issue by jayeffaar** [primefaces/primeng#973]
When using a Datatable with scrollable="true" and scrollHeight="100%", the scrollable area ends up being too long by what appears to be the height of the table header, and extends below the table's container element.

Looking at the datable.ts code, it looks to me like the computed scrollBody maxHeight fails to take into account the fixed table header.

```
        <p-dataTable
                [value]="studyTags"
                scrollable="true"
                scrollHeight="100%"
```

From PrimeNG's datatable.ts:

```
        if(this.scrollHeight) {
            if(this.percentageScrollHeight)
                this.scrollBody.style.maxHeight = this.domHandler.getOuterHeight(this.el.nativeElement.parentElement) * (parseInt(this.scrollHeight) / 100) + 'px';
```

![scrollable](https://cloud.githubusercontent.com/assets/20727055/18882788/a7a0ccfc-84ae-11e6-9eb7-5a4df4a44675.jpg)

**Comment by NNemec** [comment]
Seems like this issue reappeared. The corresponding code has been completely reworked and I cannot find anything resembling the logic that was introduced to fix this issue.

**Comment by ctrl-brk** [comment]
There are still quite a few issues with the scrollable data table even it RC2.
Try to make is scrollable with resizable and reordering columns. Fill it with data, so scroll appears. Fill with less data so there's no scroll. Play with headers size and order and you will see all kinds of strange behavior.

**Comment by jksuf** [comment]
Hi, Indeed I think that this issue is related to a post i made : [https://github.com/primefaces/primeng/issues/1905](url)

**Comment by shalaby** [comment]
this bug still exists.

**Comment by BartoszBaczek** [comment]
is there any workaround for this?

**Comment by cagataycivici** [comment]
Could you please create a new issue and post the number here, we can check it for 4-RC2.
