### ISSUE TITLE
DynamicDialogRef - onClose Observable never completes

### ISSUE THREAD

**Issue by kali-dali** [primefaces/primeng#9732]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
The `onClose` Observable in the `DynamicDialogRef` never completes. This is an issue, because other functionality, such as the `forkJoin` operator of the rxjs library depends on Observables completing properly, not just emitting events.
This issue applies to all dialog components / services which provide Observables to listen for events, e.g. ConfirmDialog, Dialog, ConfirmationService, etc.

Here is an example case:
https://stackblitz.com/edit/dynamic-dialog-ref-onclose-not-completing?file=src/app/app.component.html

**Current behavior**
`onClose` Observable never completes when DynamicDialog closes.

**Expected behavior**
`onClose` Observable completes when DynamicDialog closes.

**What is the motivation / use case for changing the behavior?**
Provide better integration into rxjs library.

**Please tell us about your environment:**
OS: Windows 10
Browser: Google Chrome
Angular version: 11.0.0
PrimeNG version: 11.0.0

**Comment by Emkacf** [comment]
I also observed the same issue. Will someone take care of that?

**Comment by sagar-varude** [comment]
OS: Windows 10
Browser: Google Chrome
Angular version: 11.0.0
PrimeNG version: 11.0.0

**Comment by sagar-varude** [comment]
same issue with this technology stack.
OS: Windows 10
Browser: Google Chrome
Angular version: 11.0.0
PrimeNG version: 11.0.0

**Comment by clivebor** [comment]
I also encountered the same issue, found a work around to take(1) and then it completes:

`ref.onClose.pipe(take(1)).subscribe(...)`

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by codepearlex** [comment]
Still broken: https://stackblitz.com/edit/dynamic-dialog-ref-onclose-not-completing-ntvgy9?file=src/app/app.module.ts
Please reopen @mertsincan.

CC @kali-dali
