### ISSUE TITLE
PickList: Remove source and target controls + Option to define custom labels for middle buttons

### ISSUE THREAD

**Issue by vaibhavcodegeek** [primefaces/primeng#974]
Hi,

It would be nice if we can have following following options in PickList component,
1. Feature to hide source and target controls
2. Feature to define custom labels for middle buttons

Please consider the features.

**Comment by vishal3007** [comment]
I also need this feature.

**Comment by xadhoom** [comment]
well, source and target controls can be easily disabled using CSS:

```
.ui-picklist-source-controls {
  display: none !important;
}

.ui-picklist-target-controls {
  display: none !important;
}

.ui-picklist-listwrapper {
  width: 45% !important;
}
```

depending on your angular application, you may need to add ```encapsulation: ViewEncapsulation.None``` to the ```@Component``` entry

**Comment by cagataycivici** [comment]
Duplicate for 395, for button labels, please create another ticket.
