### ISSUE TITLE
Theme: Material Design Compact

### ISSUE THREAD

**Issue by Vladislav-wn** [primefaces/primeng#9740]
Hi
1. Active RadioButton looks "crooked".
https://primefaces.org/primeng/showcase/#/radiobutton

2. Step names looks "crooked". They are like crossed out
https://primefaces.org/primeng/showcase/#/steps/personal

Thank you.

**Comment by yigitfindikli** [comment]
I couldn't replicate it with 11.1.0 final. You can check again.

**Comment by Vladislav-wn** [comment]
Hi,
It's all about this class:
.p-radiobutton .p-radiobutton-box .p-radiobutton-icon {
    width: 10px;
    height: 10px;
    transition-duration: 0.2s;
    background-color: #3F51B5;
}
If you change it, then it works correctly:
.p-radiobutton .p-radiobutton-box .p-radiobutton-icon {
    width: 12px;
    height: 12px;
    transition-duration: 0.2s;
    background-color: #3F51B5;
}
You can see on your page that the geometry of the active RadioButton is "curved"
https://primefaces.org/primeng/showcase/#/radiobutton

"primeng": "^11.1.0",
