### ISSUE TITLE
Galleria: thumbnail items doesn't work properly when responsive options are set

### ISSUE THREAD

**Issue by Jonnyprof** [primefaces/primeng#9744]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://www.primefaces.org/primeng/showcase/#/galleria

**Current behavior**
If you have responsive options, the thumbnail panel doesn't show the selected image when navigating, hides thumbnails and you are not able to navigate to all images.

**Expected behavior**
Thumbnail navigation should show the selected image and be able to navigate to all images.

**Minimal reproduction of the problem with instructions**
- Go to galleria page and set mobile resolution. Refresh page.
- Navigate the photos with thumbnail arrows and will see thumbnails are not shown as expected.

When you have responsive options, it takes global numVisible and not responsiveOptions numVisible because of calculatePosition() doesn't have set itemsContainer at first. 
https://github.com/primefaces/primeng/blob/e4516182d64e2e5f4405511fdbca29ddfe099a71/src/app/components/galleria/galleria.ts#L671-L673
If you resize window, it works as expected because it runs calculatePosition function.

One ugly workaround should be fire manually resize event after component is rendered:
```ts
window.dispatchEvent(new Event('resize'));
```
It forces to go to calculatePosition() and set the correct d_numVisible variable according with responsiveOptions.

* **Angular version:** 5.X
9.0 but is failing in all versions (the code is the same)

* **PrimeNG version:** 5.X
9.0 but is failing in all versions (the code is the same)

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Tested in Firefox 84.0.2 and chrome 87.0.4280.66, but I think that affect all browsers

**Comment by Jonnyprof** [comment]
I've tested it in your gallery showcase and still not working

**Comment by yigitfindikli** [comment]
Hi @Jonnyprof,

Thanks for the feedback fixed now.
