### ISSUE TITLE
I18N in Menu Model

### ISSUE THREAD

**Issue by sourdoth** [primefaces/primeng#9748]
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
please add translate (I18N) option to MenuModel, i tried with label:"{{'var' | translate}}" "escape":false but not work.

**Comment by yigitfindikli** [comment]
Menu items already on your side. You can translate on your side.
