### ISSUE TITLE
p-splitter not working with I think nested ngtemplates

### ISSUE THREAD

**Issue by ProfEibe** [primefaces/primeng#9754]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Splitters panels are multiplying when using nested ngTemplates.
I have I quite complex scrollPanel I wanted to insert into the splitter. It includes a few form-elements, two p-tables and a ngif loading ngtemplate. 
When calling the site there are more than 2 panels, the scrollPanel is in two of them, one is the loading-ngtemplate and one is my right-side-splitter-element.

I tried to make a simple example of the problem. It happens when you move the splitter.
https://stackblitz.com/edit/primeng-splitter-demo-a3bebw?file=src/app/app.component.html

**Current behavior**
Many panels are created and in my place the change of the size is not working.

**Expected behavior**
Only the two panels.

**Comment by yigitfindikli** [comment]
You need to use splitter inside of splitter.  Check [nested splitter](https://primefaces.org/primeng/showcase/#/splitter).

**Comment by ProfEibe** [comment]
No I don't want nested splitter. I just want 1 splitter with a right and a left side.
It just creates more panels and I don't know why!

**Comment by rmathews-mnc** [comment]
I am having this problem as well

**Comment by pedy711** [comment]
I faced the same issue

**Comment by ealib** [comment]
Did you try a single child of `<ng-template>`?

```html
<ng-template>
    <div>
        <!-- your original content here -->
    </div>
</ng-template>
```
