### ISSUE TITLE
template support for emptyMessage in Dataview component

### ISSUE THREAD

**Issue by lallenfrancisl** [primefaces/primeng#9762]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
can only specify a string for the empty message

**Expected behavior**
template support like for header and footer

**What is the motivation / use case for changing the behavior?**
emptyMessage should be more than a string and it is needed to be more than that in many cases. So the component should support this for maximum utility.

* **Angular version:** 9.0

* **PrimeNG version:** 11.0.0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
