### ISSUE TITLE
p-table - Virtualscroll does not work inside p-dialog

### ISSUE THREAD

**Issue by mrdlink** [primefaces/primeng#9767]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/p-table-virtualscroll-bug?file=src/app/app.component.html

**Current behavior**
When I'm using a p-table with virtualscrolling enabled inside a p-dialog, then the content of the table is barely visible.

**Expected behavior**
I'm expecting the virtualscroll of p-table to be supported inside p-dialog too.

**Please tell us about your environment:**
OS: Windows

* **Angular version:** 11.0.4

* **PrimeNG version:** 11.1.0

* **Browser:** Chrome

**Comment by yigitfindikli** [comment]
Duplicate of https://github.com/primefaces/primeng/issues/9766
