### ISSUE TITLE
Calendar - locale doesn't support

### ISSUE THREAD

**Issue by berlot** [primefaces/primeng#9770]
**I'm submitting a bug report

**Current behavior**
The calendar control doesn't support locales. When I visit demo page I don't see translate. In before primeng version it works correctly.
https://stackblitz.com/edit/primeng-calendar-demo?file=package.json

**Expected behavior**
Calendar should display translate when set locale parameter.

* **Angular version:** 11

* **PrimeNG version:** 11

**Comment by yigitfindikli** [comment]
The locale is deprecated. You can use our new [I18N API](https://primefaces.org/primeng/showcase/#/i18n).
