### ISSUE TITLE
Angular 11.0.5 (@angular/cdk": "11.0.4) InputTextArea could not be resolved

### ISSUE THREAD

**Issue by paulsperanza** [primefaces/primeng#9773]
[x] bug report => Search github for a similar issue or PR before submitting

**Current behavior**
Running ng serve gives the following error

**Expected behavior**
Run my app in the browser

**Minimal reproduction of the problem with instructions**
ng serve

**What is the motivation / use case for changing the behavior?**
So the app will run

**Please tell us about your environment:**
Windows 10, VS Code

* **Angular version:** 5.X
    "@angular/animations": "~11.0.5",
    "@angular/cdk": "11.0.4",
    "@angular/common": "~11.0.5",
    "@angular/compiler": "~11.0.5",
    "@angular/core": "~11.0.5",
    "@angular/forms": "~11.0.5",
    "@angular/localize": "~11.0.5",
    "@angular/platform-browser": "~11.0.5",
    "@angular/platform-browser-dynamic": "~11.0.5",
    "@angular/router": "~11.0.5",

* **PrimeNG version:** 5.X
    "primeflex": "^2.0.0",
    "primeicons": "^4.1.0",
    "primeng": "^11.1.0-rc.1",

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Google Chrome Version 87.0.4280.141 (Official Build) (64-bit)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
    "typescript": "~4.0.2"

**Comment by yigitfindikli** [comment]
You need to import InputTextareaModule.
