### ISSUE TITLE
Using flexbox for p-table or a new table component written using table

### ISSUE THREAD

**Issue by lallenfrancisl** [primefaces/primeng#9774]
I am intending this as a discussion rather than a feature request but wouldn't writing table component using flexbox make styling and responsiveness of the table component easier. Is there any specific reason we have not done it yet ? One is legacy browser compatibility but other than that is there any reason.

**Comment by Cito** [comment]
Why not use the good old table tag for tabular data? That's exactly what it's made for, it's not a "legacy browser" tag. If you use tables for grid layouts, that's another thing. But for tabular data, I think it is totally appropriate and the semantically right choice. It is also no problem to make it responsive, as [this demo](https://primefaces.org/primeng/showcase/#/table/responsive) shows.

Flexbox is *not* really good for tables, which are 2-dimensional structures, is is primarily for 1-dimensional structures. While you can of course nest flexboxes, the individual rows would not know of each other. E.g. if one value is wider in one row, this would only widen the table cell for that row, but not the other table cells of the same column in the other rows.

**Comment by Cito** [comment]
Btw, PrimeNG has a [forum](https://forum.primefaces.org/viewforum.php?f=35) and a [chat](https://discord.gg/gzKFYnpmCY) for such discussions.

**Comment by lallenfrancisl** [comment]
> Why not use the good old table tag for tabular data? That's exactly what it's made for, it's not a "legacy browser" tag. If you use tables for grid layouts, that's another thing. But for tabular data, I think it is totally appropriate and the semantically right choice. It is also no problem to make it responsive, as [this demo](https://primefaces.org/primeng/showcase/#/table/responsive) shows.
> 
> Flexbox is _not_ really good for tables, which are 2-dimensional structures, is is primarily for 1-dimensional structures. While you can of course nest flexboxes, the individual rows would not know of each other. E.g. if one value is wider in one row, this would only widen the table cell for that row, but not the other table cells of the same column in the other rows.

Oh those are valid reasons. Also now I saw the dataview component, which is sort of something like what I have asked.



> Btw, PrimeNG has a [forum](https://forum.primefaces.org/viewforum.php?f=35) and a [chat](https://discord.gg/gzKFYnpmCY) for such discussions.

Oh sorry, I didn't notice that. Will keep future discussions there :smile:
