### ISSUE TITLE
wrong class name displayed.

### ISSUE THREAD

**Issue by tsanhan** [primefaces/primeng#9777]
class p-button-text not made, class p-button-label is made instead.

https://github.com/primefaces/primeng/blob/64da7a46d1e4be103744473dc00d6a12b84d3d00/src/app/showcase/components/button/buttondemo.html#L383

**Comment by yigitfindikli** [comment]
closed in https://github.com/primefaces/primeng/commit/33d62429b3b831cb61b39fa0f06947882e8a0273
