### ISSUE TITLE
PrimeNg dropdown with filter does not open in iphone small devices

### ISSUE THREAD

**Issue by yadavsunilmoravia** [primefaces/primeng#9779]
Except for safari in small devices, primeNg dropdown is working but in this scenario it does not open if we enable filter otherwise normally it is working.

<p-dropdown
	[options]="options"
	[(ngModel)]="selectedOption"
	[inputId]="inputElementId"
	[styleClass]="styleClass"
	[ariaFilterLabel]="ariaFilterLabel"
	[placeholder]="placeholder"
	[required]="required"
	[dropdownIcon]="dropDownIcon"
	[filter]="enableSearch"
	[scrollHeight]="scrollHeight"
	[resetFilterOnHide]=true
	[autoDisplayFirst]="autoDisplayFirst"
	(keydown)="handleKeydownEvent($event)"
	(onHide)="handleOnHideEvent($event)"
	(onShow)="handleOnShowEvent($event)"
	(onBlur)="handleOnBlur($event)"
	(mousedown)="overrideMouseClickEvent()">
</p-dropdown>

**Comment by yadavsunilmoravia** [comment]
Please reply this issue. Its critical one

**Comment by sugan2412** [comment]
I am also facing the same issue.Do we have any work around for this.
Angular version - 10 
Primeng version 10.

Please let me know , if we have any fix for the same.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
