### ISSUE TITLE
Icons in buttons only work if statically assigned

### ISSUE THREAD

**Issue by jowenn** [primefaces/primeng#978]
I've tried to create buttons with *ngFor, but they are not created correctly

**Hardcoded icon works:**
`<button *ngFor="let btn of btnss" pButton type="text" icon="fa-user" [ngClass]="{'ui-state-active': checkState(btn)}" ></button>`

_The correct output  is created:_
`<button _ngcontent-abh-2="" icon="fa-user" pbutton="" type="text" ng-reflect-ng-class="[object Object]" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-icon-only" ng-reflect-icon="fa-user"><span class="ui-button-icon-left ui-c fa fa-fw fa-user"></span><span class="ui-button-text ui-c">ui-button</span></button>`

**Setting icon dynamically does not work:**
`<button *ngFor="let btn of bans" pButton type="text" [attr.icon]="btn.icon" [ngClass]="{'ui-state-active': checkState(btn)}" ></button>`

_The_ output is wrongly created:

`<button _ngcontent-kyo-2="" pbutton="" type="text" ng-reflect-ng-class="[object Object]" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" icon="fa-users"><span class="ui-button-text ui-c">ui-button</span></button>`

The problem seems to be, that the binding happens too late, after the ngAfterViewInit invocation and then changes to the icon attribute are ignored.

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.

**Comment by Rj-s** [comment]
Its not working with latest primeng "primeng": "^4.0.1".
Below is the code which we can see in inspection but no icon is getting displayed.


<button _ngcontent-c3="" class="custom-btnPrimary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" iconpos="right" id="submitLoginId" pbutton="" type="submit" ng-reflect-icon-pos="right" ng-reflect-label="Log In" icon="fa fa-spinner fa-pulse">
    <span class="ui-button-text ui-c">Log In</span>
</button>

**Comment by jmcmichael** [comment]
I am still seeing this issue. I set up the following button:

``` html
<button pButton type="submit"
        label="Launch Process"
        [attr.icon]="(serverRequestActive$ | async) ? 'fa-spinner' : null"
        [disabled]="!startForm.valid"></button>
```
This is rendered as:
``` html
<button _ngcontent-c1="" label="Launch Process" pbutton=""
        type="submit" ng-reflect-label="Launch Process"
        icon="fa-spinner" disabled=""
        class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only">
        <span class="ui-button-text ui-c">Launch Process</span>
</button>
```

Note that if I substitute 'true' for '(serverRequestActive$ | async)' the same thing happens. This behavior appears identical to that originally reported in this issue.

**Comment by Rj-s** [comment]
Try this:- 

    <button pButton type="submit"
        label="Launch Process"
        icon="iconName"
        [disabled]="!startForm.valid"></button>


Component:- 

    public iconName='none'; // make sure you put some string here. you can keep blank space also.
    ngOnint(){
    {
    // make a server call  and let server side boolean come then:- 
    this.iconName = serverSideBoolean ? 'fa-spinner' :this.iconName ;
    }

**Comment by jmcmichael** [comment]
Thank you for your suggestion, which worked but with one small adjustment. I moved the icon name assignment operation into the controller as you suggested. As I am using ngrx's subjects with select/subscribe, the component looks more like this:

*Controller:*
``` typescript
export class StartFormComponent {
  submitIcon: string;

  constructor(private store: Store<AppState>) { 
    this.serverRequestActive$ = store
      .select<boolean>(state => state.ui.serverRequestActive);

    this.serverRequestActive$.subscribe(active => {
      this.submitIcon = active ? 'fa-spinner' : 'fa-play';
    });
```
*Template*
``` html
<button pButton type="submit"
     label="Launch Process"
     [icon]="submitIcon"
     [disabled]="!startForm.valid"></button>
```
Note the addition of the brackets around the icon attribute in order to bind it.
