### ISSUE TITLE
Wrong highlighting of list item in context menu when menu items are more than 10

### ISSUE THREAD

**Issue by danielabhishekamm** [primefaces/primeng#9780]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-contextmenu-demo-nkbadu?file=src/app/app.component.ts

**Current behavior**
Wrong highlighting of list item in context menu when you hover on a menu item > 10th index

**Expected behavior**
Only the hovered menu item should be highlighted

**Minimal reproduction of the problem with instructions**
Increase the model list length to >10 items
Hover on 10th or greater menu item, the second item gets highlighted too

**What is the motivation / use case for changing the behavior?**
NA

**Please tell us about your environment:**
Windows 10
VS Code 
Node v10+

* **Angular version:** 5.X
Angular 10

* **PrimeNG version:** 5.X
11+

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript ES6

* **Node (for AoT issues):** `node --version` =   

![image](https://user-images.githubusercontent.com/21146024/104911560-1026e500-59b1-11eb-8ac4-c3809aa8ed9e.png)

**Comment by yigitfindikli** [comment]
Fixed in v11.2.1
