### ISSUE TITLE
Virtual scroll support in DataView control

### ISSUE THREAD

**Issue by Chazing** [primefaces/primeng#9781]
**I'm submitting a ...**
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The current DataView control does not support virtual scroll

**What is the motivation / use case for changing the behavior?**
For a DataView with a lot of items that will work efficiently, virtual scrolling is needed 

**Please tell us about your environment:**

* **Angular version:** 10.1.5

* **PrimeNG version:** 10.0.3

* **Browser:** [all]

* **Language:** [all]

**Comment by QuentinLeCaignec** [comment]
+1 on this, it seems obvious for the data view which is about list and grid list of item to have a way to use the virtual scroll. 

I'm stuck trying to turn my current dataview grid into a virtual scroll since it might fix the current Chrome issue of max 1000 grid rows displayed (current limitation of chrome's CSS grid). I've managed to turn the grid layout into a beautiful masonry display but I need some kind of virtual scroll to get around the limits of a large dataset that's too much to display all at once and without pagination.

**Comment by sanketsw** [comment]
The p-virtualScroller does not support Multi columns (Grid View) and  p-gridView does not support virtual scroll. At this stage I am stuck and cannot use either of the component to display a photo gallery grid.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by paulamoralesf** [comment]
I'm facing the same issue with PrimeNG version 15, still it is not solved and I did some tricks to make it work but it has a weird behavior because of the scrollHeight defined, as it has the half of the height expected I have a white space when the list of items ends.

**Comment by sidharthbajpai** [comment]
Still facing the same issue in **2024.** Freely scrolling infinitely in a e-commerce app **is a luxury**, which avoids the pain of clicking next page for every bunch of items that you do not want. This functionality is crucial for a data view, whose purpose is strongly inclined towards displaying products in a convenient manner. Kindly request you to reopen this issue please.
