### ISSUE TITLE
Carousel swipe not working in iOS

### ISSUE THREAD

**Issue by sanchitos** [primefaces/primeng#9786]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
[https://www.primefaces.org/primeng/showcase/#/carousel](https://www.primefaces.org/primeng/showcase/#/carousel) 

**Current behavior**
Open up [https://www.primefaces.org/primeng/showcase/#/carousel](https://www.primefaces.org/primeng/showcase/#/carousel) 

If you open it up in responsive mode in chrome / use it on Android the swiping works fine. If you try to do the same in iOS it doesn't work.

**Expected behavior**
The gestures should work on both on iOS and Android

**What is the motivation / use case for changing the behavior?**
The user experience should be the same on both systems.

**Please tell us about your environment:**

* **Angular version:** 11

* **PrimeNG version:** 11

* **Browser:** [iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =

**Comment by n2pro-wa** [comment]
A similar problem

**Comment by Tilesto** [comment]
Same issue +

**Comment by Oledjio** [comment]
A similar problem +

**Comment by sgpatel5** [comment]
Same issue +

**Comment by samuelwang48** [comment]
a hotfix

```ts
  ngAfterViewChecked(): void {
    const carousels = document.querySelectorAll('.p-carousel-items-container');
    if (this.primengCarouselSwipeFix === false && carousels.length > 0) {
      console.log("carousels", carousels);
      carousels.forEach( (carousel: any) => {
        console.log("fix carousel vertical swipe on touch event based device", carousel);
        const fixEventIndex = 3;
        carousel.removeEventListener("touchmove", carousel.eventListeners()[fixEventIndex]);
      }); 
      this.primengCarouselSwipeFix = true;
    }   
  }
```

**Comment by grenobnik** [comment]
yes, very annoying issue. Thank you, @samuelwang48, I am going with removing the event listener approach.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by franpereadev** [comment]
same problem still happens in new versions

**Comment by alexapascu** [comment]
same issue +

**Comment by wasit-shafi** [comment]
> There is an event "touchmove" blocking the scroll. I guess it was used to prevent the view on mobile devices from having "bouncing" effect. On the other hand, it is also preventing the other directions to act naturally on mobile devices. A hotfix, not perfect.
> 
> ```ts
>   ngAfterViewChecked(): void {
>     const carousels = document.querySelectorAll('.p-carousel-items-container');
>     if (this.primengCarouselSwipeFix === false && carousels.length > 0) {
>       console.log("carousels", carousels);
>       carousels.forEach( (carousel: any) => {
>         console.log("fix carousel vertical swipe on touch event based device", carousel);
>         const fixEventIndex = 3;
>         carousel.removeEventListener("touchmove", carousel.eventListeners()[fixEventIndex]);
>       }); 
>       this.primengCarouselSwipeFix = true;
>     }   
>   }
> ```

# Something similar/related for fixing the issue on StackOverflow 
https://stackoverflow.com/questions/62302234/cant-vertical-scroll-page-on-mobile-devices-with-full-width-primeng-carousel/62581853#62581853.
FYI: We were facing this issue on all the mobile/touch-based devices

**Comment by alexapascu** [comment]
same issue
