### ISSUE TITLE
Toast customized template displayed after close button

### ISSUE THREAD

**Issue by tlgman** [primefaces/primeng#9787]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When I define 'message' template. Html is dispalyed after 'close Cross button'.

**Expected behavior**
The template should appear before the cross.

**Minimal reproduction of the problem with instructions**
Exemple of custom message template : 
```html
<p-toast position="bottom-right">
  <ng-template let-message pTemplate="message">
    <div class="p-toast-message-text">
      <div class="p-toast-summary">My custom summary: {{message.summary}}</div>
      <div class="p-toast-detail">{{message.detail}}</div>
    </div>
  </ng-template>
</p-toast>
```

**What is the motivation / use case for changing the behavior?**
If no template is setted. Html from the template is rendered before the button. 
If there is a custom template, the html is rendered after the close button.
We can see that on this line :
https://github.com/primefaces/primeng/blob/afb92e5589a1f19f7a29b1cea6bf8a0816198e92/src/app/components/toast/toast.ts#L28

Maybe it's normal, but I don't understand why.

* **Angular version:** 11.05

* **Browser:** [Chrome XX | Firefox XX | IE XX]

**Comment by yigitfindikli** [comment]
You can use the closable property of toast.
