### ISSUE TITLE
Make table row filter funnel icon buttons detachable

### ISSUE THREAD

**Issue by Cito** [primefaces/primeng#9789]
**I'm submitting a ...**  (check one with "x")

- [ ] bug report
- [X] **feature request**
- [ ] support request

**Current behavior**

If you use the "Filter Row" approach for [Table Filters](https://primefaces.org/primeng/showcase/#/table/filter), then each filter column gets two additional filter buttons (with funnel icon), one for applying and one for removing. This wastes a lot of space if you have narrow columns. The "remove filter" button (second, crossed through funnel) is not really necessary, since you can remove the filter with the "apply filter" button (first, normal funnel) as well. But even the "apply filter" button would not be strictly neccesary if the filters were applied instantenously (see #9581), the only advantage is the ability to specify a match operator.

**Expected (suggested) behavior**

Make the attribute directives `showClearButton` and `showApplyButton` also work with the `row` display mode in order to control the two funnel icons. It seems they currently only work in `menu` display mode.

**What is the motivation / use case for changing the behavior?**

Save screen space and declutter the filter row.

* **Angular version:** 11.0

* **PrimeNG version:** 11.1

* **Browser:** all

**Comment by ThomasPrikrylBE** [comment]
Is there an update on this? I wanted to use `showMenu=false` and `showClearButton=true` to avoid having the filter menu funnel button but to be able to clear the filter input via the clear button, however as mentioned above `showClearButton `seems to be not controlling the row display mode buttons.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
