### ISSUE TITLE
Radiobutton: How to emit the latest model value?

### ISSUE THREAD

**Issue by vishal3007** [primefaces/primeng#979]
p-radioButton has only onclick preperty to emit the model value(https://angular.io/docs/ts/latest/cookbook/component-communication.html#!#child-to-parent) but as this is called on click event and by that time model is not updated therefore the old value is emitted.

import { Component, OnInit, EventEmitter, Output } from '@angular/core';

@Component({
    selector: 'activity-tree-type',
    template:
    `
        <p-radioButton name="activityTreeType" value="1" label="Value 1" 
            [(ngModel)]="selectedTreeType" (onClick)="activityTreeTypeClicked($event)"></p-radioButton>
        <p-radioButton name="activityTreeType" value="2" label="Value 2" 
            [(ngModel)]="selectedTreeType" (onClick)="activityTreeTypeClicked($event)"></p-radioButton>
    `
})
export class FcRolesActivityTreeTypeComponent implements OnInit {
    private selectedTreeType: number = 1;
    @Output()
    private onTreeTypeChange: EventEmitter<number>;

    constructor() {
        this.onTreeTypeChange = new EventEmitter<number>();
    }

    ngOnInit() { }

    activityTreeTypeClicked(): void {
        console.log('click: ' + this.selectedTreeType);
        this.onTreeTypeChange.emit(this.selectedTreeType);
    }
}

Edit:
I got it working with "ngModelChange" instead of "onClick" property.

**Comment by mrgoos** [comment]
Hi,
I have encountered this issue as well.
I don't see the point of using `ngModelChange` and `ngModel` at the same time.
Is there any other solution?
Thanks.

**Comment by mahesh5b5** [comment]
@vishal3007  Thanks mate ngModelChange  worked for me !
