### ISSUE TITLE
Make virtualscrolling works & active with pTemplate="rowexpansion"

### ISSUE THREAD

**Issue by dktjsp** [primefaces/primeng#9799]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
 
/

**Current behavior**

When using row grouping feature with row expansion & virtualScroll enabled, the virtual scroll is lagging

**Expected behavior**

Use the virtual scroll when using rowexpansion rows

**Minimal reproduction of the problem with instructions**

Reproduce the example like in the documentation (minimal component & template below) but with virtual scrolling enabled & a lot of items

Table component 

```
<p-table
        #table
        (onSort)="onSort()"
        (selectionChange)="onSelect($event)"
        [autoLayout]="true"
        [columns]="selectedColumns"
        [dataKey]="groupCol?.property"
        [resizableColumns]="true"
        [rowTrackBy]="rowTrackBy()"
        [rows]="30"
        [scrollable]="true"
        [selection]="selectedItems"
        [totalRecords]="dataset?.length"
        [value]="dataset"
        [virtualRowHeight]="34"
        [virtualScroll]="true"
        columnResizeMode="expand"
        scrollHeight="flex"
        sortMode="multiple"
        styleClass="p-datatable-sm">

....

</p-table>
```

Row expansion template 

```
 <ng-template  let-expanded="expanded" let-columns="columns" let-rowData let-rowIdx="i" pTemplate="rowexpansion">
          <ng-container [ngTemplateOutletContext]="{columns: columns, rowData: rowData, rowIdx: rowIdx}"
                        [ngTemplateOutlet]="rowContent"></ng-container>
        </ng-template>
```

**What is the motivation / use case for changing the behavior?**

Performances & improved app experience !

**Please tell us about your environment:**

Windows
Chrome

* **Angular version:** 5.X

Angular 11

* **PrimeNG version:** 5.X

11.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   10.16.3

**Comment by GetoXs** [comment]
@dktjsp did you find any workaround? We have the same problem.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
