### ISSUE TITLE
Accordion | Programmatic tab reordering expands content of first tab

### ISSUE THREAD

**Issue by saramcicchi** [primefaces/primeng#9809]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-accordion-reorder

**Current behavior**
When Ivy is enabled, reordering accordion tabs unexpectedly shows the content of the tab.
<img width="108" alt="image" src="https://user-images.githubusercontent.com/5788052/105535317-bf6b0100-5cbc-11eb-9e23-9a7d7ca7a5ca.png">

When Ivy is disabled, reordering accordion tabs does not show the content of the tab, as expected.
<img width="108" alt="image" src="https://user-images.githubusercontent.com/5788052/105535070-6307e180-5cbc-11eb-8b8c-37791503859d.png">

**Expected behavior**
Reordering accordion tabs should not show the content of the tab when Ivy is enabled.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/primeng-accordion-reorder

**What is the motivation / use case for changing the behavior?**
Behavior should be the same between Ivy and View Engine compilations. (And should work with Ivy since that is the default  as of Angular 9).

**Please tell us about your environment:**

* **Angular version:** 10.X, 11.X

* **PrimeNG version:** 10.X, 11.X

* **Browser:** all

 
* **Language:** all

* **Node (for AoT issues):** `node --version` =   14.5.4

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by saramcicchi** [comment]
Hi @mertsincan, this is still an issue in PrimeNG v14.2.1. Here is an updated stackblitz: https://stackblitz.com/edit/github-pe98bl-pguqmr. Can you please reopen this issue?

**Comment by cetincakiroglu** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
