### ISSUE TITLE
Add compareSelectionBy property to DataTable.

### ISSUE THREAD

**Issue by ribizli** [primefaces/primeng#981]
Not only that the deep equals solution can result in performance problems, I don't see any reason to use it.

There should be an option (e.g. `selectionByRef`) to use strict equals instead of deep equals.

**Comment by cagataycivici** [comment]
Makes sense for sure, for deep equals there is dataKey to speed it up btw.

**Comment by cagataycivici** [comment]
Added compareSelectionBy="equals | deepEquals".  Made it a string as I have a plan to introduce a 3rd faster option.

**Comment by ribizli** [comment]
What if there isn't a suitable dataKey? At least that shoud support a function input to use identity...

**Comment by cagataycivici** [comment]
If there is no dataKey, then equals (identity) or deepEquals (equality).

**Comment by ribizli** [comment]
I've read your answer too late,  sorry.
