### ISSUE TITLE
When table is  lazy and having sorting then "lazyLoad" execute twice

### ISSUE THREAD

**Issue by lightstore** [primefaces/primeng#9810]
[ x] bug report --> SUPER BUG

**Current behavior**
When table is  lazy and having sorting then "lazyLoad" execute twice

**Expected behavior**
Every call to server must execute once.
Table after take parameters about lazy or sorting or filtering must call server once

**Minimal reproduction of the problem with instructions**
When initialize Table component
1.First call at ngOnInit and second call at sort
2.When user click header for sort, first call at ngOnChanges second call at sort

* **Angular version:** 11.0
* **PrimeNG version:** 11.1

**Comment by lightstore** [comment]
Dear sirs,

you must solve the problem because is very critical !

**Comment by yigitfindikli** [comment]
Fixed in v11.2.1.

**Comment by lightstore** [comment]
Dear sirs,

when table initialize problem solved but,
when apply new sort table call again server twice.

When click column header for sorting table response:
1.onClick      line 3190
   sort           line 1009
   **sortSingle line 1058 <--- one call**

2.ngOnChanges   line 891
   **sortSingle          line 1058  <--- second call**
