### ISSUE TITLE
Accessibility: p-calendar uses aria-required incorrectly

### ISSUE THREAD

**Issue by eemt** [primefaces/primeng#9818]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
p-calendar comonent, when using the "required" property, inserts 
aria-required=""
That is not a valid value.

"The aria-required property can have values of 'true' or 'false'."
https://www.w3.org/TR/WCAG20-TECHS/ARIA2.html

**Expected behavior**
PrimeNG components should use ARIA properties correctly.

ARIA attributes must conform to valid values
https://dequeuniversity.com/rules/axe/4.1/aria-valid-attr-value?application=AxeChrome

**Minimal reproduction of the problem with instructions**
Use Calendar component with an input and the require attribute, then run accessibility tools such as axe.

**What is the motivation / use case for changing the behavior?**
To pass accessibility audits

**Please tell us about your environment:**

* **Angular version:** 10

* **PrimeNG version:** 10

* **Browser:** all

**Comment by BaronRocco** [comment]
i am experiencing this issue as well.  is there a known workaround?
note: original post was 6 months ago.

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
