### ISSUE TITLE
Toggleable Row Groups - Multiple Field Grouping - primeng 9

### ISSUE THREAD

**Issue by ruchiagrawal2** [primefaces/primeng#9820]
I am using prime ng 9. I have successfully implemented row grouping on p-table on one field. I am not able to find how to extend the same for multiple fields. Prime ng documentation from version 5 to version 11 says "Similarly multiple field grouping can be implemented as well" but there is not an example added in any versions. 
Using the example in the documentation link below lets say I want to group on Color in addition to Brand. I only want to show Vin and Year in table column heading but have two expandable rows first for brand , then on color . only when you expanding on color you see the other information. This is what I want to implement for my customer and I could not find success after trying few combinations . Can you please provide sample code ?
https://www.primefaces.org/primeng/v9-lts/#/table/rowgroup

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.

**Comment by ruchiagrawal2** [comment]
This is an issue . Row Grouping on Multiple fields is not working .

**Comment by AvshT** [comment]
I'm agree with @ruchiagrawal2.

@yigitfindikli can you please give a **stackblitz** example of how to achieve **multiple row groups using p-table**
