### ISSUE TITLE
PrimeNG Tables - Horizontal scrolling behaves strangely

### ISSUE THREAD

**Issue by marcodafonseca** [primefaces/primeng#9821]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://primeng-tablefilter-mobile-bug-tqyogp.stackblitz.io

**Current behavior**
The bug only appears in mobile/tablet devices. Desktop works perfectly.
What happens is when horizontal scrolling and filtering is enabled and the users filters by a column that is on the far right the horizontal scrolling behaves strangely. The header and body columns get misaligned and sometimes the scroll appears to go back to the far left again and restart the scrolling process.

**Expected behavior**
Horizontal scrolling should behave normally as per desktop.

**Minimal reproduction of the problem with instructions**
https://primeng-tablefilter-mobile-bug-tqyogp.stackblitz.io

**What is the motivation / use case for changing the behavior?**
This current behavior is not ideal for users

**Please tell us about your environment:**

* **Angular version:** 5.X

* **PrimeNG version:** 5.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
