### ISSUE TITLE
Toggleable Row Groups - Multiple field Grouping not working. 

### ISSUE THREAD

**Issue by ruchiagrawal2** [primefaces/primeng#9825]
**Kindly do not close the issue without any solution , I have searched the forums and there is no solution with implementing the multiple field grouping similarly as one field.**

I am using prime ng 9. Row Grouping for p-table only works for one field.  Extending to group on multiple fields does not  work. The documentation from version 5 to version 11  just says "Similarly multiple field grouping can be implemented as well" . But extending it does not work. 

Using the example in the documentation link below lets say if you add to group on Color in addition to Brand. I have tried similar implementation for my customer need  and this is not working on prime ng 9

https://www.primefaces.org/primeng/v9-lts/#/table/rowgroup

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a stackblitz example.

**Comment by jy006** [comment]
@ruchiagrawal2 have you found something? Or have you moved on?
I'm using the rowspan mode and hoping it would be possible to group multiple rows on the table. The documentation says:

> Multiple row grouping is available in "rowspan" mode by specifying the groupRowsBy as an array of fields.

But adding an array of fields does not change anything. Also there's no example anywhere. There's only one [post](https://forum.primefaces.org/viewtopic.php?t=65208) on the forum with no response either.
