### ISSUE TITLE
Disabled radio still clickable via label

### ISSUE THREAD

**Issue by JakeSummers** [primefaces/primeng#983]
When you have a radio button that is disabled you can still click on the text beside the radio button to toggle it.  

For example, dispite the fact that `BAR` is disabled, I can still click on the text `BAR` to select the button: 

![image](https://cloud.githubusercontent.com/assets/5657503/18934943/bf1d0c68-85aa-11e6-9c9b-f444db554b68.png)

After Click: 

![image](https://cloud.githubusercontent.com/assets/5657503/18934978/fe1f6a96-85aa-11e6-8142-54bcbf85d314.png)

Code: 

```
<p-radioButton class="radio-holder"
               value="bar"
               label="BAR"
               [disabled]="true"
               [(ngModel)]="foo"
></p-radioButton>
<p-radioButton class="radio-holder"
               value="baz"
               label="BAZ"
               [disabled]="true"
               [(ngModel)]="foo"
></p-radioButton>
```

Clicking on the actual button works as selected (it won't change the selected state).

**Comment by ziadvictor** [comment]
This issue was fixed for <p-radioButton> but not for <p-tableRadioButton> which should be used inside a <p-table>
