### ISSUE TITLE
List box “toggle all” checkbox needs to have a label

### ISSUE THREAD

**Issue by EOussama** [primefaces/primeng#9835]
**Current behavior**
No way to add a label next to the “toggle all” checkbox

**Expected behavior**
An input variable that allows for inserting a text or a template to customize the accessibility message

**What is the motivation / use case for changing the behavior?**
For accessibility reasons, there needs to be a label that informs users what the checkbox is for

* **Angular version:** 10

* **PrimeNG version:** 10.X
 
![image](https://user-images.githubusercontent.com/22644543/106271662-272aca00-6230-11eb-8360-7f65bb1945c1.png)

**Comment by EOussama** [comment]
This issue is a follow up to [this pr](https://github.com/primefaces/primeng/pull/5242)

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
