### ISSUE TITLE
Not filtering date using "Is"  in table

### ISSUE THREAD

**Issue by RobertoFreireFerrazPassos** [primefaces/primeng#9838]
Use url:
https://primefaces.org/primeng/showcase/#/table/filter

Got o the first table called Filter Menu
Look at the collumn Date
The first value is 09/12/2015

try filter using Match All Is 09/12/2015

It bring not results

NOTE: Probably this error occurs because some hours difference in Date value between the DateTimePicker in Callender and the actual value in the table

**Comment by cagataycivici** [comment]
Fixed via https://github.com/primefaces/primeng/issues/9879
