### ISSUE TITLE
Resize on TreeTable

### ISSUE THREAD

**Issue by jtesser** [primefaces/primeng#984]
There doesn't seem to be any columnResize on TreeTable.  I a using 1.0.0-beta.16

**Comment by mmlitvin** [comment]
I run into the same issue. 
Styling p-column works inside of the p-dataTable but not inside of the p-treeTable
=================
This works
 <p-dataTable styleClass="recTable" [value]="rows" [scrollable]="true" scrollHeight="300px" >
 <p-column field="icon" header="" [style]="{'width':'40px'}"></p-column>
 </p-dataTable>

=================
but this does not work
<p-treeTable styleClass="recTable" [value]="rows" (onNodeExpand)="loadNode($event)"  [scrollable]="true" scrollHeight="300px">
 <p-column field="icon" header="" [style]="{'width':'40px'}"></p-column>
 </p-treeTable >
======================
thanks

**Comment by mmercan** [comment]
+1

**Comment by jtraband** [comment]
+1

**Comment by veplechuc** [comment]
any news on this issue?

**Comment by cagataycivici** [comment]
@Mrtcndkn Please take over.

**Comment by Mrtcndkn** [comment]
https://github.com/primefaces/primeng/commit/f5aef0ce331596bdaf8538fb9f9e095d35236cb9

**Comment by cagataycivici** [comment]
Revert as it is broken, will do it for 4.1.x.

**Comment by finalxcode** [comment]
+1

**Comment by fabgas** [comment]
Any milestones for this features please ?

**Comment by hgrgic** [comment]
+1 ASAP

**Comment by EkamKamboj** [comment]
Any update for the same ?
