### ISSUE TITLE
Because the char &nbsp; in p-button, I got a ugly pick-list.

### ISSUE THREAD

**Issue by PedroEast** [primefaces/primeng#9840]
I tried to add a `p-pickList` in my website. It looks good in your example. But when I added it, I found the ugly char `&nbsp` in the 12 buttons. Maybe the String which has no char is need in your `p-button-label`.

**Comment by PedroEast** [comment]
Here is my package.json 
`
"primeicons": "^4.1.0",
"primeng": "^11.2.0",
"quill": "^1.3.7",
"@fullcalendar/core": "^5.5.1",
`

**Comment by PedroEast** [comment]
I have to operate DOM to delete &nbsp; It's unhappy. Use `AfterViewInit` hook in Angular, and delete it by DOM.

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
