### ISSUE TITLE
p-autocomplete does not clears selected object when CTRL-Z is pressed in textbox

### ISSUE THREAD

**Issue by rekna1** [primefaces/primeng#9842]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/github-16c1yp

**Current behavior**
autocomplete with forceSelection=true
type 'first' into textbox and selected item
id 1 shows next to label id:
now press CTRL-Z (cursor moves to beginning of line) and then immediately press TAB
id is cleared but First remains in textbox so one has the idea an items was selected but no id is showing

**Expected behavior**

- CTRL-Z just moves cursor to beginning of line, it should delete the text
- When pressing TAB after CTRL-Z, the object (in this case 'item' on the component) should be null

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/github-16c1yp
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 11.1

* **PrimeNG version:** 11.2

* **Browser:** [chrome]

 
* **Language:** [TypeScript 4.x ]

**Comment by LeonardoHenriqueOliveira** [comment]
There is another problem with p-autocomplete. 
When p-autocomplete in a p-inputgroup with p-fluid, the input object does not use all the column width. When we put a p-input in stead of p-autocomplete, it function.
