### ISSUE TITLE
Getting started documentation for Ripple is incomplete (need to add RippleModule to App Module imports)

### ISSUE THREAD

**Issue by frankhale** [primefaces/primeng#9843]
I'm a complete newbie with PrimeNG and I was following the getting started steps and I wanted to create a button with the ripple effect. The ripple set up instructions leave out that you need to add the RippleModule to your App module imports. Once I added the RippleModule and pRipple to my buttons it worked fine.

**Comment by yigitfindikli** [comment]
You can check at https://www.primefaces.org/primeng/showcase/#/ripple
