### ISSUE TITLE
Close dialog by key 'esc' does only work on latest dialog

### ISSUE THREAD

**Issue by Rotzbua** [primefaces/primeng#9846]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://github-9h3z9y.stackblitz.io

**Current behavior**
Dialog can be closed by pressing 'esc'.
It does only work for one latest opened dialog. If more than one dialog is opened it does not work after the latest dialog is closed.

**Expected behavior**
If the latest dialog is closed, the next still opened dialog should be closed by 'esc'.

**Minimal reproduction of the problem with instructions**
see https://plnkr.co

**What is the motivation / use case for changing the behavior?**
better usability with keyboard

**Please tell us about your environment:**

* **Angular version:** 11.X

* **PrimeNG version:** 11.1.0

* **Browser:** all

**Comment by AvshT** [comment]
Hi,
@yigitfindikli the problem is in dialog hide func, you should **decrease DomHandler.zindex by 1** after the hide.

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
