### ISSUE TITLE
p-dropdown (as well as other components) is not disabled when inside fieldset with disabled attribute

### ISSUE THREAD

**Issue by rekna1** [primefaces/primeng#9848]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
**Current behavior**
if p-drowndown is child of &lt;fieldset&gt; with attribute disabled p-dropdown is not disabled 
like when a regular Html &lt;select&gt; element is child of &lt;fieldset disabled&gt; one can not select any option

this probably applies to other components as well.

**Expected behavior**
I expect a p-drowdown to be disabled when that p-dropdown is contained within a fieldset with the disabled attribute set.
**fieldset** allows efficiently to disable a group of inputs without having to disable each input individually

**Minimal reproduction of the problem with instructions**

```
<fieldset disabled>
  <p-dropdown .... ></p-dropdown>
 </fieldset>
```

**What is the motivation / use case for changing the behavior?**
It should follow standard HTML specifications https://www.w3schools.com/tags/att_fieldset_disabled.asp

**Please tell us about your environment:**

Windows 10, npm, VSCODE, IIS, 

* **Angular version:** 11.1

* **PrimeNG version:** 11.2

* **Browser:** [all]
 
* **Language:** [all ]

**Comment by gayatriraichandani** [comment]
Facing the same issue..

**Comment by rekna1** [comment]
Like to add the following comment : as I've experienced through developping web applications, I prefer using standard HTML elements with custom behaviour through directives (if it's possible, of course). The reason : you will be more future proof, because in this case when HTML introduces new attributes/properties/behaviour, if you use a custom component, those will not be available to this component unless you implement them as well. The above issue is a perfect example, if a dropdown was an input element with a directive, it would have supported disable inside disabled fieldset probably out of the box. Provided of course it is feasible to implement a dropdown using a directive. ( aria attributes are another example, and those are hard enough to get right on standard elements)

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by jtraband** [comment]
Still running into this... In what version was it fixed???
