### ISSUE TITLE
Displaying loading icon while nodes with a large number of children is being expanded.

### ISSUE THREAD

**Issue by javiergedeon-tm** [primefaces/primeng#9849]
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Current behavior**
Currently expanding a node with too many children nodes takes too long, it stays frozen and there's no way of letting users know the tree is working in the background.

**Expected behavior**
The loading icon can be displayed while the node is being expanded.

**What is the motivation / use case for changing the behavior?**
Better user experience.

**Please tell us about your environment:**
Windows 10, npm, vs code, IIS,

* **Angular version:** 8.2.1

* **PrimeNG version:** 8.0.2

* **Browser:** [all ]
* **Language:** [all ]

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
