### ISSUE TITLE
Closable option on multiselect

### ISSUE THREAD

**Issue by OriolInvernonLlaneza** [primefaces/primeng#9850]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Unlike other components, the multiselect has no option to hide/disable the close button when opened.

**Expected behavior**
It would be nice to have the option to hide the button with a 'closable' property like in other components. Alternatively, there could be an option to enable a button to clear the selection in place of the close button or alongside it.

**Please tell us about your environment:**
* **Angular version:** 11.0.5

* **PrimeNG version:** 11.2

* **Browser:** [all]
 
* **Language:** [all]

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
