### ISSUE TITLE
saga-green disappeared in the Version 11.2.0

### ISSUE THREAD

**Issue by juri-sinitson** [primefaces/primeng#9855]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Saga green is no more there in the latest PrimeNG version 11 although it should be there according to https://primefaces.org/primeng/showcase/#/setup

```
$ find node_modules/primeng/ -iname "*green*"
node_modules/primeng/resources/themes/arya-green
node_modules/primeng/resources/themes/luna-green
node_modules/primeng/resources/themes/vela-green
```

So I get the error when compiling:
```
SassError: Can't find stylesheet to import.
@import "node_modules/primeng/resources/themes/saga-green/theme";
```

**Expected behavior**
saga-green is there again

**Minimal reproduction of the problem with instructions**
Update to the latest PrimeNG version 11 and issue `$ find node_modules/primeng/ -iname "*green*"` in the project dir or just compile the project with `$ ng serve --open`.

**What is the motivation / use case for changing the behavior?**
I used saga-green in production, now I need to work around

* **Angular version:** 11.1.1

* **PrimeNG version:** 11.2.0

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
