### ISSUE TITLE
DataView content has faulty styling

### ISSUE THREAD

**Issue by adama357** [primefaces/primeng#9856]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The CSS for the DataView component is such that the header and footer simply appear to float above and below the main content. 

This is because (I'm using the Nova theme here) in PrimeNG 10 and 11, the CSS for `.p-dataview .p-dataview-content` has no border or padding. 

![dataview11_1](https://user-images.githubusercontent.com/20462430/106933986-32be3b00-66df-11eb-97ac-889de47dc629.png)

**Expected behavior**
In PrimeNG 9, the CSS for `body .ui-dataview .ui-dataview-content` has `padding: 0.571em 1em;` and `border: 1px solid #c8c8c8;`. This made it so the header and footer formed a box around the content: 

![dataview9](https://user-images.githubusercontent.com/20462430/106936276-022bd080-66e2-11eb-957b-cbd133d88a16.png)

If I add this styling to the PrimeNG 11 demo, it looks great:

![dataview11_2](https://user-images.githubusercontent.com/20462430/106936351-1374dd00-66e2-11eb-85bc-dc50b6815d00.png)

**Minimal reproduction of the problem with instructions**
PrimeNG 11 showcase: https://www.primefaces.org/primeng/showcase/#/dataview

vs PrimeNG 9 showcase: https://www.primefaces.org/primeng/v9-lts/#/dataview

**Please tell us about your environment:**
Windows 10

* **Browser:** [all]

**Comment by yigitfindikli** [comment]
We'll reconsider if there is more community feedback on this. Thank you for your report.

**Comment by CD-UNCC** [comment]
@yigitfindikli you mean this isn't a regression? This seems like something that should be addressed our team was confused by this as well.

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
