### ISSUE TITLE
MultiSelect chip can be used with maxSelectedLabels and selectedItemsLabel

### ISSUE THREAD

**Issue by sourdoth** [primefaces/primeng#9859]
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
MultiSelect: 
Hi!, when display="chip" on Multiselect the attribute selectedItemsLabel="{0} items selected" not works, only work when i remove the "chip"

**Expected behavior**
work this -> selectedItemsLabel="{0} items selected" when enable "chip" property


* **PrimeNG version:** 11.2
<!-- Check whether this is still an issue in the most recent Angular version -->

**Comment by arielkuzminski** [comment]
Any update on this?

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by kavitha10** [comment]
Still the above is there in primeng v-13.4.1
MultiSelect: 
when display="chip" on Multiselect the attribute selectedItemsLabel="{0} items selected" not works, only works when i remove the "chip"
