### ISSUE TITLE
p-steps shows menu item which is marked as invisible

### ISSUE THREAD

**Issue by VILLAN3LL3** [primefaces/primeng#9865]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
[Editor URL](https://stackblitz.com/edit/github-bc9uim?file=src/app/app.component.ts)
[Application URL](https://github-bc9uim.stackblitz.io)

**Current behavior**
A menu item whose property _visible_ was set to _false_ is still displayed in the stepper

**Expected behavior**
A menu item whose property _visible_ was set to _false_ is not displayed in the stepper

**Minimal reproduction of the problem with instructions**
see stackblitz

**What is the motivation / use case for changing the behavior?**
Use case: The items of a stepper are only generated at runtime. In some cases a middle step should not be displayed, but the activationIndex property of the individual steps should be retained.

**Please tell us about your environment:**
n/a, see stackblitz

* **Angular version:** 5.X
11.0.5 (stackblitz), 11.1.0 (my local machine)

* **PrimeNG version:** 5.X
11.1.0-rc1 (stackblitz), 11.2.0 (my local machine)

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

**Comment by yigitfindikli** [comment]
We'll reconsider if there is more community feedback on this. Thank you for your report.

**Comment by jonnomk** [comment]
If the step component uses MenuItem API, then it should support visibility, right?  I have a scenario where I want to hide an item in the stepper if a certain condition evaluates to true, so could use this - thanks.

**Comment by Inaamgharbi** [comment]
@yigitfindikli   We have the same problem

**Comment by igor-h** [comment]
> @yigitfindikli We have the same problem, any news ?

Any news, what I did I just filtered the array like this:

```
...
      {
        label: this.translateService.instant('contract.edit.tabs.terms'),
        routerLink: 'terms',
        visible: this.isVisibileTerms()
      },
      ...
    ];

    // Filter and assign only visible steps:
    this.stepsItems = steps.filter(item => item.visible);

```

**Comment by igor-h** [comment]
@cetincakiroglu  Just checked the version 14 documentation. And the issue is still happening.

**Comment by jonnomk** [comment]
Yes, can this please be re-opened @cetincakiroglu ?
