### ISSUE TITLE
Overlaypanel: Styling the border

### ISSUE THREAD

**Issue by tcoz** [primefaces/primeng#9869]
How can one style the entire border with the structural elements? The triangular pointer arrow (which I want to keep, please don't suggest removing it :) ) is created with a transform it seems. I need a way to style the left/right sides of the arrow triangle (leaving the bottom as-is so it appears to be part of the whole panel). 

The overlaypanel itself, the border is very straightforward to style with the structural elements. But that little arrow is blocking me from finishing that little style tweak.

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.

**Comment by tcoz** [comment]
This is disappointing. I bought a license so that I would have access to this area and timely support. Based on this response, that would appear to have been wasted money. What is the point of the issues section if a licensed user can't post an issue?
