### ISSUE TITLE
Dropdown toLocaleLowerCase is not a function when optionLabel is a number

### ISSUE THREAD

**Issue by tiagotrigger** [primefaces/primeng#9870]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
```

I will not put a plunkr because it is something simple.

**Current behavior**

The `optionLabel` of the dropdown expects the value to be a string and calls the function `toLocaleLowerCase`.
However, if the optionLabel represents a number, it will throw an exception `TypeError: this.getOptionLabel(...).toLocaleLowerCase is not a function`

Example at line 966, but there are other lines with the same call.
https://github.com/primefaces/primeng/blob/c9946d3e3cff773b05c642b12b19a0631a5e1408/src/app/components/dropdown/dropdown.ts#L966

**Expected behavior**

I think it would be better to accept numbers as well or at least not throw this hard to understand exception.

**Comment by vjonas** [comment]
Any idea when it'll get merged? :)

**Comment by Mahmoudibrahim03** [comment]
Any idea when it'll get merged !

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by cetincakiroglu** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.

**Comment by jammyjoker** [comment]
Still not fixed in PrimeVue DropDown. Just updated to the latest revision - 3.46.0.
