### ISSUE TITLE
Breing able to change date format of default calendar provided with primeng data table filter menu

### ISSUE THREAD

**Issue by chapoub** [primefaces/primeng#9874]
Hi,

I'm submitting a feature request.

Yet the p-columnFilter calendar showed by opening the menu is in format mm/dd/yy.
![PrimengCalendarImage](https://user-images.githubusercontent.com/36192104/107392251-62ab7b00-6af1-11eb-9f60-2e092bd2056c.jpg)

It would be nice if we were able to change this format without having to create a custom date filter menu.

Adding monthNavigator and yearNavigator attributes like for p-calendar would be really nice too.
![image](https://user-images.githubusercontent.com/36192104/107392581-bf0e9a80-6af1-11eb-9689-1e9b8d159f93.png)

Thanks a lot,

**Comment by yigitfindikli** [comment]
You can use 
```
<ng-template pTemplate="filter" let-value let-filter="filterCallback">
    <p-calendar...></p-calendar>
</ng-template>
```
