### ISSUE TITLE
Feature to add edit-mode of row to TreeTable component

### ISSUE THREAD

**Issue by PHuhn** [primefaces/primeng#9886]
**I'm submitting a ...**
```
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
```

**Current behavior**
p-table has a robust set of features.  I have chosen to use edit-mode of row.  I recently had a need to use TreeTable and it does not support that option.  For design consistency, it seem prudent to support edit-mode of row in both components.

**What is the motivation / use case for changing the behavior?**
Consistency across similar components.

**Please tell us about your environment:**
Windows 10 Pro

* **Angular version:**
Angular 11

* **PrimeNG version:** 
PrimeNG 11

* **Browser:**
Chrome
 
* **Language:**
TypeScript

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by Iznogood1** [comment]
Hi, 
It seems this improvement is still not implemented.
I would propose to reopen the issue as suggested by @cetincakiroglu 

Rgds

**Comment by Nabeeh-AlSawaf** [comment]
still not added
