### ISSUE TITLE
remove test console.log in production

### ISSUE THREAD

**Issue by cyptus** [primefaces/primeng#9889]
**Current behavior**
prime ng logs test strings with `console.log` in https://github.com/primefaces/primeng/blob/14b518a0ecf78faae3e0751edd209e1de251c2f7/src/app/components/table/table.ts#L773

**Expected behavior**
no test `console.log` in production

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **PrimeNG version:** master

* **Browser:** all
 
* **Language:** all

**Comment by leon-marzahn** [comment]
@yigitfindikli pls

**Comment by yigitfindikli** [comment]
Fixed in https://github.com/primefaces/primeng/commit/6969c808cfbdac1b508c5ba9cdb296dde49ae55e
