### ISSUE TITLE
TextArea with AutoResize has height of 0 if it starts as hidden

### ISSUE THREAD

**Issue by adama357** [primefaces/primeng#9890]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-befymr

**Current behavior**
If a textarea with autoResize is generated while hidden, its height gets set to 0. (This happens whether or not the text area contains text.)

**Expected behavior**
Even if it's hidden, its size should be set to whatever it's supposed to be.

**Minimal reproduction of the problem with instructions**
See stackblitz

**What is the motivation / use case for changing the behavior?**
Our website displays a loading screen while a page loads, so the page is hidden while it's loading. Once the loading screen disappears, the textareas all are flat, whether or not they contain text. This will cause confusion, and unless we can find some kind of workaround, this may prevent us from upgrading to PrimeNG 11. 

Relates to #9231 and #7000

**Please tell us about your environment:**
Windows 10

* **Angular version:** 11.1

* **PrimeNG version:** 11.2

* **Browser:** [Chrome 88 ]

**Comment by adama357** [comment]
I guess the problem line is 

`this.el.nativeElement.style.height = this.el.nativeElement.scrollHeight + 'px';`

in [inputtextarea.ts](https://github.com/primefaces/primeng/blob/master/src/app/components/inputtextarea/inputtextarea.ts). `scrollHeight` starts as 0 if the parent element is hidden. 

A better-than-nothing solution would be to only run that line if `scrollHeight `is set, so it remains set to `auto`.

**Comment by vukwilku** [comment]
+1

**Comment by gstokes** [comment]
Hi, just wondering is there any plan to fix this, it's quite an old issue yet no progress on it. Thanks

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by Haze272** [comment]
still not fixed!

**Comment by ProfEibe** [comment]
[cetincakiroglu](https://github.com/cetincakiroglu) please reopen this issue

**Comment by BRNTZN** [comment]
[cetincakiroglu](https://github.com/cetincakiroglu) don't know why this is closed it is still broken

**Comment by jules-js** [comment]
still appears in 16.9.1
