### ISSUE TITLE
Tree selection select wrong node after filter is applied

### ISSUE THREAD

**Issue by Andrei9b** [primefaces/primeng#9892]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior** 
After applying filter, the node selected through (onNodeSelect) event is different than the node clicked 

**Expected behavior**
After applying filter, the node selected through (onNodeSelect) event should be the one that is clicked

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/github-v3tsfz?file=src/app/app.component.ts
1. expand 'Pictures' node, select logo.jpg -> logo.jpg node is selected through (onNodeSelect) event
2. search for 'logo' using filter. Select 'logo.jpg'. -> 'Documents' node is selected through (onNodeSelect) event

* **PrimeNG version:** 7.X, 11.X

**Comment by yigitfindikli** [comment]
Hi @Andrei9b, 
I couldn't replicate on showcase and demo project. Can you replicate without stackblitz?

**Comment by danielbernhedwcs** [comment]
Does this issue have a solution anywhere else? after it was removed? 

It is still present in 13.4.1 and I see the same thing in the StackBlitz example above.
