### ISSUE TITLE
Not able to open menubar using enter key while navigating through keyboard using tab key.

### ISSUE THREAD

**Issue by iambhuvi** [primefaces/primeng#9897]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search GitHub for a similar issue or PR before submitting
[ ] feature request => Please check if the request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit a support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://www.primefaces.org/primeng/v9-lts/#/menubar <-- prime-ng 9
https://www.primefaces.org/primeng/v8.2.9-lts/#/menubar <-- prime-ng 8.2.9 LTS
https://www.primefaces.org/primeng-8.1.5/#/menubar <-- prime-ng 8.1.5

**Current behaviour**

1. If we get the focus on one of the item of menubar (example: File) by pressing tab keys and then press enter. The menu gets opened in prime-ng 8.1.5 but not in prime-ng 8.2.9 LTS and prime-ng 9. 
2. Also, navigating inside the menu the sub-menu items don't perform the command assigned to them on enter keypress.
3.  Also, sub-menu don't open on the press of enter key.

**Expected behaviour**
The menu item should behave like in 8.1.5 version of prime-ng i.e. open the menu and perform the desired command assigned to the menu item. 

1. If the focus is on File tab then pressing enter should open the file menu as drop-down style.
![image](https://user-images.githubusercontent.com/25735286/107931629-90396e00-6fa2-11eb-8169-8a1b091bad73.png)

2.If the focus is on File-> New-> Project and if the project has some assigned command then it should get invoked.  
3. The sub-menu should get opened by pressing the enter key.

**Minimal reproduction of the problem with instructions**
Go to the links provide above and follow the steps.

1. Get to the File Menu item (label) using the keyboard tab key and hit enter.
3. Get to the File-> New using the keyboard tab, enter key and hit the enter key.
4. Get to the File-> New-> Project using the keyboard tab, enter key and hit the enter key.

**What is the motivation/use case for changing the behaviour?**
In case a user keyboard-centric user and prefer to use the keyboard in the application. He/She won't able to do navigate the menu.

**Please tell us about your environment:**
Windows-10
Intellij Ultimate

* **Angular version:** 9.x

* **PrimeNG version:** 9.1.3

* **Browser:** [all | Chrome Version 88.0.4324.146 (Official Build) (64-bit) | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [typescript: 3.8.3| ES6 | ES5]

**Comment by iambhuvi** [comment]
Adding to the above-reported issue. In Menubar we should be able to navigate using arrow keys not just enter key.

1. Pressing "down arrow key" to open the menu and move downwards in the list.
2. Pressing the "up arrow key" to close the menu if you're on the top menu item otherwise move upwards.

Similarly for left and right arrow key to open and close sub-menus(focus on File->New, so pressing right arrow key on New opens its submenu and pressing left arrow key takes the focus back to the Files menu item).

**Comment by gstokesRev** [comment]
Hi Just wondering is there an update or solution for this

**Comment by jbcollings** [comment]
A partial workaround for this issue is to set the `url` property of `MenuItem` to the empty string if the menu item does not otherwise have a URL or router link set. This will resolve the issue if the menu item is used with a command or simply to contain other menu items.

The `url` and `routerLink` properties of the menu model are used to conditionally set the `href` attribute on an anchor element. However, browsers will not fire click events (triggered by the enter key in this case) on anchor elements that do not have an href. Setting `url` to the empty string forces the `href` attribute to exist with an empty value. This doesn't affect anything else as the click event handler already prevents the default behavior.

Unfortunately, this cannot be used to fix the issue for the dropdown menu button in the responsive layout. A proper fix would be to use a button instead of an anchor when the menu item does not have a URL or router link.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
