### ISSUE TITLE
OnRowDblClick Event on Data Table 

### ISSUE THREAD

**Issue by jkumawat** [primefaces/primeng#99]
Hi Prime NG Team,

I would request you to add a event on data-table row for double click which returns the selected object value return. 

Thank you.

**Comment by toregua** [comment]
Thank you jkumawat for asking and thank you PrimeNG for adding +1

**Comment by haisumkundi** [comment]
Is this feature already added?

**Comment by PhamVanthinh2801** [comment]
> Is this feature already added?

Nooo
