### ISSUE TITLE
datatable : templating and epand don't work together when template at the bottom

### ISSUE THREAD

**Issue by huineng** [primefaces/primeng#990]
I have a table with row expension and with templating (pug) (expandableRows="true")

with error
p-column(expander="true" styleClass="col-icon")
p-column([style]="{width:'6%'}", field="email")
         template(let-item="rowData",pTemplate="",type="body",let-col="")
               img.table-img-circle. etc..
template(let-item="")
                .ui-grid.ui-grid-responsive.ui-fluid

when clicking on the expand .. this gives an error .. cannot read undefined from undefined

with no error
p-column(expander="true" styleClass="col-icon")
     template(let-item="")
                .ui-grid.ui-grid-responsive.ui-fluid
p-column([style]="{width:'6%'}", field="email")
         template(let-item="rowData",pTemplate="",type="body",let-col="")
               img.table-img-circle. etc..

so in my opinion it's better to indent the template right after the field instead of putting it at the end at the same level as the fields as per your example

**Comment by jdpearce** [comment]
I just created a [project to illustrate this issue](https://github.com/jdpearce/primeng-issue-990) as it's affecting me too. I've wasted hours on this problem and would appreciate a fix to either the docs or the code.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with them and if issue persists drop a comment and we'll reopen. Make sure you use the template type with pTemplate.
