### ISSUE TITLE
"No provider for Table" error in Angular

### ISSUE THREAD

**Issue by omerfarukarslanks** [primefaces/primeng#9901]
angular version: 11,
primeng version: 11.2.1
typescript version: 4.0.5
node version: v15.4.0

When using the editable table I get an error "No provider for Table".  I copy the row editing example from https://www.primefaces.org/primeng/showcase/#/table/edit and add it to my project. I am giving my own mock data into it. In addition, the TableModule and the component I use with other related modules are also included in the app.module. Unfortunately I could not find any solution. I would be glad if you could help.

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.
