### ISSUE TITLE
Range slider cannot be changed when initialized with maximum value

### ISSUE THREAD

**Issue by simdevmon** [primefaces/primeng#9902]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
If a range slider is initialized with both values of the maximum range (e.g. [100,100]) it is not possible to change the value (e.g. decrease the lower part).
The the initial value is different (e.g. 20, 80) and both sliders are moved to the maximum value, it works fine. 

**Expected behavior**
It should be possible to move the slider.

**Minimal reproduction of the problem with instructions**

- Go to the slider demo: https://primefaces.org/primeng/showcase/#/slider
- Change the value of the range `rangeValues: number[] = [100, 100];`
- Slider cannot be moved anymore 

![image](https://user-images.githubusercontent.com/16277781/108047995-ca5c4b80-7046-11eb-9672-0206a6b3de93.png)

* **Angular version:** 5.X
11.2.0

* **PrimeNG version:** 5.X
11.2.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Google Chrome

**Comment by yigitfindikli** [comment]
Fixed in v11.3.0
