### ISSUE TITLE
Feature to use edit-mode of row with Grouped Column Layout to TreeTable component

### ISSUE THREAD

**Issue by hamza-aniba** [primefaces/primeng#9903]
**Current behavior**
The problem appears when I use the Treetable edit and the grouped column in this case the type of the row where we have the option grouped column take by default the same type of the following row for example if I have an editable column (grouped column ) with a text type and the first column below is editable and with the date type, when we want to edit the grouped column it takes the date type instead of the text type

**Expected behavior**
I expect each editable col to keep the starting type (text, date ...) even when using the colgroup pattern.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
 Windows 10 Pro, VSCode 

* **Angular version:** 
 Angular 9

* **PrimeNG version:**
PrimeNG 9.2.3-lts

* **Browser:** 
All 
 
* **Language:**
TypeScript

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
