### ISSUE TITLE
When table is lazy and having sorting then "lazyLoad" execute twice

### ISSUE THREAD

**Issue by lightstore** [primefaces/primeng#9904]
Dear sirs,

when table initialize problem solved but,
when apply new sort table call again server twice.

When click column header for sorting table response:
1.onClick      line 3190
   sort           line 1009
   **sortSingle line 1058 <--- one call**

2.ngOnChanges   line 891
   **sortSingle          line 1058  <--- second call**

_Originally posted by @lightstore in https://github.com/primefaces/primeng/issues/9810#issuecomment-779666465_

**Comment by yigitfindikli** [comment]
Hi @lightstore,

I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our [stackblitz template](https://stackblitz.com/github/primefaces/primeng-issue-template).
