### ISSUE TITLE
PrimeNG V11.2.3 Dynamic dialog auto refreshing parent

### ISSUE THREAD

**Issue by sridharpedamallu** [primefaces/primeng#9908]
On close of dialog window. The parent window is automatically refreshing. In previous versions it was not the case.
Is it a bug? or is it meant to be?

Angular version : 10.2.0
primeng version: 11.2.3 / 11.2.2

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a stackblitz example.
