### ISSUE TITLE
p-picklist drag and drop is not working correctly.  Can verify on your own PrimeNG showcase (drag Bamboo Watch).

### ISSUE THREAD

**Issue by paul-lucidLIFT** [primefaces/primeng#9910]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Dragging from source list to destination displays visible source list (only drops selected item), but source list is dragged.  Looks like maybe the wrong container element is being selected for dragging?

**Expected behavior**
Only the select item from the source list should be visible (dragged).

**Minimal reproduction of the problem with instructions**
On your own showcase, navigate to the p-picklist page and on the first example at the top of the page, drag 'Bamboo Watch' from source to target.  Should be obvious.

**What is the motivation / use case for changing the behavior?**
This is not how previous versions worked - in the midst of an upgrade to Angular 11 so a quick fix would be appreciated.

**Please tell us about your environment:**
MacOS 11.1, Chrome 88

* **Angular version:** 11.1.2

* **PrimeNG version:** 11.2.0

* **Browser:** Chrome 88.
* 
* **Language:** Typescript 4.05

**Comment by paul-lucidLIFT** [comment]
Thank you for looking at this so quickly!

**Comment by yigitfindikli** [comment]
Fixed in https://github.com/primefaces/primeng/commit/83102d238abca1e4a6847cd0eadd8fd3f77e1102
