### ISSUE TITLE
Dropdown component, when `editable=true` doesn't allow to override placeholder styles

### ISSUE THREAD

**Issue by camilogiraldo** [primefaces/primeng#9911]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**

Dropdown component, when `editable=true` doesn't allow to override placeholder styles. No `p-placeholder` class is being added to the label.

**Expected behavior**

`p-placeholder` class added to override editable-dropdown component

**Minimal reproduction of the problem with instructions**

1. Create a dropdown with editable=true
https://stackblitz.com/edit/primeng-dropdown-demo-yeq1lv

**What is the motivation / use case for changing the behavior?**

Appropriately style the placeholder on editable-dropdown selects.

**Please tell us about your environment:**

* **Angular version:** 11.0.4 

* **PrimeNG version:** ^11.0.0

* **Browser:** [all x | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by yigitfindikli** [comment]
This is expected. You can style placeholders like this;

```
// Not Editable
:host ::ng-deep .p-dropdown .p-dropdown-label.p-placeholder {
    color:red;
}

//Editable
:host ::ng-deep .p-dropdown-label.p-inputtext::placeholder {
    color:red;
}
```

**Comment by camilogiraldo** [comment]
Thanks @yigitfindikli ! It worked for me ! :D
