### ISSUE TITLE
Migration v9 to v11: Application breaking because of filters

### ISSUE THREAD

**Issue by smunir** [primefaces/primeng#9926]
I have an application generated using Jhipster PrimeNG Blueprint. It enables table filtering using 'filters' as 

`this.myTable.filters.filterField.value`

Since filters definition in table.ds has been updated from

`
@Input() filters: { [s: string]: FilterMetadata; } = {};
`

to  

`
filters: {
        [s: string]: FilterMetadata | FilterMetadata[];
    };
`

on upgrading app to v11 is breaking giving error  

> Property 'value' does not exist on type 'FilterMetadata | FilterMetadata[]'.
>   Property 'value' does not exist on type 'FilterMetadata[]'.ts(2339)

Migration Guide doesn't say anything about this. This must be enlisted in Migration guide under Breaking Changes.
Is there a work around to tackle this change without breaking application?

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.

**Comment by smunir** [comment]
Alright, but atleast add this in migration guide
