### ISSUE TITLE
p-invalid css class not working?

### ISSUE THREAD

**Issue by OPunktSchmidt** [primefaces/primeng#9928]
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Plunkr Case (Bug Reports)**

https://stackblitz.com/github/OPunktSchmidt/PrimeNG-PInvalid-Issue

**Current behavior**

The p-invalid css class does not make the text "Username is not available." red. Look at the stackblitz example

**Expected behavior**

Text "Username is not available." should be red.

**Minimal reproduction of the problem with instructions**

Look at the stackblitz example.

**Please tell us about your environment:**

I upgraded my project form PrimeNG / Angular 10 to 11 and noticed this problem. I does not happen with PrimeNG / Angular 10.

* **Angular version:** 11.2.1

* **PrimeNG version:** 11.2.3

**Comment by Halynsky** [comment]
@OPunktSchmidt Hello
By debugging the official website of PrimeNG, I just have noticed that they have another class for error style there.
It's `p-error`. And its works correctly.
Angular 12
PrimeNG 12

**Comment by yigitfindikli** [comment]
You can use ng-invalid and ng-dirty in same time.
