### ISSUE TITLE
Toast messages don't handle very small screens well

### ISSUE THREAD

**Issue by adama357** [primefaces/primeng#9930]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
If I set the device (in the browser dev tools) to be something very narrow like iPhone 5/SE, the toast message exceeds the horizontal boundaries of the screen.

![toast](https://user-images.githubusercontent.com/20462430/108893655-f6437800-75d6-11eb-8af0-b14f29211257.png)

**Expected behavior**
The toast message should horizontally shrink as needed to fit the screen (with margins on either side)

**Minimal reproduction of the problem with instructions**
Docs page: https://www.primefaces.org/primeng/showcase/#/toast

**What is the motivation / use case for changing the behavior?**
It looks unintentional / wrong

**Please tell us about your environment:**
Windows 10

* **PrimeNG version:** 11

* **Browser:** [Chrome 88 ]

**Comment by andi-dev** [comment]
I would have also expected toasts to scale nicely on smaller screens. My solution to handle this myself is adding the following css rule:

```
.p-toast {
  max-width: calc(100vw - 40px);
}
``` 

The toast is positioned at 20px from the right, thus substracting 40px from the viewport width is nicely centering the toast in the middle of the screen.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by anuragjatofficial** [comment]
Looks like we still have this issue for smaller screens 
![image](https://github.com/user-attachments/assets/dfd437af-fa89-4297-9c89-83a432feba3f)

---
toast is lacking responsiveness for smaller screen sizes , I feel @andi-dev  provided nice solution for this issue

**Comment by mustard123** [comment]
This is still an issue

**Comment by SalvatoreCapano** [comment]
@andi-dev 's solution isn't working for me if custom class is defined in a vue component, but we can set the value at component level, as explained in Pass Through docs ( https://primevue.org/passthrough/#global ). like this:
app.use(PrimeVue, {
    // ...
    pt: {
        toast: {
            root: {
                style: 'max-width: calc(100vw - 40px);'
            }
        },
    }
});

**Comment by nomanocra** [comment]
The issue is still there. On my side I tried to override the styles but overriding p-toast 
`.p-toast {
  max-width: calc(100vw - 40px);
}`

or stylesheet 

`toast: {
     root: {
      style: 'max-width: calc(100vw - 40px);'
     }
  },`

none of those options works for me.

**Comment by Denis-Wanjohi** [comment]
.p-toast {
  max-width: calc(100vw - 40px);
}

this worked pretty good for me
