### ISSUE TITLE
PrimeNG Table Bug

### ISSUE THREAD

**Issue by hradev** [primefaces/primeng#9932]
Hi There I reported the bug last week on Primevue for the datatable.

I found another bug (well I think it is a bug) on PrimeNG table.

Goto this link (provided by PrimeNG demo)
https://stackblitz.com/edit/primeng-tablecrud-demo

Add columnFilter to name column for instance.

Paginate to page 2 .
Edit Product details.

Table jumps back to page 1.

Doesn't do that without the columnFilter present.

Regards,
H

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a stackblitz example.
