### ISSUE TITLE
OnPush default should be more explicitly documented

### ISSUE THREAD

**Issue by daleclements** [primefaces/primeng#9936]
**I'm submitting a ...**  (check one with "x")
```
I'm not sure how to categorize this
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/primeng-menuitem-hover-changedetection-only

**Current behavior**
See stackblitz
When making changes to a MenuItem the changes are not reflected in the UI until the MenuItem is hovered over.

**Expected behavior**
I'm not sure. See the motivation section below. 

It does seem awkward to have to reassign the entire array of MenuItems every time I want to display a change to one item, but I don't know what a better solution would be. Perhaps just a note in the documentation that a function like this is necessary?

```
    /*
     * PrimeNG switched to using OnPush change detection by default in version 10
     * As a result, if we want changes to any MenuItem to be reflected in the UI, we need
     * to reassign the collection that is used as the [value] in the <p-menubar>
     */
    refreshView() {
        this.menuItems = [...this.menuItems];
    }
```

**Minimal reproduction of the problem with instructions**
See stackblitz

**What is the motivation / use case for changing the behavior?**
I initially began creating this issue as a bug, but now I know this is caused by an intentional change in PrimeNG to make all components use OnPush change detection. Perhaps this qualifies more as a Feature Request than a bug then.

The problem is that Angular does not use OnPush by default, so working with PrimeNG components requires different practices than Angular components normally do. That difference should be explicitly documented.

Currently, the only mention of this change to OnPush that I could find is in the blog post announcing PrimeNG 10, and it isn't elaborated on nor is it included in the "Breaking Changes" segment even though it does in fact break functionality that relied on the default change detection strategy used in prior versions.

There should at least be a warning in the "Getting Started" guide informing users of the OnPush default because working with these components without knowing that results in unexpected behavior.

**Comment by waratah** [comment]
This is a breaking change from when I upgraded from V8 to V13.    Most of my inserts and deletes failed because they worked on the array with push and splice.   It is therefore very important to mention this in the upgrade notes as well as upfront for other clients.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
