### ISSUE TITLE
Split Button to implement pButton p-button-text class

### ISSUE THREAD

**Issue by pekevski** [primefaces/primeng#9937]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewed in detail and assisted.

https://stackblitz.com/edit/github-njv6tf?file=src/app/app.component.html

**Current behaviour**
Implementing a split button with the styleClass of p-button-text

**Expected behaviour**
The button should be flattened to be text only as suggested in various theme.css styles. eg:

```
.p-button.p-button-secondary.p-button-text,
.p-buttonset.p-button-secondary > .p-button.p-button-text,
.p-splitbutton.p-button-secondary > .p-button.p-button-text {
    background-color: transparent;
    color: #607d8b;
    border-color: transparent;
}
```

I would recommend adding a buttonStyle input on the splitbutton component that gets passed to the #defaultButton in the current splitbutton.ts implementation? Unless there is some styling that I have missed.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/github-njv6tf?file=src/app/app.component.html

**What is the motivation / use case for changing the behaviour?**
The split button should flatten itself if using the p-button-text styling 

* **Angular version:** 11.X

* **PrimeNG version:** 11.2.0

**Comment by yigitfindikli** [comment]
You can use p-button-label.

**Comment by pekevski** [comment]
Sorry if I don't understand, but how would you use p-button-label? Do you mean to override the css class manually?

**Comment by mukeshk** [comment]
Is this fixed already? I see the same issue
