### ISSUE TITLE
Table Crud Bug

### ISSUE THREAD

**Issue by hradev** [primefaces/primeng#9938]
Hi,

Please see stackblitz:

https://stackblitz.com/edit/primeng-tablecrud-demo-h6pjfa

Goto page 2 of the product list, edit something and save. Table jumps back to page 1.

It happens when I add a p-columnFilter to a column of the table.

Regards,
H

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
