### ISSUE TITLE
PrimeNG 11 Column Filter: Apply/Clear Button spacing

### ISSUE THREAD

**Issue by OPunktSchmidt** [primefaces/primeng#9939]
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Current behavior**

If you translate the "Clear" and "Apply" buttons in your own language and the text is longer than die english text the buttons stick together.

![image](https://user-images.githubusercontent.com/7362709/109157508-633f4500-7772-11eb-8b45-2158366bcb49.png)

**Expected behavior**

There should be a default spacing between this buttons so it looks always good in every language.

* **Angular version:** 11.2.1

* **PrimeNG version:** 11.2.3

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by XaviFabregas** [comment]
Can someone explain me how can I translate Apply and Clear buttons? Thx
