### ISSUE TITLE
p-dropdown cannot correctly be bound to simple array

### ISSUE THREAD

**Issue by davidda** [primefaces/primeng#9941]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/github-zlrkvc?file=src/app/app.component.html

**Current behavior**
The property bound via ngModel is never updated.

**Expected behavior**
The property should be updated.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/github-zlrkvc?file=src/app/app.component.html

When you bind a dropdown to a list of strings
 [options]="['New York', 'Berlin']"
it is displayed correctly, but the model is never updated.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 11.x

* **PrimeNG version:** 11.2.2

**Comment by s4m0r4m4** [comment]
I've run into this as well

**Comment by s4m0r4m4** [comment]
The problem is here: https://github.com/primefaces/primeng/blob/4915754e2d3b7015b54afa65ac97752d50f808f2/src/app/components/dropdown/dropdown.ts#L421.

If you provide optionValue, it naturally uses it (good). If you don't, it then checks if you provided optionLabel - if you did, it simply passes back the selected option, if you did not, it tries to access option.value, which does not exist for options in a plain list. 

I've confirmed that if I provide an input for "optionLabel" then it is able to get the property correctly from the form control model, but of course then each item in the list shows as "empty", which is problematic. @yigitfindikli are you open to a PR to simply remove the 2nd ternary operation?

**Comment by s4m0r4m4** [comment]
This commit, 2 months ago, resulted in this change: https://github.com/primefaces/primeng/commit/46cb5069a3f42a2ff5918d7cdfcef3713c088a72

**Comment by davidda** [comment]
@s4m0r4m4 Removing the 2nd ternary case would probably break the case when you assign a SelectItem[] as data source and don't specify _optionLabel_ and _optionValue_. 

Perhaps it would be better to inspect the data source when it is assigned and determine whether it it's a simple array or an object array.
Alternatively, a new input parameter could enable the "simple array" mode.

**Comment by s4m0r4m4** [comment]
I'm not too familiar with the SelectItem interface, but if that's something they support then I get it that they can't simply remove it. However they want to fix it is fine by me, but support for a simple list is a must.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
