### ISSUE TITLE
SelectableRow when disabled provides no way to target styling for disabled row.

### ISSUE THREAD

**Issue by Coderrob** [primefaces/primeng#9944]
I'm submitting a feature request.
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When the p-table component is used with the `[pSelectableRow]` directive there is a property to set the row to disabled. Currently there are no styles or indicators applied that the table row is disabled for selection.

**Expected behavior**
 In this case it would be helpful for external component users to be able to take action, style wise, on the row by using a new or existing css class applied based on the `isEnabled()` flag within the `SelectableRow` directive.

We've used `p-disabled-row` for our tweak to the `SelectableRow` directive. Just a suggestion. Naming is hard. :)

```
    host: {
        '[class.p-selectable-row]': 'isEnabled()',
        '[class.p-highlight]': 'selected',
+        '[class.p-disabled-row]': '!isEnabled()',
        '[attr.tabindex]': 'isEnabled() ? 0 : undefined'
    }
```

**Minimal reproduction of the problem with instructions**
`<tr [pSelectableRow]="rowData" [pSelectableRowDisabled]="true">`

**What is the motivation / use case for changing the behavior?**
No way to easily apply a disabled styling to the contents of the p-table row when it is disabled for selection. 

**Please tell us about your environment:**

* **Angular version:** 5.X
9.x

* **PrimeNG version:** 5.X
10.0.3

* **Browser:** 
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS / ES6

* **Node (for AoT issues):** `node --version` =   
N/A

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by Coderrob** [comment]
> Hi,
> 
> So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!
> 
> Best Regards,

Sure thing! Thank you @mertsincan. :)
