### ISSUE TITLE
Childless PanelMenu item appears to "open" and "close"

### ISSUE THREAD

**Issue by adama357** [primefaces/primeng#9946]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://github-1tmwas.stackblitz.io

**Current behavior**
With certain themes (such as Nova), opening a PanelMenu header item results in that item remaining a certain color (in this case blue) until that item is closed.  But if a header item doesn't have any children (and is just a button), it still gets toggled on and off, as though it were opening and closing. (E.g., half the times you click on it, it turns blue.)

**Expected behavior**
For childless items, they wouldn't stay modified after being clicked. 

**Minimal reproduction of the problem with instructions**
See stackblitz

**What is the motivation / use case for changing the behavior?**
PanelMenus can be used for page navigation, and if you click on a page to navigate to it, and then click it again, it shouldn't be toggling it on and off. 

* **PrimeNG version:** 11.2

**Comment by yigitfindikli** [comment]
Stackblitz example not working. And If the problem causes by legacy themes we're not updating legendary themes, legacy themes still exist for backward compatibility. Please feel free to reopen with a new stackblitz example or more detail.
