### ISSUE TITLE
Cannot add an icon to a button dynamically if the initial state is an empty string (i.e. no icon)

### ISSUE THREAD

**Issue by adbarrett** [primefaces/primeng#9950]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
If an icon is linked to a property and the initial state is an empty string (i.e. no icon), attempting to add the icon later by updating the property to an icon class (e.g. pi pi-check) results in a console error.

**Expected behavior**
If the initial state of the icon is hidden (i.e. the icon class is an empty string), it should be possible to add an icon later by updating the property it is linked to.

**Minimal reproduction of the problem with instructions**
Follow this link and click the button. The counter should increase to 1 and the pi-check icon should appear however it instead results in the following console error:
![image](https://user-images.githubusercontent.com/8956017/109333252-200ad200-7857-11eb-8b98-b680b06df69e.png)

[https://github-cztijh.stackblitz.io](https://github-cztijh.stackblitz.io)

app.component.html:
```
<h2>PrimeNG Issue Template</h2>
<p>Please create a test case and attach the link of the plunkr to your github issue report.</p>

<button pButton label="PrimeNG" [icon]="iconClass" (click)="onClick($event)"></button>
{{counter}}
```

app.component.ts:
```
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent {

  counter = 0;

  get iconClass(): string {
    return this.counter === 0 ? "" : "pi pi-check"
  }

  onClick() {
    this.counter++;
  }
}
```

Same example but with the workaround of adding an icon class that doesn't exist:
[https://github-p1p66t.stackblitz.io](https://github-p1p66t.stackblitz.io)

app.component.html:
```
<h2>PrimeNG Issue Template</h2>
<p>Please create a test case and attach the link of the plunkr to your github issue report.</p>

<button pButton label="PrimeNG" [icon]="iconClass" (click)="onClick($event)"></button>
{{counter}}
```

app.component.ts:
```
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent {

  counter = 0;

  get iconClass(): string {
    return this.counter === 0 ? "abcde" : "pi pi-check"
  }

  onClick() {
    this.counter++;
  }
}
```

**What is the motivation / use case for changing the behavior?**
It would be nice to be able to show or hide an icon from the button (e.g. a spinner) based on some property (e.g. an isLoading property) and have the initial state of hidden. E.g. load the page, button does not have an icon, click the button which triggers something in the backend, the button gets disabled and shows a spinner icon to show something is happening. The spinner disappears and the button is re-enabled once the backend process has finished.

* **Angular version:** 9.0.7

* **PrimeNG version:** 11.2.2

* **Browser:** Chrome 88.0.4324.182 (not tested in other browsers)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
