### ISSUE TITLE
PickList drag item in Chrome cause strange behaviour when ripple is active

### ISSUE THREAD

**Issue by fabien-ml** [primefaces/primeng#9951]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
https://primefaces.org/primeng/showcase/#/picklist

**Current behavior**
In the primeng picklist demo in the doc,
When ripple is activated and you try to drag an item quickly before the ripple effect end, all part that is "covered" by the ripple is dragged.

**Expected behavior**
Only the item should be dragged.

**Minimal reproduction of the problem with instructions**
- Go to primeng picklist doc with chrome
- Try to drag an item quickly before the ripple effect end

**What is the motivation / use case for changing the behavior?**
In term of UX, user doesn't have to wait a ripple effect end before dragging an item properly

* **Browser:** 
Chrome 88

**Comment by yigitfindikli** [comment]
Fixed in https://github.com/primefaces/primeng/issues/9943.
