### ISSUE TITLE
p-cascadeSelect optionGroupChildren wrong type definition

### ISSUE THREAD

**Issue by fabien-ml** [primefaces/primeng#9952]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Current behavior**
When using p-cascadeSelect [optionGroupChildren]="['states', 'cities']" (like in the doc), the typescript compiler says "Type 'string[]' is not assignable to type 'string'".

Setting the type manually to string[] in the .d.ts file of primeng fix it.

**Expected behavior**
Should no cause error.

**Minimal reproduction of the problem with instructions**
- Create a new angular project en vscode
- Add primeng
- Folow primeng cascade select doc example

**Please tell us about your environment:**
- Mac OS
- VS Code
- NPM

* **Angular version:** 11.2.3

* **PrimeNG version:** 11.2.3

**Comment by yigitfindikli** [comment]
Hi @fabien-ml,

I couldn't replicate it with v11.2.3 can you share a sample project or stackblitz example?

**Comment by fabien-ml** [comment]
Hi, here is a sample project and screenshot from my ide.
![Capture d’écran 2021-03-01 à 08 49 36](https://user-images.githubusercontent.com/2832351/109467275-3d17ee80-7a6b-11eb-8fef-f8a3dca402f4.png)

[primeng-sandbox.zip](https://github.com/primefaces/primeng/files/6059864/primeng-sandbox.zip)

**Comment by yigitfindikli** [comment]
Thanks for your report and effort. I'll add this issue to our roadmap.
