### ISSUE TITLE
p-columnFilter: Built in empty filter

### ISSUE THREAD

**Issue by OPunktSchmidt** [primefaces/primeng#9953]
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Current behavior**

The built in filters offer no possibility to filter for empty entries. But I think this is a common use case. For example, if you have a list of appointments and each appointment is assigned to a participant. The user now wants to filter all entries where the column "Participant" is empty. This is currently not possible or has to be implemented by the developer.

![image](https://user-images.githubusercontent.com/7362709/109473388-8409e200-7a73-11eb-8f9c-f4881c668b33.png)

**Expected behavior**

The built-in filters should provide a way to filter for empty entries. This should be optional. Possibly controllable via a setting like "[filterforEmpty]=true".

**What is the motivation / use case for changing the behavior?**

This is a very common use case. Many applications need something like this.

**PrimeNG version:** 11

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
