### ISSUE TITLE
[p-table]  formarray caused cannot find control with path

### ISSUE THREAD

**Issue by DKLigos** [primefaces/primeng#9956]
I am trying to create the PrimeNg editable table with angular forms, but I got the following error. " Cannot find control with path: 'tableRowArray -> '" The same thing I tried with "table" it is working fine. But with the p-table I am getting this kind of behavior? How can I fix this issue.
https://stackblitz.com/github/DKLigos/primeTableForm

**Comment by sidpssp** [comment]
@DKLigos - I was just checking your sample code on stackblitz.

If you just change the "index" to "rowIndex" in the file app.component.html, it starts to work fine. 

As Is:
<ng-template pTemplate="body" let-product let-i="index"> 

To Be:
<ng-template pTemplate="body" let-product let-i="**rowIndex**">
