### ISSUE TITLE
Unable to install primeng with angular 2.0.1

### ISSUE THREAD

**Issue by jaurakunal** [primefaces/primeng#996]
Hi,

I've upgraded my code to angular 2.0.1. When I try running npm install primeng --save it errors out with these lines at the end of npm-debug.log 

**638 verbose stack Error: The package reflect-metadata@0.1.8 does not satisfy its siblings' peerDependencies requirements!
638 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:125:32
638 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:268:7
638 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:142:5
638 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
638 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
638 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
638 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
638 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
638 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
638 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
639 verbose cwd C:\Kunal\Personal\MobileApps\MHS\Website\Paperfit2.0
640 error Windows_NT 6.3.9600
641 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "primeng" "--save"
642 error node v4.2.1
643 error npm  v2.14.7
644 error code EPEERINVALID
645 error peerinvalid The package reflect-metadata@0.1.8 does not satisfy its siblings' peerDependencies requirements!
645 error peerinvalid Peer angular-in-memory-web-api@0.1.3 wants reflect-metadata@~0.1.8
645 error peerinvalid Peer angular2@2.0.0-beta.12 wants reflect-metadata@0.1.2
645 error peerinvalid Peer primeng@0.9.1 wants reflect-metadata@0.1.2
646 verbose exit [ 1, true ]**

Here's what I have in my package.json file

**{
  "name": "paperfit",
  "version": "2.0.0",
  "description": "Perfit redesigned",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "postinstall": "typings install",
    "typings": "typings",
    "build:vendor": "gulp copy-vendor-files",
    "build:dev": "gulp clean-dist && gulp copy-vendor-files && gulp build --dev",
    "build:prod": "gulp clean-dist && gulp copy-vendor-files && gulp build --production && node systemjs.builder.js",
    "deploy:local": "gulp clean-local-tomcat && gulp deploy-to-local-tomcat"
  },
  "author": "Kunal Jaura",
  "license": "ISC",
  "dependencies": {
    "@angular/common": "~2.0.1",
    "@angular/compiler": "~2.0.1",
    "@angular/core": "~2.0.1",
    "@angular/forms": "~2.0.1",
    "@angular/http": "~2.0.1",
    "@angular/platform-browser": "~2.0.1",
    "@angular/platform-browser-dynamic": "~2.0.1",
    "@angular/router": "~3.0.1",
    "@angular/upgrade": "~2.0.1",

    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.39",
    "zone.js": "^0.6.25",

    "angular-in-memory-web-api": "~0.1.1",
    "bootstrap": "^3.3.6",
    "moment": "^2.14.1",
    "ng2-bs3-modal": "^0.6.1"
  },
  "devDependencies": {
    "codelyzer": "0.0.24",
    "concurrently": "^3.0.0",
    "del": "^2.2.1",
    "gulp": "^3.9.1",
    "gulp-autoprefixer": "^3.1.0",
    "gulp-clean-css": "^2.0.10",
    "gulp-concat": "^2.6.0",
    "gulp-if": "^2.0.1",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-typescript": "^2.13.6",
    "gulp-uglify": "^1.5.4",
    "lite-server": "^2.2.2",
    "systemjs-builder": "^0.15.23",
    "tslint": "^3.13.0",
    "typescript": "^2.0.3",
    "typings": "^1.4.0",
    "yargs": "^4.7.1"
  }
}**

Any help on this would be much appreciated.

Cheers
Kunal

**Comment by watalberto** [comment]
Did you try removing reflect-metadata from your package.json and letting it decide which version download??
My package.json is very similar, just that I don't have 2 of your dependencies and I never install 'reflect-metadata', I just leave npm choose which version install...

**Comment by jaurakunal** [comment]
@watalberto thanks for that suggestion. I did try your appraoch and the reflect-metadata error went away but I now get this.

1739 verbose stack Error: The package rxjs@5.0.0-beta.12 does not satisfy its siblings' peerDependencies requirements!
1739 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:125:32
1739 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:268:7
1739 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:142:5
1739 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
1739 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
1739 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
1739 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
1739 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
1739 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
1739 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
1740 verbose cwd C:\Kunal\Personal\MobileApps\MHS\Website\Paperfit2.0
1741 error Windows_NT 6.3.9600
1742 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "primeng" "--save"
1743 error node v4.6.0
1744 error npm  v2.15.9
1745 error code EPEERINVALID
1746 error peerinvalid The package rxjs@5.0.0-beta.12 does not satisfy its siblings' peerDependencies requirements!
1746 error peerinvalid Peer @angular/core@2.0.1 wants rxjs@5.0.0-beta.12
1746 error peerinvalid Peer @angular/http@2.0.1 wants rxjs@5.0.0-beta.12
1746 error peerinvalid Peer @angular/router@3.0.1 wants rxjs@5.0.0-beta.12
1746 error peerinvalid Peer angular-in-memory-web-api@0.1.3 wants rxjs@5.0.0-beta.12
1746 error peerinvalid Peer angular2@2.0.0-beta.12 wants rxjs@5.0.0-beta.2

:-(

**Comment by jaurakunal** [comment]
@watalberto - My bad. Stupid mistake. Forgot to delete the node_modules folder and re-install everything after removing refelct-metadata from my package.json.

Once I did that the install went through fine. Interestingly, though, it ended up installing the same version of reflect-metadata that the package.json wanted it to.

Anyways, thanks for helping out with this.
Cheers
Kunal

**Comment by watalberto** [comment]
hey! that's good, you're welcome! ;)
