### ISSUE TITLE
Table goes back to page 1 on data fetch when filter is populated

### ISSUE THREAD

**Issue by saramcicchi** [primefaces/primeng#9960]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-table-data-fetch-resets-pagination-with-filter

**Current behavior**
1. Go to page 2
2. Click "Fetch Data" button -> table stays on page 2 as expected
3. Type something into the "Global Search" box
4. Go to page 2
5. Click "Fetch Data" button -> table goes to page 1 which is unexpected

**Expected behavior**
Step 5 should not go back to page 1 but should instead stay on the page it was on. Setting the table with new data should behave the same whether or not a filter is provided.

**What is the motivation / use case for changing the behavior?**
Say a user creates a filter and changes pages, then we receive an event that the data changed, such as a record being updated, added or removed, the table will render the changes and reset the pagination instead of just rendering the changes.

Note this is similar in nature to #9236 which has the same issue but with scrolling instead of pagination.

The line causing this issue is https://github.com/primefaces/primeng/blob/11.2.3/src/app/components/table/table.ts#L1296. 

**Please tell us about your environment:**

* **Angular version:** 10.X, 11.X

* **PrimeNG version:** 10.X, 11.X

* **Browser:** all

 
* **Language:** all

* **Node (for AoT issues):** `node --version` =   14.15.4

**Comment by yigitfindikli** [comment]
This is expected,  when filtering or data changing is done, data display should move to the first page by design.

**Comment by saramcicchi** [comment]
Hi @yigitfindikli, can you please reexamine? The behavior is _inconsistent_. You stated that when data changing is done, data display should move to the first page but that is not the case, _unless_ there is a filter applied. Please see my stackblitz which demonstrates this.
