### ISSUE TITLE
p-table: property to check if a filter is active

### ISSUE THREAD

**Issue by OPunktSchmidt** [primefaces/primeng#9962]
[ ] bug report => Search github for a similar issue or PR before submitting
[X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Expected behavior**

We need a simple way to check if a filter is active to enable buttons. In my example i want to enable a button to reset all filters if a active filter exists.

![image](https://user-images.githubusercontent.com/7362709/109783702-8f434600-7c0a-11eb-83cf-d9b6bbc4fab1.png)

None of these settings seem to be suitable for this.

![image](https://user-images.githubusercontent.com/7362709/109783830-b568e600-7c0a-11eb-9e7e-f77982dad746.png)

**PrimeNG version:** 11

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
