### ISSUE TITLE
An error when clicking outside Filter Menu.

### ISSUE THREAD

**Issue by diosvo** [primefaces/primeng#9964]
It has an error when I try click outside the table to close Filter Menu.
![image](https://user-images.githubusercontent.com/51939323/109793625-7c9b3200-7c47-11eb-8a01-fa605dfed589.png)

And this is a demo by PrimeNg on Stackblitz: https://primeng-tablefilter-demo.stackblitz.io/
Thank for your help!

**Comment by yigitfindikli** [comment]
I couldn't replicate it with https://stackblitz.com/edit/primeng-tablefilter-demo
