### ISSUE TITLE
calendar minDate and maxDate settings not working

### ISSUE THREAD

**Issue by cforeman75** [primefaces/primeng#9968]
minDate and maxDate are being set, but UI is not showing any month navigation for these settings.

Angular CLI: 11.2.2
Node: 12.14.1
OS: darwin x64

Angular: 11.2.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.2
@angular-devkit/build-angular   0.1102.2
@angular-devkit/core            11.2.2
@angular-devkit/schematics      11.2.2
@angular/cdk                    11.2.2
@angular/cli                    11.2.2
@angular/material               11.2.2
@schematics/angular             11.2.2
@schematics/update              0.1102.2
rxjs                            6.6.6
typescript                      4.0.5
"primeng": "11.2.3",

defaultDate: Date = new Date();

ngOnInit() {
    this.minDate.setDate(this.defaultDate.getDate() - 30);
    this.maxDate.setDate(this.defaultDate.getDate() + 30);
    this.maxCollectionDate.setDate(this.defaultDate.getDate() + 180);
}

<p-calendar [showIcon]="true"
                        [defaultDate]="defaultDate"
                        [hideOnDateTimeSelect]="true"
                        [minDate]="minDate"
                        [maxDate]="maxDate"
                        [readonlyInput]="true"
                        formControlName="visitDate">
            </p-calendar>

<img width="411" alt="Calendar" src="https://user-images.githubusercontent.com/73716878/109998433-372a4380-7cdf-11eb-9409-835bd9868b3a.png">

**Comment by yigitfindikli** [comment]
I couldn't replicate it. You can check [this example.](https://stackblitz.com/edit/primeng-calendar-demo-gf5j9y?file=src/app/app.component.ts)
