### ISSUE TITLE
Dialog resize behavior is inconsistent

### ISSUE THREAD

**Issue by an-austin-jones** [primefaces/primeng#9969]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-dialog-demo-xabnqb?file=src/app/app.component.html

**Current behavior**
Dialog resizing behaves differently depending on if it was moved or not. Before dragging the dialog by click and holding the header, resizing the dialog works like a zoom (top left moves as well). After dragging (moving) the dialog, resizing anchors the top left of the dialog.

**Expected behavior**
The behavior or resizing to be consistent regardless of having dragged the dialog. I personally prefer the zoom resizing.

**Minimal reproduction of the problem with instructions**
In the demo linked (can be replicated on the most recent primeng page for the dialog overlay component as well), 
1. click the "Show" button.
2. resize the dialog that popped up by click and holding the bottom right. Notice the zoom method of resizing.
3. move the dialog by click and holding the header
4. again, resize the dialog. Notice the anchored top left corner.

**What is the motivation / use case for changing the behavior?**
Consistent behavior

* **Angular version:**
11.0.0

* **PrimeNG version:**
11.0.0-rc.1

* **Browser:** Chrome 88

**Comment by yigitfindikli** [comment]
This is caused by `position: fixed` and necessary for draggable dialog.
