### ISSUE TITLE
P table Global Search function throws error in angular 11

### ISSUE THREAD

**Issue by swarup-bhol** [primefaces/primeng#9970]
(input)="dt.filterGlobal($event.target.value, 'contains')" 

here due to angular 11 strict type checking i am getting error in value that possibly target can be null.
Because of this ng build is also not working.

i have tried following things
(input)="dt.filterGlobal($event.target!.value, 'contains')" 
(input)="dt.filterGlobal($event.targe?!.value, 'contains')" 

None of these seems to be
![Screenshot 2021-03-04 at 10 41 52 PM](https://user-images.githubusercontent.com/54322967/110001875-d6c8ef80-7d3a-11eb-878e-eda1fe9f161b.png)
 working

**Comment by yigitfindikli** [comment]
This issue not about PrimeNG. I saw your message on our discord channel as well. You can check https://stackoverflow.com/questions/65536598/primeng-table-filterglobal-ts2339-property-value-does-not-exist-on-type-even .
