### ISSUE TITLE
state storage only working for ptextbox in filter

### ISSUE THREAD

**Issue by MohamedSahir** [primefaces/primeng#9972]
I am using a priming table and save the filter state based on documentation.

Table State
stateStorage="local" stateKey="statedemo-local"

expected o/p :
once set the filter, refresh the page, the selected filter is persisted in the filterbox and result in grid.

current behavior:
it only works for a textbox in filter,all other controls especially dropdown and calendar not set in filter, but the result shown in the grid is the filter .
demo:
[demo-satckblitz](https://stackblitz.com/edit/primeng-tablefilter-demo-w9m7jc?file=src%2Fapp%2Fapp.component.html)

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template

**Comment by MohamedSahir** [comment]
Reopened an issue with angular 11 
this is the version .


  "rxjs": "6.6.3",
    "quill": "1.3.7",
    "tslib": "2.1.0",
    "primeng": "11.2.2",
    "zone.js": "0.10.2",
    "chart.js": "2.9.3",
    "primeflex": "2.0.0",
    "primeicons": "4.1.0",
    "@types/node": "8.9.5",
    "@angular/cdk": "11.0.4",
    "@angular/core": "11.0.9",
    "@angular/forms": "11.0.9",
    "@types/jasmine": "3.3.16",
    "@angular/common": "11.0.9",
    "@angular/router": "11.0.9",
    "@angular/compiler": "11.0.9",
    "@types/jasminewd2": "2.0.8",

---


This is the demo attached :
[demo](https://stackblitz.com/edit/github-za58gp-a4sy4x?file=package.json)
