### ISSUE TITLE
state storage only working for ptextbox in filter  ##9972

### ISSUE THREAD

**Issue by MohamedSahir** [primefaces/primeng#9976]
https://github.com/primefaces/primeng/issues/9972

I have created the issue and the issue has closed. Therefore created this issue with an updated version. the issue is  select something from dropdown or calendar fields, refresh the page, in the grid, we can see the filter result, but not set in dropdown and calendar.it only works with textbox

version details:

  "rxjs": "6.6.3",
    "quill": "1.3.7",
    "tslib": "2.1.0",
    "primeng": "11.2.2",
    "zone.js": "0.10.2",
    "chart.js": "2.9.3",
    "primeflex": "2.0.0",
    "primeicons": "4.1.0",
    "@types/node": "8.9.5",
    "@angular/cdk": "11.0.4",
    "@angular/core": "11.0.9",
    "@angular/forms": "11.0.9",
    "@types/jasmine": "3.3.16",
    "@angular/common": "11.0.9",
    "@angular/router": "11.0.9",
    "@angular/compiler": "11.0.9",
    "@types/jasminewd2": "2.0.8",

---

This is the demo attached :
[demo](https://stackblitz.com/edit/github-za58gp-a4sy4x?file=package.json)

**Comment by yigitfindikli** [comment]
I couldn't replicate it with the latest PrimeNG you can check at https://stackblitz.com/edit/primeng-tablefilter-demo-fsokgi

**Comment by yigitfindikli** [comment]
I see the calendar problem on stackblitz. It's fixed in https://github.com/primefaces/primeng/issues/9967
