### ISSUE TITLE
ConfirmDialog component dysfunction

### ISSUE THREAD

**Issue by cholokla** [primefaces/primeng#998]
I have two problems with ConfirmDialog component and Angular 2.0.1.

Firstly, 'rejectIcon' attribute doesn't seem to set icon while 'acceptIcon' is working properly.

Second and more problematic is when I try to use 'confirmationService.confirm' method several times in a row passing different 'message' attributes. It looks like only the first one is set in the dialog, and next calls are still showing the same message.

And one question, could it be possible to not fix the default width od the dialog (if not set manualy using the 'width' attribute)? In such case text areas shoud be set to css no-wrap and in result dialog width will follow text width.

**Comment by kt215** [comment]
It looks like first and second issues will be fixed in 1.0.0-beta.17 by https://github.com/primefaces/primeng/issues/946 and https://github.com/primefaces/primeng/issues/958, respectively.

**Comment by cholokla** [comment]
yes, it works now like a charm :)

only dialog width suggestion left to consider...
