### ISSUE TITLE
Integration of Tailwindcss

### ISSUE THREAD

**Issue by juri-sinitson** [primefaces/primeng#9981]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
The spacing scale is too small, e.g. in case of padding `p-p-0` to `p-p-6` whereas tailwindcss spacing is `p-0` to `p-96`.
Utilities for text scale, rotation and other CSS properties are missing.

**Expected behavior**
PrimeNG is based on/supports/integrates Tailwindcss.

**Minimal reproduction of the problem with instructions**
In case of padding the classes `p-p-7` to `p-p-96` are not there, see https://primefaces.org/primeng/showcase/#/primeflex/spacing and compare it with https://tailwindcss.com/docs/customizing-spacing#default-spacing-scale

PrimeNG has currently no classes comparamble with e.g. 
https://tailwindcss.com/docs/font-size or 
https://tailwindcss.com/docs/rotate#rotate-scale

**What is the motivation / use case for changing the behavior?**
Saving time avoiding pixel pushing when the disired spacing does not fit current spacing of PrimeNG. Same flexibility and configurability for PrimenNG as with tailwindcss.

* **Angular version:** 11.X
* **PrimeNG version:** 11.X

**Comment by yigitfindikli** [comment]
PrimeBlocks on the way. PrimeBlocks will cover features like that.
