### ISSUE TITLE
new version 11.3.0 not support import all module 

### ISSUE THREAD

**Issue by jindovu** [primefaces/primeng#9982]
Hi Everyone,
     Today I upgrade to new version 11.3.0 and I got issue with import all module and I have to repair all component I did because new version not allow to import all module
- Code old
`import {
    TabMenuModule, ConfirmDialogModule, SelectButtonModule, MultiSelectModule, DialogService, ConfirmationService,
    CheckboxModule, InputTextModule, ButtonModule, DialogModule, AutoCompleteModule, DropdownModule, PaginatorModule,CalendarModule, TooltipModule, ListboxModule, SplitButtonModule, PanelModule, DragDropModule, InputTextareaModule,TreeModule, TreeTableModule, KeyFilterModule, ChipsModule, SpinnerModule, AccordionModule, EditorModule, FileUploadModule, DynamicDialogModule, FieldsetModule, DataViewModule, TabViewModule, InputNumberModule, InputSwitchModule
} from "primeng"`
- Now we have seperate one by one like this
`import { TabMenuModule } from "primeng/tabmenu";`

Please help me to check this

Thank you.

**Comment by yigitfindikli** [comment]
'primeng/primeng' imports removed for performance issues.
