### ISSUE TITLE
Changing captcha language does not work

### ISSUE THREAD

**Issue by VILLAN3LL3** [primefaces/primeng#9985]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The initialization of the captcha with the supplied language works. But if the language changes, the captcha is not re-rendered and remains in the original language.

**Expected behavior**
If the language changes the captcha should change the language, too.

**Minimal reproduction of the problem with instructions**
Template:
```
<p-captcha
        #captcha
        [siteKey]="captchaKey"
        theme="dark"
        [language]="(language$ | async) || 'de'"
        (onResponse)="doSomething($event)"
      ></p-captcha>
```
.ts file:
```
language$: Observable<string>;
```

**What is the motivation / use case for changing the behavior?**
Multilanguage app

**Please tell us about your environment:**
We tried it with several operation systems, ides and browsers

* **Angular version:** 5.X
11.x

* **PrimeNG version:** 5.X
11.2.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript 4.1.2

**Comment by jsanz1209** [comment]
As a result of this fix, I now get the following error:

ERROR Error: reCAPTCHA has already been rendered in this element
    at recaptcha__es.js:55
    at Captcha.init (primeng-captcha.js:46)
    at Captcha.ngAfterViewInit (primeng-captcha.js:36)

The captcha is working on, but it breaks javascript code

**Comment by mcrtricolor** [comment]
I'm having the same issue with the same error on console but worse. When i set a language i can't even see the captcha nor render the page.
