### ISSUE TITLE
Autocomplete cursor jump to end

### ISSUE THREAD

**Issue by izll** [primefaces/primeng#999]
Hi,

If type one or more character to autocomplete field, and inserting character before last character, the cursor always jumping to end of the string.
It's reproducible here: http://www.primefaces.org/primeng/#/autocomplete

**Comment by alezhu** [comment]
I use this hack:
In component template
```HTML
<p-autoComplete [ngModel]="Entity"
                (ngModelChange)="onNgModelChange($event)"
                #autoComplete ... >
```
in component class
```typescript 
    onNgModelChange(value: any) {
      let pos = Helpers.getSafe(() => this.autocomplete.input.selectionStart);
      /// Do something here if you need
      if (pos !== undefined) {
        setTimeout(() => {  this.autocomplete.input.selectionEnd = pos });
      }
   }
```
Helpers.getSafe
```typescript
    static getSafe(fn:Function): any {
        try{
            return fn();
        } catch(ignore) {
            return undefined;
        }
    }
```

**Comment by MaheshCasiraghi** [comment]
I found the hack of @alezhu to work even better if i substitute:

`if (pos !== undefined) {
        setTimeout(() => {  this.autocomplete.input.selectionEnd = pos });
      }`

with:

`if (pos !== undefined && pos < this.autocomplete.input.value.length) {
			setTimeout(() => {  this.autocomplete.input.selectionEnd = pos; });
		}`

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.

**Comment by raviganesh12** [comment]
I am using 2.0.6 & still having this issue.

Can't upgrade yet to Angular4
