### ISSUE TITLE
Drag and drop not working reliably

### ISSUE THREAD

**Issue by FlorianLudwig** [primefaces/primeng#9990]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://www.primefaces.org/primeng/showcase/#/dragdrop

**Current behavior**
No drag and drop possible when using Firefox

**Expected behavior**
drag and drop possible when using Firefox

**Please tell us about your environment:**
 * Firefox 86, Linux - Not working
 * Firefox 86, Mac OS X - working
 * Firefox 87, Linux - working
 * Chrome 89, Linux - working
 * Chrome 89, Linux, Mobile View  (dev tools)- not working

**Comment by yigitfindikli** [comment]
I couldn't replicate it with Firefox 86, Mac OS.

**Comment by FlorianLudwig** [comment]
Interesting.

When hovering the elements, the cursor changes but I drag them.

I don't get any errors in the console.

It also fails in an incognito tab with no plugins.

**Comment by demike** [comment]
This show case is also not working in chrome dev tools with touch / mobile view enabled

**Comment by FlorianLudwig** [comment]
Updated to Firefox 87, cannot reproduce the issue anymore.

But can reproduce it in chrome dev tools mobile view, as @demike reported

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
