### ISSUE TITLE
p-tablecheckbox component cannot be selected programmatically

### ISSUE THREAD

**Issue by omerfarukpolat** [primefaces/primeng#9992]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

**Current behavior**
Now it is not possible that change p-tablecheckbox 's situation (checked or not) dynamically. There is no access to necessary variables.

**Expected behavior**
There should be a variable that allows to change the situation of the checkbox in code. So coder can make it checked or non-checked wherever in code.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
I want to highlight all rows that have same value ​​with the clicked row when I clicked a row.

**Please tell us about your environment:**
IDE

* **Angular version:** 5.X  
9.0.2

* **PrimeNG version:** 5.X
9.0.0-rc.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 89.0.4389.82
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
* all

* **Node (for AoT issues):** `node --version` =   
v14.15.4

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
