### ISSUE TITLE
Issue with Previous button on datepicker with min Date

### ISSUE THREAD

**Issue by jaggi510** [primefaces/primeng#9995]
We are seeing issue with previous button with minDate on p-calendar with monthNavigator and yearNavigator. The previous button is not getting disabled on min date month, if you keep clicking on the previous button there is no change in the year navigator after the min year is achieved, only the months are changing, so at this time all the dates are disabled but in the month navigator and year navigator it looks like the valid month and year.
Steps to reproduce:
1. create calendar like this
<p-calendar showIcon="true" [monthNavigator]="true" [yearNavigator]="true" placeholder="MM/DD/YYYY"
          [readonlyInput]="true" formControlName="effectiveStartDate" [yearRange]="yearRange" dateFormat="mm/dd/yy"
          [minDate]="minDate" [maxDate]="maxDate">
        </p-calendar>
setup minDate, maxDate and yearRange. 
2. Now keep clicking on the previous button, after the min Date is passed, you will notice that on every click months are changing but the year is not, and all the dates are disabled.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
