### ISSUE TITLE
 onColResize view does not update

### ISSUE THREAD

**Issue by lingthe** [primefaces/primeng#9996]
I am not sure what I am doing wrong or why is this behave like this but onColResize event with in primeng Table does not behave as I expected: Please look at stackblitz below: when I resize the column, callback is fired (demoResize()) and in that callback I increment variable 'n' and change variable 'b', both bound to the view. View does not update, but when I log values in the function they are updated. Do not know if this is a bug. ( "primeng": "^11.3.0",)
In one of my other projects ( ang 10.xxx,  "primeng": "^9.1.3",) this works as expected ( view is updated on resize), but in the other recent one, with the same versions, does not.

https://stackblitz.com/edit/primeng-tablecolresize-demo-zexgb9
`

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
