### ISSUE TITLE
Button text raised above center in Firefox

### ISSUE THREAD

**Issue by fosztomatyas** [primefaces/primeng#9998]
**I'm submitting a ...**
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

Hello! The button texts are slightly raised above the center in Firefox.

**Expected behavior**

The button texts should be aligned with the horizontal center axis of the button.

**Minimal reproduction of the problem with instructions**

See https://primefaces.org/primeng/showcase/#/button.

![image](https://user-images.githubusercontent.com/32310039/110981553-f6ca6580-836f-11eb-9c9d-689382c6bf39.png)
![image](https://user-images.githubusercontent.com/32310039/110981609-0a75cc00-8370-11eb-9f8d-9337df01b6fe.png)

**Please tell us about your environment:**

Ubuntu 20.04, 

* **PrimeNG version:** 11.3.1

* **Browser:** Firefox 86.0, no plugins

**Comment by yigitfindikli** [comment]
I couldn't replicate it with Firefox v86 with Mac OS.
![image](https://user-images.githubusercontent.com/19997575/111121918-54340180-857e-11eb-85e3-a5cffac4d2ff.png)
