### ISSUE TITLE
p-splitter: updating panelSizes in component should reflect in the UI

### ISSUE THREAD

**Issue by erics2783** [primefaces/primeng#9999]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/github-kwzqsj?file=src/app/app.component.html

**Current behavior**
When I update the variable passed to [panelSizes], the sizes of the panels does not change.

**Expected behavior**
Panel sizes should update to match the value of the variable passed to [panelSizes]

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
* A use case would be a split screen, like a dashboard with table on one side and chart on the other, that allows user to click a button to swap the panels, but keep their sizes (chart panel size stays the same and table panel size stays the same, even though the panels are swapped).

**Please tell us about your environment:**
* Windows 10

* **Angular version:** 11.3

* **PrimeNG version:** 11.2

* **Browser:** [Chrome 88]
 
* **Language:** [TypeScript 4.1]

* **Node (for AoT issues):** `node --version` = 12.14.0

**Comment by rsohi** [comment]
Any Updates on this ?

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
